// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal.proto

package interop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务间消息ID
type InternalMsgId int32

const (
	InternalMsgId_MSG_INTERNAL_INVALID InternalMsgId = 0
	// 服务注册相关 100-199
	InternalMsgId_MSG_INTERNAL_SERVICE_REGISTER   InternalMsgId = 100
	InternalMsgId_MSG_INTERNAL_SERVICE_DEREGISTER InternalMsgId = 101
	InternalMsgId_MSG_INTERNAL_SERVICE_HEARTBEAT  InternalMsgId = 102
	InternalMsgId_MSG_INTERNAL_SERVICE_DISCOVER   InternalMsgId = 103
	// 网关路由相关 200-299
	InternalMsgId_MSG_INTERNAL_GATEWAY_ROUTE     InternalMsgId = 200
	InternalMsgId_MSG_INTERNAL_GATEWAY_BROADCAST InternalMsgId = 201
	InternalMsgId_MSG_INTERNAL_GATEWAY_KICK      InternalMsgId = 202
	// 玩家路由相关 300-399
	InternalMsgId_MSG_INTERNAL_PLAYER_ROUTE         InternalMsgId = 300
	InternalMsgId_MSG_INTERNAL_PLAYER_BIND_SERVER   InternalMsgId = 301
	InternalMsgId_MSG_INTERNAL_PLAYER_UNBIND_SERVER InternalMsgId = 302
	InternalMsgId_MSG_INTERNAL_PLAYER_TRANSFER      InternalMsgId = 303
	// 地图服务器相关 400-499
	InternalMsgId_MSG_INTERNAL_MAP_ENTER_REQUEST  InternalMsgId = 400
	InternalMsgId_MSG_INTERNAL_MAP_ENTER_RESPONSE InternalMsgId = 401
	InternalMsgId_MSG_INTERNAL_MAP_LEAVE_REQUEST  InternalMsgId = 402
	InternalMsgId_MSG_INTERNAL_MAP_LEAVE_RESPONSE InternalMsgId = 403
	InternalMsgId_MSG_INTERNAL_MAP_MOVE_SYNC      InternalMsgId = 404
	InternalMsgId_MSG_INTERNAL_MAP_AOI_ENTER      InternalMsgId = 405
	InternalMsgId_MSG_INTERNAL_MAP_AOI_LEAVE      InternalMsgId = 406
	InternalMsgId_MSG_INTERNAL_MAP_AOI_UPDATE     InternalMsgId = 407
	// 战斗相关 500-599
	InternalMsgId_MSG_INTERNAL_COMBAT_START  InternalMsgId = 500
	InternalMsgId_MSG_INTERNAL_COMBAT_ACTION InternalMsgId = 501
	InternalMsgId_MSG_INTERNAL_COMBAT_END    InternalMsgId = 502
	// 跨服相关 600-699
	InternalMsgId_MSG_INTERNAL_CROSS_SERVER_REQUEST  InternalMsgId = 600
	InternalMsgId_MSG_INTERNAL_CROSS_SERVER_RESPONSE InternalMsgId = 601
)

// Enum value maps for InternalMsgId.
var (
	InternalMsgId_name = map[int32]string{
		0:   "MSG_INTERNAL_INVALID",
		100: "MSG_INTERNAL_SERVICE_REGISTER",
		101: "MSG_INTERNAL_SERVICE_DEREGISTER",
		102: "MSG_INTERNAL_SERVICE_HEARTBEAT",
		103: "MSG_INTERNAL_SERVICE_DISCOVER",
		200: "MSG_INTERNAL_GATEWAY_ROUTE",
		201: "MSG_INTERNAL_GATEWAY_BROADCAST",
		202: "MSG_INTERNAL_GATEWAY_KICK",
		300: "MSG_INTERNAL_PLAYER_ROUTE",
		301: "MSG_INTERNAL_PLAYER_BIND_SERVER",
		302: "MSG_INTERNAL_PLAYER_UNBIND_SERVER",
		303: "MSG_INTERNAL_PLAYER_TRANSFER",
		400: "MSG_INTERNAL_MAP_ENTER_REQUEST",
		401: "MSG_INTERNAL_MAP_ENTER_RESPONSE",
		402: "MSG_INTERNAL_MAP_LEAVE_REQUEST",
		403: "MSG_INTERNAL_MAP_LEAVE_RESPONSE",
		404: "MSG_INTERNAL_MAP_MOVE_SYNC",
		405: "MSG_INTERNAL_MAP_AOI_ENTER",
		406: "MSG_INTERNAL_MAP_AOI_LEAVE",
		407: "MSG_INTERNAL_MAP_AOI_UPDATE",
		500: "MSG_INTERNAL_COMBAT_START",
		501: "MSG_INTERNAL_COMBAT_ACTION",
		502: "MSG_INTERNAL_COMBAT_END",
		600: "MSG_INTERNAL_CROSS_SERVER_REQUEST",
		601: "MSG_INTERNAL_CROSS_SERVER_RESPONSE",
	}
	InternalMsgId_value = map[string]int32{
		"MSG_INTERNAL_INVALID":               0,
		"MSG_INTERNAL_SERVICE_REGISTER":      100,
		"MSG_INTERNAL_SERVICE_DEREGISTER":    101,
		"MSG_INTERNAL_SERVICE_HEARTBEAT":     102,
		"MSG_INTERNAL_SERVICE_DISCOVER":      103,
		"MSG_INTERNAL_GATEWAY_ROUTE":         200,
		"MSG_INTERNAL_GATEWAY_BROADCAST":     201,
		"MSG_INTERNAL_GATEWAY_KICK":          202,
		"MSG_INTERNAL_PLAYER_ROUTE":          300,
		"MSG_INTERNAL_PLAYER_BIND_SERVER":    301,
		"MSG_INTERNAL_PLAYER_UNBIND_SERVER":  302,
		"MSG_INTERNAL_PLAYER_TRANSFER":       303,
		"MSG_INTERNAL_MAP_ENTER_REQUEST":     400,
		"MSG_INTERNAL_MAP_ENTER_RESPONSE":    401,
		"MSG_INTERNAL_MAP_LEAVE_REQUEST":     402,
		"MSG_INTERNAL_MAP_LEAVE_RESPONSE":    403,
		"MSG_INTERNAL_MAP_MOVE_SYNC":         404,
		"MSG_INTERNAL_MAP_AOI_ENTER":         405,
		"MSG_INTERNAL_MAP_AOI_LEAVE":         406,
		"MSG_INTERNAL_MAP_AOI_UPDATE":        407,
		"MSG_INTERNAL_COMBAT_START":          500,
		"MSG_INTERNAL_COMBAT_ACTION":         501,
		"MSG_INTERNAL_COMBAT_END":            502,
		"MSG_INTERNAL_CROSS_SERVER_REQUEST":  600,
		"MSG_INTERNAL_CROSS_SERVER_RESPONSE": 601,
	}
)

func (x InternalMsgId) Enum() *InternalMsgId {
	p := new(InternalMsgId)
	*p = x
	return p
}

func (x InternalMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[0].Descriptor()
}

func (InternalMsgId) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[0]
}

func (x InternalMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalMsgId.Descriptor instead.
func (InternalMsgId) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

// 服务类型
type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_INVALID ServiceType = 0
	ServiceType_SERVICE_TYPE_GLOBAL  ServiceType = 1
	ServiceType_SERVICE_TYPE_GATEWAY ServiceType = 2
	ServiceType_SERVICE_TYPE_GAME    ServiceType = 3
	ServiceType_SERVICE_TYPE_MAP     ServiceType = 4
	ServiceType_SERVICE_TYPE_ADMIN   ServiceType = 5
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_INVALID",
		1: "SERVICE_TYPE_GLOBAL",
		2: "SERVICE_TYPE_GATEWAY",
		3: "SERVICE_TYPE_GAME",
		4: "SERVICE_TYPE_MAP",
		5: "SERVICE_TYPE_ADMIN",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_INVALID": 0,
		"SERVICE_TYPE_GLOBAL":  1,
		"SERVICE_TYPE_GATEWAY": 2,
		"SERVICE_TYPE_GAME":    3,
		"SERVICE_TYPE_MAP":     4,
		"SERVICE_TYPE_ADMIN":   5,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

// 服务信息
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=interop.ServiceType" json:"service_type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	GroupId       int32                  `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,7,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	MaxOnline     int32                  `protobuf:"varint,8,opt,name=max_online,json=maxOnline,proto3" json:"max_online,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	RegisterTime  int64                  `protobuf:"varint,10,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,11,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceInfo) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

func (x *ServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ServiceInfo) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *ServiceInfo) GetMaxOnline() int32 {
	if x != nil {
		return x.MaxOnline
	}
	return 0
}

func (x *ServiceInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServiceInfo) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

func (x *ServiceInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ServiceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 服务注册请求
type ServiceRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegisterRequest) Reset() {
	*x = ServiceRegisterRequest{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegisterRequest) ProtoMessage() {}

func (x *ServiceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegisterRequest.ProtoReflect.Descriptor instead.
func (*ServiceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRegisterRequest) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

// 服务注册响应
type ServiceRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegisterResponse) Reset() {
	*x = ServiceRegisterResponse{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegisterResponse) ProtoMessage() {}

func (x *ServiceRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegisterResponse.ProtoReflect.Descriptor instead.
func (*ServiceRegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceRegisterResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 服务注销请求
type ServiceDeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=interop.ServiceType" json:"service_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDeregisterRequest) Reset() {
	*x = ServiceDeregisterRequest{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeregisterRequest) ProtoMessage() {}

func (x *ServiceDeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeregisterRequest.ProtoReflect.Descriptor instead.
func (*ServiceDeregisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDeregisterRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceDeregisterRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

// 服务心跳请求
type ServiceHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=interop.ServiceType" json:"service_type,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,3,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Load          float32                `protobuf:"fixed32,5,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeatRequest) Reset() {
	*x = ServiceHeartbeatRequest{}
	mi := &file_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeatRequest) ProtoMessage() {}

func (x *ServiceHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceHeartbeatRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

func (x *ServiceHeartbeatRequest) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetLoad() float32 {
	if x != nil {
		return x.Load
	}
	return 0
}

// 服务发现请求
type ServiceDiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceType   ServiceType            `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=interop.ServiceType" json:"service_type,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoverRequest) Reset() {
	*x = ServiceDiscoverRequest{}
	mi := &file_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoverRequest) ProtoMessage() {}

func (x *ServiceDiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoverRequest.ProtoReflect.Descriptor instead.
func (*ServiceDiscoverRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceDiscoverRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

func (x *ServiceDiscoverRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 服务发现响应
type ServiceDiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Services      []*ServiceInfo         `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoverResponse) Reset() {
	*x = ServiceDiscoverResponse{}
	mi := &file_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoverResponse) ProtoMessage() {}

func (x *ServiceDiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoverResponse.ProtoReflect.Descriptor instead.
func (*ServiceDiscoverResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceDiscoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceDiscoverResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ServiceDiscoverResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

// 网关路由消息（Gateway转发到GameServer/MapServer）
type GatewayRouteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId         int32                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRouteMessage) Reset() {
	*x = GatewayRouteMessage{}
	mi := &file_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRouteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRouteMessage) ProtoMessage() {}

func (x *GatewayRouteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRouteMessage.ProtoReflect.Descriptor instead.
func (*GatewayRouteMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayRouteMessage) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GatewayRouteMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GatewayRouteMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GatewayRouteMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GatewayRouteMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 网关广播消息
type GatewayBroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []int64                `protobuf:"varint,1,rep,packed,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	MsgId         int32                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayBroadcastMessage) Reset() {
	*x = GatewayBroadcastMessage{}
	mi := &file_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayBroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayBroadcastMessage) ProtoMessage() {}

func (x *GatewayBroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayBroadcastMessage.ProtoReflect.Descriptor instead.
func (*GatewayBroadcastMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{8}
}

func (x *GatewayBroadcastMessage) GetSessionIds() []int64 {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *GatewayBroadcastMessage) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *GatewayBroadcastMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GatewayBroadcastMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 网关踢人请求
type GatewayKickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKickRequest) Reset() {
	*x = GatewayKickRequest{}
	mi := &file_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKickRequest) ProtoMessage() {}

func (x *GatewayKickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKickRequest.ProtoReflect.Descriptor instead.
func (*GatewayKickRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayKickRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GatewayKickRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GatewayKickRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *GatewayKickRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 玩家路由信息
type PlayerRouteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	GameServerId  int32                  `protobuf:"varint,4,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MapServerId   int32                  `protobuf:"varint,5,opt,name=map_server_id,json=mapServerId,proto3" json:"map_server_id,omitempty"`
	CurrentMapId  int64                  `protobuf:"varint,6,opt,name=current_map_id,json=currentMapId,proto3" json:"current_map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRouteInfo) Reset() {
	*x = PlayerRouteInfo{}
	mi := &file_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRouteInfo) ProtoMessage() {}

func (x *PlayerRouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRouteInfo.ProtoReflect.Descriptor instead.
func (*PlayerRouteInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerRouteInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerRouteInfo) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PlayerRouteInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerRouteInfo) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

func (x *PlayerRouteInfo) GetMapServerId() int32 {
	if x != nil {
		return x.MapServerId
	}
	return 0
}

func (x *PlayerRouteInfo) GetCurrentMapId() int64 {
	if x != nil {
		return x.CurrentMapId
	}
	return 0
}

// 玩家绑定服务器请求
type PlayerBindServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameServerId  int32                  `protobuf:"varint,3,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MapServerId   int32                  `protobuf:"varint,4,opt,name=map_server_id,json=mapServerId,proto3" json:"map_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBindServerRequest) Reset() {
	*x = PlayerBindServerRequest{}
	mi := &file_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBindServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBindServerRequest) ProtoMessage() {}

func (x *PlayerBindServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBindServerRequest.ProtoReflect.Descriptor instead.
func (*PlayerBindServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerBindServerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBindServerRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PlayerBindServerRequest) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

func (x *PlayerBindServerRequest) GetMapServerId() int32 {
	if x != nil {
		return x.MapServerId
	}
	return 0
}

// 玩家绑定服务器响应
type PlayerBindServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	RouteInfo     *PlayerRouteInfo       `protobuf:"bytes,3,opt,name=route_info,json=routeInfo,proto3" json:"route_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBindServerResponse) Reset() {
	*x = PlayerBindServerResponse{}
	mi := &file_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBindServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBindServerResponse) ProtoMessage() {}

func (x *PlayerBindServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBindServerResponse.ProtoReflect.Descriptor instead.
func (*PlayerBindServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerBindServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerBindServerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *PlayerBindServerResponse) GetRouteInfo() *PlayerRouteInfo {
	if x != nil {
		return x.RouteInfo
	}
	return nil
}

// 玩家解绑服务器请求
type PlayerUnbindServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameServerId  int32                  `protobuf:"varint,2,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MapServerId   int32                  `protobuf:"varint,3,opt,name=map_server_id,json=mapServerId,proto3" json:"map_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUnbindServerRequest) Reset() {
	*x = PlayerUnbindServerRequest{}
	mi := &file_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUnbindServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUnbindServerRequest) ProtoMessage() {}

func (x *PlayerUnbindServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUnbindServerRequest.ProtoReflect.Descriptor instead.
func (*PlayerUnbindServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerUnbindServerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerUnbindServerRequest) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

func (x *PlayerUnbindServerRequest) GetMapServerId() int32 {
	if x != nil {
		return x.MapServerId
	}
	return 0
}

// 玩家转移请求
type PlayerTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FromServerId  int32                  `protobuf:"varint,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId    int32                  `protobuf:"varint,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	PlayerData    []byte                 `protobuf:"bytes,4,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTransferRequest) Reset() {
	*x = PlayerTransferRequest{}
	mi := &file_internal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTransferRequest) ProtoMessage() {}

func (x *PlayerTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTransferRequest.ProtoReflect.Descriptor instead.
func (*PlayerTransferRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerTransferRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerTransferRequest) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *PlayerTransferRequest) GetToServerId() int32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *PlayerTransferRequest) GetPlayerData() []byte {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

// 玩家转移响应
type PlayerTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTransferResponse) Reset() {
	*x = PlayerTransferResponse{}
	mi := &file_internal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTransferResponse) ProtoMessage() {}

func (x *PlayerTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTransferResponse.ProtoReflect.Descriptor instead.
func (*PlayerTransferResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerTransferResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 地图进入请求（GameServer -> MapServer）
type MapEnterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MapId         int64                  `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,6,opt,name=z,proto3" json:"z,omitempty"`
	GameServerId  int32                  `protobuf:"varint,7,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	PlayerData    []byte                 `protobuf:"bytes,8,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEnterRequest) Reset() {
	*x = MapEnterRequest{}
	mi := &file_internal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEnterRequest) ProtoMessage() {}

func (x *MapEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEnterRequest.ProtoReflect.Descriptor instead.
func (*MapEnterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{16}
}

func (x *MapEnterRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapEnterRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *MapEnterRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapEnterRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapEnterRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapEnterRequest) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *MapEnterRequest) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

func (x *MapEnterRequest) GetPlayerData() []byte {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

// 地图进入响应（MapServer -> GameServer）
type MapEnterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	ObjectId      int64                  `protobuf:"varint,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MapId         int64                  `protobuf:"varint,4,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             float32                `protobuf:"fixed32,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,7,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEnterResponse) Reset() {
	*x = MapEnterResponse{}
	mi := &file_internal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEnterResponse) ProtoMessage() {}

func (x *MapEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEnterResponse.ProtoReflect.Descriptor instead.
func (*MapEnterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{17}
}

func (x *MapEnterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MapEnterResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MapEnterResponse) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *MapEnterResponse) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapEnterResponse) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapEnterResponse) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapEnterResponse) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 地图离开请求（GameServer -> MapServer）
type MapLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ObjectId      int64                  `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MapId         int64                  `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Reason        int32                  `protobuf:"varint,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapLeaveRequest) Reset() {
	*x = MapLeaveRequest{}
	mi := &file_internal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapLeaveRequest) ProtoMessage() {}

func (x *MapLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapLeaveRequest.ProtoReflect.Descriptor instead.
func (*MapLeaveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{18}
}

func (x *MapLeaveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapLeaveRequest) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *MapLeaveRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapLeaveRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// 地图离开响应（MapServer -> GameServer）
type MapLeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapLeaveResponse) Reset() {
	*x = MapLeaveResponse{}
	mi := &file_internal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapLeaveResponse) ProtoMessage() {}

func (x *MapLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapLeaveResponse.ProtoReflect.Descriptor instead.
func (*MapLeaveResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{19}
}

func (x *MapLeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MapLeaveResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MapLeaveResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 地图移动同步（MapServer -> Gateway -> Client）
type MapMoveSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int64                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,5,opt,name=z,proto3" json:"z,omitempty"`
	Orientation   float32                `protobuf:"fixed32,6,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Speed         float32                `protobuf:"fixed32,7,opt,name=speed,proto3" json:"speed,omitempty"`
	MoveType      int32                  `protobuf:"varint,8,opt,name=move_type,json=moveType,proto3" json:"move_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapMoveSync) Reset() {
	*x = MapMoveSync{}
	mi := &file_internal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMoveSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMoveSync) ProtoMessage() {}

func (x *MapMoveSync) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMoveSync.ProtoReflect.Descriptor instead.
func (*MapMoveSync) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{20}
}

func (x *MapMoveSync) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *MapMoveSync) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapMoveSync) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapMoveSync) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapMoveSync) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *MapMoveSync) GetOrientation() float32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

func (x *MapMoveSync) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *MapMoveSync) GetMoveType() int32 {
	if x != nil {
		return x.MoveType
	}
	return 0
}

func (x *MapMoveSync) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// AOI进入通知（MapServer -> GameServer）
type AoiEnterNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Objects       []*AoiObjectInfo       `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AoiEnterNotify) Reset() {
	*x = AoiEnterNotify{}
	mi := &file_internal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AoiEnterNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AoiEnterNotify) ProtoMessage() {}

func (x *AoiEnterNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AoiEnterNotify.ProtoReflect.Descriptor instead.
func (*AoiEnterNotify) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{21}
}

func (x *AoiEnterNotify) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AoiEnterNotify) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *AoiEnterNotify) GetObjects() []*AoiObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

// AOI离开通知（MapServer -> GameServer）
type AoiLeaveNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ObjectIds     []int64                `protobuf:"varint,3,rep,packed,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AoiLeaveNotify) Reset() {
	*x = AoiLeaveNotify{}
	mi := &file_internal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AoiLeaveNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AoiLeaveNotify) ProtoMessage() {}

func (x *AoiLeaveNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AoiLeaveNotify.ProtoReflect.Descriptor instead.
func (*AoiLeaveNotify) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{22}
}

func (x *AoiLeaveNotify) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AoiLeaveNotify) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *AoiLeaveNotify) GetObjectIds() []int64 {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

// AOI更新通知（MapServer -> GameServer）
type AoiUpdateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Objects       []*AoiObjectInfo       `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AoiUpdateNotify) Reset() {
	*x = AoiUpdateNotify{}
	mi := &file_internal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AoiUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AoiUpdateNotify) ProtoMessage() {}

func (x *AoiUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AoiUpdateNotify.ProtoReflect.Descriptor instead.
func (*AoiUpdateNotify) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{23}
}

func (x *AoiUpdateNotify) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AoiUpdateNotify) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *AoiUpdateNotify) GetObjects() []*AoiObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

// AOI对象信息
type AoiObjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int64                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectType    int32                  `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	X             float32                `protobuf:"fixed32,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,7,opt,name=z,proto3" json:"z,omitempty"`
	Orientation   float32                `protobuf:"fixed32,8,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Attributes    map[int32]int64        `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AoiObjectInfo) Reset() {
	*x = AoiObjectInfo{}
	mi := &file_internal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AoiObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AoiObjectInfo) ProtoMessage() {}

func (x *AoiObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AoiObjectInfo.ProtoReflect.Descriptor instead.
func (*AoiObjectInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{24}
}

func (x *AoiObjectInfo) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *AoiObjectInfo) GetObjectType() int32 {
	if x != nil {
		return x.ObjectType
	}
	return 0
}

func (x *AoiObjectInfo) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *AoiObjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AoiObjectInfo) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AoiObjectInfo) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AoiObjectInfo) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *AoiObjectInfo) GetOrientation() float32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

func (x *AoiObjectInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AoiObjectInfo) GetAttributes() map[int32]int64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// 战斗开始通知
type CombatStartNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      int64                  `protobuf:"varint,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Attackers     []*CombatUnitInfo      `protobuf:"bytes,3,rep,name=attackers,proto3" json:"attackers,omitempty"`
	Defenders     []*CombatUnitInfo      `protobuf:"bytes,4,rep,name=defenders,proto3" json:"defenders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatStartNotify) Reset() {
	*x = CombatStartNotify{}
	mi := &file_internal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatStartNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatStartNotify) ProtoMessage() {}

func (x *CombatStartNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatStartNotify.ProtoReflect.Descriptor instead.
func (*CombatStartNotify) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{25}
}

func (x *CombatStartNotify) GetCombatId() int64 {
	if x != nil {
		return x.CombatId
	}
	return 0
}

func (x *CombatStartNotify) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CombatStartNotify) GetAttackers() []*CombatUnitInfo {
	if x != nil {
		return x.Attackers
	}
	return nil
}

func (x *CombatStartNotify) GetDefenders() []*CombatUnitInfo {
	if x != nil {
		return x.Defenders
	}
	return nil
}

// 战斗单位信息
type CombatUnitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        int64                  `protobuf:"varint,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	UnitType      int32                  `protobuf:"varint,2,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Hp            int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Mp            int32                  `protobuf:"varint,6,opt,name=mp,proto3" json:"mp,omitempty"`
	MaxMp         int32                  `protobuf:"varint,7,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatUnitInfo) Reset() {
	*x = CombatUnitInfo{}
	mi := &file_internal_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatUnitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatUnitInfo) ProtoMessage() {}

func (x *CombatUnitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatUnitInfo.ProtoReflect.Descriptor instead.
func (*CombatUnitInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{26}
}

func (x *CombatUnitInfo) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *CombatUnitInfo) GetUnitType() int32 {
	if x != nil {
		return x.UnitType
	}
	return 0
}

func (x *CombatUnitInfo) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *CombatUnitInfo) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CombatUnitInfo) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *CombatUnitInfo) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *CombatUnitInfo) GetMaxMp() int32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

// 战斗行动通知
type CombatActionNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      int64                  `protobuf:"varint,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	ActorId       int64                  `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActionType    int32                  `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	SkillId       int32                  `protobuf:"varint,4,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Effects       []*CombatEffect        `protobuf:"bytes,5,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatActionNotify) Reset() {
	*x = CombatActionNotify{}
	mi := &file_internal_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatActionNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatActionNotify) ProtoMessage() {}

func (x *CombatActionNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatActionNotify.ProtoReflect.Descriptor instead.
func (*CombatActionNotify) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{27}
}

func (x *CombatActionNotify) GetCombatId() int64 {
	if x != nil {
		return x.CombatId
	}
	return 0
}

func (x *CombatActionNotify) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *CombatActionNotify) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *CombatActionNotify) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *CombatActionNotify) GetEffects() []*CombatEffect {
	if x != nil {
		return x.Effects
	}
	return nil
}

// 战斗效果
type CombatEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	EffectType    int32                  `protobuf:"varint,2,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,4,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	CurrentMp     int32                  `protobuf:"varint,5,opt,name=current_mp,json=currentMp,proto3" json:"current_mp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatEffect) Reset() {
	*x = CombatEffect{}
	mi := &file_internal_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatEffect) ProtoMessage() {}

func (x *CombatEffect) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatEffect.ProtoReflect.Descriptor instead.
func (*CombatEffect) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{28}
}

func (x *CombatEffect) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CombatEffect) GetEffectType() int32 {
	if x != nil {
		return x.EffectType
	}
	return 0
}

func (x *CombatEffect) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CombatEffect) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *CombatEffect) GetCurrentMp() int32 {
	if x != nil {
		return x.CurrentMp
	}
	return 0
}

// 战斗结束通知
type CombatEndNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      int64                  `protobuf:"varint,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	Result        int32                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Rewards       []*CombatReward        `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatEndNotify) Reset() {
	*x = CombatEndNotify{}
	mi := &file_internal_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatEndNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatEndNotify) ProtoMessage() {}

func (x *CombatEndNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatEndNotify.ProtoReflect.Descriptor instead.
func (*CombatEndNotify) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{29}
}

func (x *CombatEndNotify) GetCombatId() int64 {
	if x != nil {
		return x.CombatId
	}
	return 0
}

func (x *CombatEndNotify) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CombatEndNotify) GetRewards() []*CombatReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// 战斗奖励
type CombatReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        int64                  `protobuf:"varint,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Exp           int64                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold          int64                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	Items         []*ItemInfo            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatReward) Reset() {
	*x = CombatReward{}
	mi := &file_internal_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatReward) ProtoMessage() {}

func (x *CombatReward) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatReward.ProtoReflect.Descriptor instead.
func (*CombatReward) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{30}
}

func (x *CombatReward) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *CombatReward) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *CombatReward) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *CombatReward) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// 物品信息
type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ConfigId      int32                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_internal_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{31}
}

func (x *ItemInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemInfo) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ItemInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 跨服请求
type CrossServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromServerId  int32                  `protobuf:"varint,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId    int32                  `protobuf:"varint,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	MsgId         int32                  `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossServerRequest) Reset() {
	*x = CrossServerRequest{}
	mi := &file_internal_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossServerRequest) ProtoMessage() {}

func (x *CrossServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossServerRequest.ProtoReflect.Descriptor instead.
func (*CrossServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{32}
}

func (x *CrossServerRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CrossServerRequest) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *CrossServerRequest) GetToServerId() int32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *CrossServerRequest) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *CrossServerRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CrossServerRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 跨服响应
type CrossServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromServerId  int32                  `protobuf:"varint,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId    int32                  `protobuf:"varint,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossServerResponse) Reset() {
	*x = CrossServerResponse{}
	mi := &file_internal_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossServerResponse) ProtoMessage() {}

func (x *CrossServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossServerResponse.ProtoReflect.Descriptor instead.
func (*CrossServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{33}
}

func (x *CrossServerResponse) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CrossServerResponse) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *CrossServerResponse) GetToServerId() int32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *CrossServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrossServerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CrossServerResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 内部消息包装
type InternalMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          int32                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceServerId int32                  `protobuf:"varint,4,opt,name=source_server_id,json=sourceServerId,proto3" json:"source_server_id,omitempty"`
	TargetServerId int32                  `protobuf:"varint,5,opt,name=target_server_id,json=targetServerId,proto3" json:"target_server_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InternalMessage) Reset() {
	*x = InternalMessage{}
	mi := &file_internal_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalMessage) ProtoMessage() {}

func (x *InternalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalMessage.ProtoReflect.Descriptor instead.
func (*InternalMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{34}
}

func (x *InternalMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *InternalMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InternalMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InternalMessage) GetSourceServerId() int32 {
	if x != nil {
		return x.SourceServerId
	}
	return 0
}

func (x *InternalMessage) GetTargetServerId() int32 {
	if x != nil {
		return x.TargetServerId
	}
	return 0
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\ainterop\"\xf2\x03\n" +
	"\vServiceInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.interop.ServiceTypeR\vserviceType\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\x05R\agroupId\x12!\n" +
	"\fonline_count\x18\a \x01(\x05R\vonlineCount\x12\x1d\n" +
	"\n" +
	"max_online\x18\b \x01(\x05R\tmaxOnline\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12#\n" +
	"\rregister_time\x18\n" +
	" \x01(\x03R\fregisterTime\x12%\n" +
	"\x0elast_heartbeat\x18\v \x01(\x03R\rlastHeartbeat\x12>\n" +
	"\bmetadata\x18\f \x03(\v2\".interop.ServiceInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x16ServiceRegisterRequest\x12.\n" +
	"\aservice\x18\x01 \x01(\v2\x14.interop.ServiceInfoR\aservice\"P\n" +
	"\x17ServiceRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"p\n" +
	"\x18ServiceDeregisterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.interop.ServiceTypeR\vserviceType\"\xbe\x01\n" +
	"\x17ServiceHeartbeatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.interop.ServiceTypeR\vserviceType\x12!\n" +
	"\fonline_count\x18\x03 \x01(\x05R\vonlineCount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04load\x18\x05 \x01(\x02R\x04load\"l\n" +
	"\x16ServiceDiscoverRequest\x127\n" +
	"\fservice_type\x18\x01 \x01(\x0e2\x14.interop.ServiceTypeR\vserviceType\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\"\x82\x01\n" +
	"\x17ServiceDiscoverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x120\n" +
	"\bservices\x18\x03 \x03(\v2\x14.interop.ServiceInfoR\bservices\"\x9a\x01\n" +
	"\x13GatewayRouteMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x84\x01\n" +
	"\x17GatewayBroadcastMessage\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\x03R\n" +
	"sessionIds\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x03R\tplayerIds\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x82\x01\n" +
	"\x12GatewayKickRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xdc\x01\n" +
	"\x0fPlayerRouteInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12$\n" +
	"\x0egame_server_id\x18\x04 \x01(\x05R\fgameServerId\x12\"\n" +
	"\rmap_server_id\x18\x05 \x01(\x05R\vmapServerId\x12$\n" +
	"\x0ecurrent_map_id\x18\x06 \x01(\x03R\fcurrentMapId\"\x9f\x01\n" +
	"\x17PlayerBindServerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12$\n" +
	"\x0egame_server_id\x18\x03 \x01(\x05R\fgameServerId\x12\"\n" +
	"\rmap_server_id\x18\x04 \x01(\x05R\vmapServerId\"\x8a\x01\n" +
	"\x18PlayerBindServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x127\n" +
	"\n" +
	"route_info\x18\x03 \x01(\v2\x18.interop.PlayerRouteInfoR\trouteInfo\"\x82\x01\n" +
	"\x19PlayerUnbindServerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12$\n" +
	"\x0egame_server_id\x18\x02 \x01(\x05R\fgameServerId\x12\"\n" +
	"\rmap_server_id\x18\x03 \x01(\x05R\vmapServerId\"\x9d\x01\n" +
	"\x15PlayerTransferRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\x05R\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\x05R\n" +
	"toServerId\x12\x1f\n" +
	"\vplayer_data\x18\x04 \x01(\fR\n" +
	"playerData\"O\n" +
	"\x16PlayerTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\xd5\x01\n" +
	"\x0fMapEnterRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\x03R\x05mapId\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x01(\x02R\x01z\x12$\n" +
	"\x0egame_server_id\x18\a \x01(\x05R\fgameServerId\x12\x1f\n" +
	"\vplayer_data\x18\b \x01(\fR\n" +
	"playerData\"\xa7\x01\n" +
	"\x10MapEnterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\x03R\bobjectId\x12\x15\n" +
	"\x06map_id\x18\x04 \x01(\x03R\x05mapId\x12\f\n" +
	"\x01x\x18\x05 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\a \x01(\x02R\x01z\"z\n" +
	"\x0fMapLeaveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\x03R\bobjectId\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\x03R\x05mapId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\x05R\x06reason\"f\n" +
	"\x10MapLeaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\"\xde\x01\n" +
	"\vMapMoveSync\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x03R\bobjectId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x05 \x01(\x02R\x01z\x12 \n" +
	"\vorientation\x18\x06 \x01(\x02R\vorientation\x12\x14\n" +
	"\x05speed\x18\a \x01(\x02R\x05speed\x12\x1b\n" +
	"\tmove_type\x18\b \x01(\x05R\bmoveType\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"v\n" +
	"\x0eAoiEnterNotify\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x120\n" +
	"\aobjects\x18\x03 \x03(\v2\x16.interop.AoiObjectInfoR\aobjects\"c\n" +
	"\x0eAoiLeaveNotify\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x03 \x03(\x03R\tobjectIds\"w\n" +
	"\x0fAoiUpdateNotify\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x120\n" +
	"\aobjects\x18\x03 \x03(\v2\x16.interop.AoiObjectInfoR\aobjects\"\xe9\x02\n" +
	"\rAoiObjectInfo\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x03R\bobjectId\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\x05R\n" +
	"objectType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x05 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\a \x01(\x02R\x01z\x12 \n" +
	"\vorientation\x18\b \x01(\x02R\vorientation\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12F\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2&.interop.AoiObjectInfo.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xb5\x01\n" +
	"\x11CombatStartNotify\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\x03R\bcombatId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x125\n" +
	"\tattackers\x18\x03 \x03(\v2\x17.interop.CombatUnitInfoR\tattackers\x125\n" +
	"\tdefenders\x18\x04 \x03(\v2\x17.interop.CombatUnitInfoR\tdefenders\"\xb1\x01\n" +
	"\x0eCombatUnitInfo\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\x03R\x06unitId\x12\x1b\n" +
	"\tunit_type\x18\x02 \x01(\x05R\bunitType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x05R\x05maxHp\x12\x0e\n" +
	"\x02mp\x18\x06 \x01(\x05R\x02mp\x12\x15\n" +
	"\x06max_mp\x18\a \x01(\x05R\x05maxMp\"\xb9\x01\n" +
	"\x12CombatActionNotify\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\x03R\bcombatId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\x03R\aactorId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\x05R\n" +
	"actionType\x12\x19\n" +
	"\bskill_id\x18\x04 \x01(\x05R\askillId\x12/\n" +
	"\aeffects\x18\x05 \x03(\v2\x15.interop.CombatEffectR\aeffects\"\xa0\x01\n" +
	"\fCombatEffect\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x1f\n" +
	"\veffect_type\x18\x02 \x01(\x05R\n" +
	"effectType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x04 \x01(\x05R\tcurrentHp\x12\x1d\n" +
	"\n" +
	"current_mp\x18\x05 \x01(\x05R\tcurrentMp\"w\n" +
	"\x0fCombatEndNotify\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\x03R\bcombatId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x05R\x06result\x12/\n" +
	"\arewards\x18\x03 \x03(\v2\x15.interop.CombatRewardR\arewards\"v\n" +
	"\fCombatReward\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\x03R\x06unitId\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x03R\x03exp\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x03R\x04gold\x12'\n" +
	"\x05items\x18\x04 \x03(\v2\x11.interop.ItemInfoR\x05items\"V\n" +
	"\bItemInfo\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\x05R\bconfigId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xc4\x01\n" +
	"\x12CrossServerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\x05R\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\x05R\n" +
	"toServerId\x12\x15\n" +
	"\x06msg_id\x18\x04 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xc7\x01\n" +
	"\x13CrossServerResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\x05R\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\x05R\n" +
	"toServerId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\xae\x01\n" +
	"\x0fInternalMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10source_server_id\x18\x04 \x01(\x05R\x0esourceServerId\x12(\n" +
	"\x10target_server_id\x18\x05 \x01(\x05R\x0etargetServerId*\xfa\x06\n" +
	"\rInternalMsgId\x12\x18\n" +
	"\x14MSG_INTERNAL_INVALID\x10\x00\x12!\n" +
	"\x1dMSG_INTERNAL_SERVICE_REGISTER\x10d\x12#\n" +
	"\x1fMSG_INTERNAL_SERVICE_DEREGISTER\x10e\x12\"\n" +
	"\x1eMSG_INTERNAL_SERVICE_HEARTBEAT\x10f\x12!\n" +
	"\x1dMSG_INTERNAL_SERVICE_DISCOVER\x10g\x12\x1f\n" +
	"\x1aMSG_INTERNAL_GATEWAY_ROUTE\x10\xc8\x01\x12#\n" +
	"\x1eMSG_INTERNAL_GATEWAY_BROADCAST\x10\xc9\x01\x12\x1e\n" +
	"\x19MSG_INTERNAL_GATEWAY_KICK\x10\xca\x01\x12\x1e\n" +
	"\x19MSG_INTERNAL_PLAYER_ROUTE\x10\xac\x02\x12$\n" +
	"\x1fMSG_INTERNAL_PLAYER_BIND_SERVER\x10\xad\x02\x12&\n" +
	"!MSG_INTERNAL_PLAYER_UNBIND_SERVER\x10\xae\x02\x12!\n" +
	"\x1cMSG_INTERNAL_PLAYER_TRANSFER\x10\xaf\x02\x12#\n" +
	"\x1eMSG_INTERNAL_MAP_ENTER_REQUEST\x10\x90\x03\x12$\n" +
	"\x1fMSG_INTERNAL_MAP_ENTER_RESPONSE\x10\x91\x03\x12#\n" +
	"\x1eMSG_INTERNAL_MAP_LEAVE_REQUEST\x10\x92\x03\x12$\n" +
	"\x1fMSG_INTERNAL_MAP_LEAVE_RESPONSE\x10\x93\x03\x12\x1f\n" +
	"\x1aMSG_INTERNAL_MAP_MOVE_SYNC\x10\x94\x03\x12\x1f\n" +
	"\x1aMSG_INTERNAL_MAP_AOI_ENTER\x10\x95\x03\x12\x1f\n" +
	"\x1aMSG_INTERNAL_MAP_AOI_LEAVE\x10\x96\x03\x12 \n" +
	"\x1bMSG_INTERNAL_MAP_AOI_UPDATE\x10\x97\x03\x12\x1e\n" +
	"\x19MSG_INTERNAL_COMBAT_START\x10\xf4\x03\x12\x1f\n" +
	"\x1aMSG_INTERNAL_COMBAT_ACTION\x10\xf5\x03\x12\x1c\n" +
	"\x17MSG_INTERNAL_COMBAT_END\x10\xf6\x03\x12&\n" +
	"!MSG_INTERNAL_CROSS_SERVER_REQUEST\x10\xd8\x04\x12'\n" +
	"\"MSG_INTERNAL_CROSS_SERVER_RESPONSE\x10\xd9\x04*\x9f\x01\n" +
	"\vServiceType\x12\x18\n" +
	"\x14SERVICE_TYPE_INVALID\x10\x00\x12\x17\n" +
	"\x13SERVICE_TYPE_GLOBAL\x10\x01\x12\x18\n" +
	"\x14SERVICE_TYPE_GATEWAY\x10\x02\x12\x15\n" +
	"\x11SERVICE_TYPE_GAME\x10\x03\x12\x14\n" +
	"\x10SERVICE_TYPE_MAP\x10\x04\x12\x16\n" +
	"\x12SERVICE_TYPE_ADMIN\x10\x05B\x13Z\x11./interop;interopb\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_internal_proto_goTypes = []any{
	(InternalMsgId)(0),                // 0: interop.InternalMsgId
	(ServiceType)(0),                  // 1: interop.ServiceType
	(*ServiceInfo)(nil),               // 2: interop.ServiceInfo
	(*ServiceRegisterRequest)(nil),    // 3: interop.ServiceRegisterRequest
	(*ServiceRegisterResponse)(nil),   // 4: interop.ServiceRegisterResponse
	(*ServiceDeregisterRequest)(nil),  // 5: interop.ServiceDeregisterRequest
	(*ServiceHeartbeatRequest)(nil),   // 6: interop.ServiceHeartbeatRequest
	(*ServiceDiscoverRequest)(nil),    // 7: interop.ServiceDiscoverRequest
	(*ServiceDiscoverResponse)(nil),   // 8: interop.ServiceDiscoverResponse
	(*GatewayRouteMessage)(nil),       // 9: interop.GatewayRouteMessage
	(*GatewayBroadcastMessage)(nil),   // 10: interop.GatewayBroadcastMessage
	(*GatewayKickRequest)(nil),        // 11: interop.GatewayKickRequest
	(*PlayerRouteInfo)(nil),           // 12: interop.PlayerRouteInfo
	(*PlayerBindServerRequest)(nil),   // 13: interop.PlayerBindServerRequest
	(*PlayerBindServerResponse)(nil),  // 14: interop.PlayerBindServerResponse
	(*PlayerUnbindServerRequest)(nil), // 15: interop.PlayerUnbindServerRequest
	(*PlayerTransferRequest)(nil),     // 16: interop.PlayerTransferRequest
	(*PlayerTransferResponse)(nil),    // 17: interop.PlayerTransferResponse
	(*MapEnterRequest)(nil),           // 18: interop.MapEnterRequest
	(*MapEnterResponse)(nil),          // 19: interop.MapEnterResponse
	(*MapLeaveRequest)(nil),           // 20: interop.MapLeaveRequest
	(*MapLeaveResponse)(nil),          // 21: interop.MapLeaveResponse
	(*MapMoveSync)(nil),               // 22: interop.MapMoveSync
	(*AoiEnterNotify)(nil),            // 23: interop.AoiEnterNotify
	(*AoiLeaveNotify)(nil),            // 24: interop.AoiLeaveNotify
	(*AoiUpdateNotify)(nil),           // 25: interop.AoiUpdateNotify
	(*AoiObjectInfo)(nil),             // 26: interop.AoiObjectInfo
	(*CombatStartNotify)(nil),         // 27: interop.CombatStartNotify
	(*CombatUnitInfo)(nil),            // 28: interop.CombatUnitInfo
	(*CombatActionNotify)(nil),        // 29: interop.CombatActionNotify
	(*CombatEffect)(nil),              // 30: interop.CombatEffect
	(*CombatEndNotify)(nil),           // 31: interop.CombatEndNotify
	(*CombatReward)(nil),              // 32: interop.CombatReward
	(*ItemInfo)(nil),                  // 33: interop.ItemInfo
	(*CrossServerRequest)(nil),        // 34: interop.CrossServerRequest
	(*CrossServerResponse)(nil),       // 35: interop.CrossServerResponse
	(*InternalMessage)(nil),           // 36: interop.InternalMessage
	nil,                               // 37: interop.ServiceInfo.MetadataEntry
	nil,                               // 38: interop.AoiObjectInfo.AttributesEntry
}
var file_internal_proto_depIdxs = []int32{
	1,  // 0: interop.ServiceInfo.service_type:type_name -> interop.ServiceType
	37, // 1: interop.ServiceInfo.metadata:type_name -> interop.ServiceInfo.MetadataEntry
	2,  // 2: interop.ServiceRegisterRequest.service:type_name -> interop.ServiceInfo
	1,  // 3: interop.ServiceDeregisterRequest.service_type:type_name -> interop.ServiceType
	1,  // 4: interop.ServiceHeartbeatRequest.service_type:type_name -> interop.ServiceType
	1,  // 5: interop.ServiceDiscoverRequest.service_type:type_name -> interop.ServiceType
	2,  // 6: interop.ServiceDiscoverResponse.services:type_name -> interop.ServiceInfo
	12, // 7: interop.PlayerBindServerResponse.route_info:type_name -> interop.PlayerRouteInfo
	26, // 8: interop.AoiEnterNotify.objects:type_name -> interop.AoiObjectInfo
	26, // 9: interop.AoiUpdateNotify.objects:type_name -> interop.AoiObjectInfo
	38, // 10: interop.AoiObjectInfo.attributes:type_name -> interop.AoiObjectInfo.AttributesEntry
	28, // 11: interop.CombatStartNotify.attackers:type_name -> interop.CombatUnitInfo
	28, // 12: interop.CombatStartNotify.defenders:type_name -> interop.CombatUnitInfo
	30, // 13: interop.CombatActionNotify.effects:type_name -> interop.CombatEffect
	32, // 14: interop.CombatEndNotify.rewards:type_name -> interop.CombatReward
	33, // 15: interop.CombatReward.items:type_name -> interop.ItemInfo
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		EnumInfos:         file_internal_proto_enumTypes,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
