// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: chat.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMsgId int32

const (
	ChatMsgId_MSG_CHAT_INVALID ChatMsgId = 0
	ChatMsgId_MSG_CHAT_SEND    ChatMsgId = 1500 // 客户端发送聊天
	ChatMsgId_MSG_CHAT_NOTIFY  ChatMsgId = 1501 // 服务器广播聊天（推送给接收者）
)

// Enum value maps for ChatMsgId.
var (
	ChatMsgId_name = map[int32]string{
		0:    "MSG_CHAT_INVALID",
		1500: "MSG_CHAT_SEND",
		1501: "MSG_CHAT_NOTIFY",
	}
	ChatMsgId_value = map[string]int32{
		"MSG_CHAT_INVALID": 0,
		"MSG_CHAT_SEND":    1500,
		"MSG_CHAT_NOTIFY":  1501,
	}
)

func (x ChatMsgId) Enum() *ChatMsgId {
	p := new(ChatMsgId)
	*p = x
	return p
}

func (x ChatMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (ChatMsgId) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x ChatMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMsgId.Descriptor instead.
func (ChatMsgId) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

// 聊天频道
type ChatChannel int32

const (
	ChatChannel_CHAT_WORLD ChatChannel = 0 // 世界（全服在线）
	ChatChannel_CHAT_AREA  ChatChannel = 1 // 附近（同图视野内，预留）
)

// Enum value maps for ChatChannel.
var (
	ChatChannel_name = map[int32]string{
		0: "CHAT_WORLD",
		1: "CHAT_AREA",
	}
	ChatChannel_value = map[string]int32{
		"CHAT_WORLD": 0,
		"CHAT_AREA":  1,
	}
)

func (x ChatChannel) Enum() *ChatChannel {
	p := new(ChatChannel)
	*p = x
	return p
}

func (x ChatChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[1].Descriptor()
}

func (ChatChannel) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[1]
}

func (x ChatChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatChannel.Descriptor instead.
func (ChatChannel) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

// 客户端 → 服务器：发送一条聊天
type ClientChatSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Channel       int32                  `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"` // ChatChannel
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientChatSendRequest) Reset() {
	*x = ClientChatSendRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientChatSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatSendRequest) ProtoMessage() {}

func (x *ClientChatSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatSendRequest.ProtoReflect.Descriptor instead.
func (*ClientChatSendRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ClientChatSendRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientChatSendRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ClientChatSendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 服务器 → 客户端：一条聊天广播
type ClientChatNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       int32                  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	FromPlayerId  int64                  `protobuf:"varint,2,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	FromName      string                 `protobuf:"bytes,3,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientChatNotify) Reset() {
	*x = ClientChatNotify{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientChatNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatNotify) ProtoMessage() {}

func (x *ClientChatNotify) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatNotify.ProtoReflect.Descriptor instead.
func (*ClientChatNotify) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ClientChatNotify) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ClientChatNotify) GetFromPlayerId() int64 {
	if x != nil {
		return x.FromPlayerId
	}
	return 0
}

func (x *ClientChatNotify) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *ClientChatNotify) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\bprotocol\"b\n" +
	"\x15ClientChatSendRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\x05R\achannel\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x83\x01\n" +
	"\x10ClientChatNotify\x12\x18\n" +
	"\achannel\x18\x01 \x01(\x05R\achannel\x12$\n" +
	"\x0efrom_player_id\x18\x02 \x01(\x03R\ffromPlayerId\x12\x1b\n" +
	"\tfrom_name\x18\x03 \x01(\tR\bfromName\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text*K\n" +
	"\tChatMsgId\x12\x14\n" +
	"\x10MSG_CHAT_INVALID\x10\x00\x12\x12\n" +
	"\rMSG_CHAT_SEND\x10\xdc\v\x12\x14\n" +
	"\x0fMSG_CHAT_NOTIFY\x10\xdd\v*,\n" +
	"\vChatChannel\x12\x0e\n" +
	"\n" +
	"CHAT_WORLD\x10\x00\x12\r\n" +
	"\tCHAT_AREA\x10\x01B\rZ\v./;protocolb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_proto_goTypes = []any{
	(ChatMsgId)(0),                // 0: protocol.ChatMsgId
	(ChatChannel)(0),              // 1: protocol.ChatChannel
	(*ClientChatSendRequest)(nil), // 2: protocol.ClientChatSendRequest
	(*ClientChatNotify)(nil),      // 3: protocol.ClientChatNotify
}
var file_chat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
