// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码定义
type ErrorCode int32

const (
	ErrorCode_ERR_SUCCESS           ErrorCode = 0
	ErrorCode_ERR_UNKNOWN           ErrorCode = 1
	ErrorCode_ERR_INVALID_PARAM     ErrorCode = 2
	ErrorCode_ERR_NOT_FOUND         ErrorCode = 3
	ErrorCode_ERR_ALREADY_EXISTS    ErrorCode = 4
	ErrorCode_ERR_PERMISSION_DENIED ErrorCode = 5
	ErrorCode_ERR_SERVER_BUSY       ErrorCode = 6
	ErrorCode_ERR_TIMEOUT           ErrorCode = 7
	ErrorCode_ERR_NOT_IMPLEMENTED   ErrorCode = 8
	// 账号相关错误 100-199
	ErrorCode_ERR_ACCOUNT_NOT_FOUND      ErrorCode = 100
	ErrorCode_ERR_ACCOUNT_ALREADY_EXISTS ErrorCode = 101
	ErrorCode_ERR_ACCOUNT_TOKEN_INVALID  ErrorCode = 104
	ErrorCode_ERR_ACCOUNT_TOKEN_EXPIRED  ErrorCode = 105
	// 玩家相关错误 200-299
	ErrorCode_ERR_PLAYER_NOT_FOUND   ErrorCode = 200
	ErrorCode_ERR_PLAYER_NAME_EXISTS ErrorCode = 201
	ErrorCode_ERR_PLAYER_LEVEL_LIMIT ErrorCode = 202
	ErrorCode_ERR_PLAYER_OFFLINE     ErrorCode = 203
	// 账号密码错误
	ErrorCode_ERR_ACCOUNT_PASSWORD_WRONG ErrorCode = 102
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERR_SUCCESS",
		1:   "ERR_UNKNOWN",
		2:   "ERR_INVALID_PARAM",
		3:   "ERR_NOT_FOUND",
		4:   "ERR_ALREADY_EXISTS",
		5:   "ERR_PERMISSION_DENIED",
		6:   "ERR_SERVER_BUSY",
		7:   "ERR_TIMEOUT",
		8:   "ERR_NOT_IMPLEMENTED",
		100: "ERR_ACCOUNT_NOT_FOUND",
		101: "ERR_ACCOUNT_ALREADY_EXISTS",
		104: "ERR_ACCOUNT_TOKEN_INVALID",
		105: "ERR_ACCOUNT_TOKEN_EXPIRED",
		200: "ERR_PLAYER_NOT_FOUND",
		201: "ERR_PLAYER_NAME_EXISTS",
		202: "ERR_PLAYER_LEVEL_LIMIT",
		203: "ERR_PLAYER_OFFLINE",
		102: "ERR_ACCOUNT_PASSWORD_WRONG",
	}
	ErrorCode_value = map[string]int32{
		"ERR_SUCCESS":                0,
		"ERR_UNKNOWN":                1,
		"ERR_INVALID_PARAM":          2,
		"ERR_NOT_FOUND":              3,
		"ERR_ALREADY_EXISTS":         4,
		"ERR_PERMISSION_DENIED":      5,
		"ERR_SERVER_BUSY":            6,
		"ERR_TIMEOUT":                7,
		"ERR_NOT_IMPLEMENTED":        8,
		"ERR_ACCOUNT_NOT_FOUND":      100,
		"ERR_ACCOUNT_ALREADY_EXISTS": 101,
		"ERR_ACCOUNT_TOKEN_INVALID":  104,
		"ERR_ACCOUNT_TOKEN_EXPIRED":  105,
		"ERR_PLAYER_NOT_FOUND":       200,
		"ERR_PLAYER_NAME_EXISTS":     201,
		"ERR_PLAYER_LEVEL_LIMIT":     202,
		"ERR_PLAYER_OFFLINE":         203,
		"ERR_ACCOUNT_PASSWORD_WRONG": 102,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 通用响应结构
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // ErrorCode
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CommonResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 坐标信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Orientation   float32                `protobuf:"fixed32,4,opt,name=orientation,proto3" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Position) GetOrientation() float32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bprotocol\"E\n" +
	"\x0eCommonResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"V\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12 \n" +
	"\vorientation\x18\x04 \x01(\x02R\vorientation*\xd0\x03\n" +
	"\tErrorCode\x12\x0f\n" +
	"\vERR_SUCCESS\x10\x00\x12\x0f\n" +
	"\vERR_UNKNOWN\x10\x01\x12\x15\n" +
	"\x11ERR_INVALID_PARAM\x10\x02\x12\x11\n" +
	"\rERR_NOT_FOUND\x10\x03\x12\x16\n" +
	"\x12ERR_ALREADY_EXISTS\x10\x04\x12\x19\n" +
	"\x15ERR_PERMISSION_DENIED\x10\x05\x12\x13\n" +
	"\x0fERR_SERVER_BUSY\x10\x06\x12\x0f\n" +
	"\vERR_TIMEOUT\x10\a\x12\x17\n" +
	"\x13ERR_NOT_IMPLEMENTED\x10\b\x12\x19\n" +
	"\x15ERR_ACCOUNT_NOT_FOUND\x10d\x12\x1e\n" +
	"\x1aERR_ACCOUNT_ALREADY_EXISTS\x10e\x12\x1d\n" +
	"\x19ERR_ACCOUNT_TOKEN_INVALID\x10h\x12\x1d\n" +
	"\x19ERR_ACCOUNT_TOKEN_EXPIRED\x10i\x12\x19\n" +
	"\x14ERR_PLAYER_NOT_FOUND\x10\xc8\x01\x12\x1b\n" +
	"\x16ERR_PLAYER_NAME_EXISTS\x10\xc9\x01\x12\x1b\n" +
	"\x16ERR_PLAYER_LEVEL_LIMIT\x10\xca\x01\x12\x17\n" +
	"\x12ERR_PLAYER_OFFLINE\x10\xcb\x01\x12\x1e\n" +
	"\x1aERR_ACCOUNT_PASSWORD_WRONG\x10fB\rZ\v./;protocolb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(ErrorCode)(0),         // 0: protocol.ErrorCode
	(*CommonResponse)(nil), // 1: protocol.CommonResponse
	(*Position)(nil),       // 2: protocol.Position
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
