// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: game.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 系统消息 1-99
type SystemMsgId int32

const (
	SystemMsgId_MSG_SYSTEM_INVALID     SystemMsgId = 0
	SystemMsgId_MSG_SYSTEM_HEARTBEAT   SystemMsgId = 1
	SystemMsgId_MSG_SYSTEM_PING        SystemMsgId = 2
	SystemMsgId_MSG_SYSTEM_PONG        SystemMsgId = 3
	SystemMsgId_MSG_SYSTEM_KICK        SystemMsgId = 4
	SystemMsgId_MSG_SYSTEM_MAINTENANCE SystemMsgId = 5
)

// Enum value maps for SystemMsgId.
var (
	SystemMsgId_name = map[int32]string{
		0: "MSG_SYSTEM_INVALID",
		1: "MSG_SYSTEM_HEARTBEAT",
		2: "MSG_SYSTEM_PING",
		3: "MSG_SYSTEM_PONG",
		4: "MSG_SYSTEM_KICK",
		5: "MSG_SYSTEM_MAINTENANCE",
	}
	SystemMsgId_value = map[string]int32{
		"MSG_SYSTEM_INVALID":     0,
		"MSG_SYSTEM_HEARTBEAT":   1,
		"MSG_SYSTEM_PING":        2,
		"MSG_SYSTEM_PONG":        3,
		"MSG_SYSTEM_KICK":        4,
		"MSG_SYSTEM_MAINTENANCE": 5,
	}
)

func (x SystemMsgId) Enum() *SystemMsgId {
	p := new(SystemMsgId)
	*p = x
	return p
}

func (x SystemMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (SystemMsgId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x SystemMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemMsgId.Descriptor instead.
func (SystemMsgId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

// 玩家消息 200-299
type PlayerMsgId int32

const (
	PlayerMsgId_MSG_PLAYER_INVALID             PlayerMsgId = 0
	PlayerMsgId_MSG_PLAYER_CREATE              PlayerMsgId = 200
	PlayerMsgId_MSG_PLAYER_CREATE_RESPONSE     PlayerMsgId = 201
	PlayerMsgId_MSG_PLAYER_ENTER_GAME          PlayerMsgId = 202
	PlayerMsgId_MSG_PLAYER_ENTER_GAME_RESPONSE PlayerMsgId = 203
	PlayerMsgId_MSG_PLAYER_LEAVE_GAME          PlayerMsgId = 204
)

// Enum value maps for PlayerMsgId.
var (
	PlayerMsgId_name = map[int32]string{
		0:   "MSG_PLAYER_INVALID",
		200: "MSG_PLAYER_CREATE",
		201: "MSG_PLAYER_CREATE_RESPONSE",
		202: "MSG_PLAYER_ENTER_GAME",
		203: "MSG_PLAYER_ENTER_GAME_RESPONSE",
		204: "MSG_PLAYER_LEAVE_GAME",
	}
	PlayerMsgId_value = map[string]int32{
		"MSG_PLAYER_INVALID":             0,
		"MSG_PLAYER_CREATE":              200,
		"MSG_PLAYER_CREATE_RESPONSE":     201,
		"MSG_PLAYER_ENTER_GAME":          202,
		"MSG_PLAYER_ENTER_GAME_RESPONSE": 203,
		"MSG_PLAYER_LEAVE_GAME":          204,
	}
)

func (x PlayerMsgId) Enum() *PlayerMsgId {
	p := new(PlayerMsgId)
	*p = x
	return p
}

func (x PlayerMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (PlayerMsgId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x PlayerMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerMsgId.Descriptor instead.
func (PlayerMsgId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

// 地图消息 1200-1299
type MapMsgId int32

const (
	MapMsgId_MSG_MAP_INVALID         MapMsgId = 0
	MapMsgId_MSG_MAP_ENTER           MapMsgId = 1200
	MapMsgId_MSG_MAP_ENTER_RESPONSE  MapMsgId = 1201
	MapMsgId_MSG_MAP_LEAVE           MapMsgId = 1202
	MapMsgId_MSG_MAP_LEAVE_RESPONSE  MapMsgId = 1203
	MapMsgId_MSG_MAP_MOVE            MapMsgId = 1204
	MapMsgId_MSG_MAP_MOVE_RESPONSE   MapMsgId = 1205
	MapMsgId_MSG_MAP_ATTACK          MapMsgId = 1206
	MapMsgId_MSG_MAP_ATTACK_RESPONSE MapMsgId = 1207
)

// Enum value maps for MapMsgId.
var (
	MapMsgId_name = map[int32]string{
		0:    "MSG_MAP_INVALID",
		1200: "MSG_MAP_ENTER",
		1201: "MSG_MAP_ENTER_RESPONSE",
		1202: "MSG_MAP_LEAVE",
		1203: "MSG_MAP_LEAVE_RESPONSE",
		1204: "MSG_MAP_MOVE",
		1205: "MSG_MAP_MOVE_RESPONSE",
		1206: "MSG_MAP_ATTACK",
		1207: "MSG_MAP_ATTACK_RESPONSE",
	}
	MapMsgId_value = map[string]int32{
		"MSG_MAP_INVALID":         0,
		"MSG_MAP_ENTER":           1200,
		"MSG_MAP_ENTER_RESPONSE":  1201,
		"MSG_MAP_LEAVE":           1202,
		"MSG_MAP_LEAVE_RESPONSE":  1203,
		"MSG_MAP_MOVE":            1204,
		"MSG_MAP_MOVE_RESPONSE":   1205,
		"MSG_MAP_ATTACK":          1206,
		"MSG_MAP_ATTACK_RESPONSE": 1207,
	}
)

func (x MapMsgId) Enum() *MapMsgId {
	p := new(MapMsgId)
	*p = x
	return p
}

func (x MapMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[2].Descriptor()
}

func (MapMsgId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[2]
}

func (x MapMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapMsgId.Descriptor instead.
func (MapMsgId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

// 客户端到服务器的消息头
type ClientMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ClientMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientMessage) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ClientMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 服务器到客户端的消息头
type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Result        int32                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ServerMessage) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ServerMessage) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ServerMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 进入地图请求
type ClientMapEnterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapEnterRequest) Reset() {
	*x = ClientMapEnterRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapEnterRequest) ProtoMessage() {}

func (x *ClientMapEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapEnterRequest.ProtoReflect.Descriptor instead.
func (*ClientMapEnterRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMapEnterRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientMapEnterRequest) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

// 进入地图响应
type ClientMapEnterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	MapId         int32                  `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Pos           *Position              `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapEnterResponse) Reset() {
	*x = ClientMapEnterResponse{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapEnterResponse) ProtoMessage() {}

func (x *ClientMapEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapEnterResponse.ProtoReflect.Descriptor instead.
func (*ClientMapEnterResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *ClientMapEnterResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientMapEnterResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ClientMapEnterResponse) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ClientMapEnterResponse) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 地图移动请求
type ClientMapMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Pos           *Position              `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapMoveRequest) Reset() {
	*x = ClientMapMoveRequest{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapMoveRequest) ProtoMessage() {}

func (x *ClientMapMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapMoveRequest.ProtoReflect.Descriptor instead.
func (*ClientMapMoveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *ClientMapMoveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientMapMoveRequest) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ClientMapMoveRequest) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 地图移动响应
type ClientMapMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Pos           *Position              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapMoveResponse) Reset() {
	*x = ClientMapMoveResponse{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapMoveResponse) ProtoMessage() {}

func (x *ClientMapMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapMoveResponse.ProtoReflect.Descriptor instead.
func (*ClientMapMoveResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *ClientMapMoveResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientMapMoveResponse) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 离开地图请求
type ClientMapLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapLeaveRequest) Reset() {
	*x = ClientMapLeaveRequest{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapLeaveRequest) ProtoMessage() {}

func (x *ClientMapLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapLeaveRequest.ProtoReflect.Descriptor instead.
func (*ClientMapLeaveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *ClientMapLeaveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientMapLeaveRequest) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

// 离开地图响应
type ClientMapLeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapLeaveResponse) Reset() {
	*x = ClientMapLeaveResponse{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapLeaveResponse) ProtoMessage() {}

func (x *ClientMapLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapLeaveResponse.ProtoReflect.Descriptor instead.
func (*ClientMapLeaveResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *ClientMapLeaveResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientMapLeaveResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 地图攻击请求
type ClientMapAttackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapAttackRequest) Reset() {
	*x = ClientMapAttackRequest{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapAttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapAttackRequest) ProtoMessage() {}

func (x *ClientMapAttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapAttackRequest.ProtoReflect.Descriptor instead.
func (*ClientMapAttackRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *ClientMapAttackRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientMapAttackRequest) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ClientMapAttackRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 地图攻击响应
type ClientMapAttackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int64                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	TargetHp      int64                  `protobuf:"varint,4,opt,name=target_hp,json=targetHp,proto3" json:"target_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMapAttackResponse) Reset() {
	*x = ClientMapAttackResponse{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMapAttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMapAttackResponse) ProtoMessage() {}

func (x *ClientMapAttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMapAttackResponse.ProtoReflect.Descriptor instead.
func (*ClientMapAttackResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *ClientMapAttackResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientMapAttackResponse) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ClientMapAttackResponse) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *ClientMapAttackResponse) GetTargetHp() int64 {
	if x != nil {
		return x.TargetHp
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\bprotocol\x1a\fcommon.proto\"\xaa\x01\n" +
	"\rClientMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\x03R\tsessionId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"\x8d\x01\n" +
	"\rServerMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"U\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"K\n" +
	"\x15ClientMapEnterRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\"\x8a\x01\n" +
	"\x16ClientMapEnterResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\x05R\x05mapId\x12$\n" +
	"\x03pos\x18\x04 \x01(\v2\x12.protocol.PositionR\x03pos\"p\n" +
	"\x14ClientMapMoveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12$\n" +
	"\x03pos\x18\x03 \x01(\v2\x12.protocol.PositionR\x03pos\"U\n" +
	"\x15ClientMapMoveResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12$\n" +
	"\x03pos\x18\x02 \x01(\v2\x12.protocol.PositionR\x03pos\"K\n" +
	"\x15ClientMapLeaveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\"M\n" +
	"\x16ClientMapLeaveResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"i\n" +
	"\x16ClientMapAttackRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"\x83\x01\n" +
	"\x17ClientMapAttackResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x03R\x06damage\x12\x1b\n" +
	"\ttarget_hp\x18\x04 \x01(\x03R\btargetHp*\x9a\x01\n" +
	"\vSystemMsgId\x12\x16\n" +
	"\x12MSG_SYSTEM_INVALID\x10\x00\x12\x18\n" +
	"\x14MSG_SYSTEM_HEARTBEAT\x10\x01\x12\x13\n" +
	"\x0fMSG_SYSTEM_PING\x10\x02\x12\x13\n" +
	"\x0fMSG_SYSTEM_PONG\x10\x03\x12\x13\n" +
	"\x0fMSG_SYSTEM_KICK\x10\x04\x12\x1a\n" +
	"\x16MSG_SYSTEM_MAINTENANCE\x10\x05*\xbb\x01\n" +
	"\vPlayerMsgId\x12\x16\n" +
	"\x12MSG_PLAYER_INVALID\x10\x00\x12\x16\n" +
	"\x11MSG_PLAYER_CREATE\x10\xc8\x01\x12\x1f\n" +
	"\x1aMSG_PLAYER_CREATE_RESPONSE\x10\xc9\x01\x12\x1a\n" +
	"\x15MSG_PLAYER_ENTER_GAME\x10\xca\x01\x12#\n" +
	"\x1eMSG_PLAYER_ENTER_GAME_RESPONSE\x10\xcb\x01\x12\x1a\n" +
	"\x15MSG_PLAYER_LEAVE_GAME\x10\xcc\x01*\xe3\x01\n" +
	"\bMapMsgId\x12\x13\n" +
	"\x0fMSG_MAP_INVALID\x10\x00\x12\x12\n" +
	"\rMSG_MAP_ENTER\x10\xb0\t\x12\x1b\n" +
	"\x16MSG_MAP_ENTER_RESPONSE\x10\xb1\t\x12\x12\n" +
	"\rMSG_MAP_LEAVE\x10\xb2\t\x12\x1b\n" +
	"\x16MSG_MAP_LEAVE_RESPONSE\x10\xb3\t\x12\x11\n" +
	"\fMSG_MAP_MOVE\x10\xb4\t\x12\x1a\n" +
	"\x15MSG_MAP_MOVE_RESPONSE\x10\xb5\t\x12\x13\n" +
	"\x0eMSG_MAP_ATTACK\x10\xb6\t\x12\x1c\n" +
	"\x17MSG_MAP_ATTACK_RESPONSE\x10\xb7\tB\rZ\v./;protocolb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_game_proto_goTypes = []any{
	(SystemMsgId)(0),                // 0: protocol.SystemMsgId
	(PlayerMsgId)(0),                // 1: protocol.PlayerMsgId
	(MapMsgId)(0),                   // 2: protocol.MapMsgId
	(*ClientMessage)(nil),           // 3: protocol.ClientMessage
	(*ServerMessage)(nil),           // 4: protocol.ServerMessage
	(*HeartbeatRequest)(nil),        // 5: protocol.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 6: protocol.HeartbeatResponse
	(*ClientMapEnterRequest)(nil),   // 7: protocol.ClientMapEnterRequest
	(*ClientMapEnterResponse)(nil),  // 8: protocol.ClientMapEnterResponse
	(*ClientMapMoveRequest)(nil),    // 9: protocol.ClientMapMoveRequest
	(*ClientMapMoveResponse)(nil),   // 10: protocol.ClientMapMoveResponse
	(*ClientMapLeaveRequest)(nil),   // 11: protocol.ClientMapLeaveRequest
	(*ClientMapLeaveResponse)(nil),  // 12: protocol.ClientMapLeaveResponse
	(*ClientMapAttackRequest)(nil),  // 13: protocol.ClientMapAttackRequest
	(*ClientMapAttackResponse)(nil), // 14: protocol.ClientMapAttackResponse
	(*Position)(nil),                // 15: protocol.Position
}
var file_game_proto_depIdxs = []int32{
	15, // 0: protocol.ClientMapEnterResponse.pos:type_name -> protocol.Position
	15, // 1: protocol.ClientMapMoveRequest.pos:type_name -> protocol.Position
	15, // 2: protocol.ClientMapMoveResponse.pos:type_name -> protocol.Position
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
