// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务间消息ID
type InternalMsgId int32

const (
	InternalMsgId_MSG_INTERNAL_INVALID InternalMsgId = 0
	// 服务注册相关 100-199
	InternalMsgId_MSG_INTERNAL_SERVICE_REGISTER   InternalMsgId = 100
	InternalMsgId_MSG_INTERNAL_SERVICE_DEREGISTER InternalMsgId = 101
	InternalMsgId_MSG_INTERNAL_SERVICE_HEARTBEAT  InternalMsgId = 102
	InternalMsgId_MSG_INTERNAL_SERVICE_DISCOVER   InternalMsgId = 103
	// 网关路由相关 200-299
	InternalMsgId_MSG_INTERNAL_GATEWAY_ROUTE     InternalMsgId = 200
	InternalMsgId_MSG_INTERNAL_GATEWAY_BROADCAST InternalMsgId = 201
	InternalMsgId_MSG_INTERNAL_GATEWAY_KICK      InternalMsgId = 202
	// 玩家路由相关 300-399
	InternalMsgId_MSG_INTERNAL_PLAYER_ROUTE         InternalMsgId = 300
	InternalMsgId_MSG_INTERNAL_PLAYER_BIND_SERVER   InternalMsgId = 301
	InternalMsgId_MSG_INTERNAL_PLAYER_UNBIND_SERVER InternalMsgId = 302
	InternalMsgId_MSG_INTERNAL_PLAYER_TRANSFER      InternalMsgId = 303
	// 地图服务间通信 400-499
	InternalMsgId_MSG_INTERNAL_MAP_ENTER_REQUEST  InternalMsgId = 400
	InternalMsgId_MSG_INTERNAL_MAP_ENTER_RESPONSE InternalMsgId = 401
	InternalMsgId_MSG_INTERNAL_MAP_LEAVE_REQUEST  InternalMsgId = 402
	InternalMsgId_MSG_INTERNAL_MAP_LEAVE_RESPONSE InternalMsgId = 403
	InternalMsgId_MSG_INTERNAL_MAP_MOVE_REQUEST   InternalMsgId = 404
	InternalMsgId_MSG_INTERNAL_MAP_MOVE_SYNC      InternalMsgId = 405
	InternalMsgId_MSG_INTERNAL_MAP_ATTACK_REQUEST InternalMsgId = 406
	InternalMsgId_MSG_INTERNAL_COMBAT_ACTION      InternalMsgId = 407
	// 跨服相关 600-699
	InternalMsgId_MSG_INTERNAL_CROSS_SERVER_REQUEST  InternalMsgId = 600
	InternalMsgId_MSG_INTERNAL_CROSS_SERVER_RESPONSE InternalMsgId = 601
)

// Enum value maps for InternalMsgId.
var (
	InternalMsgId_name = map[int32]string{
		0:   "MSG_INTERNAL_INVALID",
		100: "MSG_INTERNAL_SERVICE_REGISTER",
		101: "MSG_INTERNAL_SERVICE_DEREGISTER",
		102: "MSG_INTERNAL_SERVICE_HEARTBEAT",
		103: "MSG_INTERNAL_SERVICE_DISCOVER",
		200: "MSG_INTERNAL_GATEWAY_ROUTE",
		201: "MSG_INTERNAL_GATEWAY_BROADCAST",
		202: "MSG_INTERNAL_GATEWAY_KICK",
		300: "MSG_INTERNAL_PLAYER_ROUTE",
		301: "MSG_INTERNAL_PLAYER_BIND_SERVER",
		302: "MSG_INTERNAL_PLAYER_UNBIND_SERVER",
		303: "MSG_INTERNAL_PLAYER_TRANSFER",
		400: "MSG_INTERNAL_MAP_ENTER_REQUEST",
		401: "MSG_INTERNAL_MAP_ENTER_RESPONSE",
		402: "MSG_INTERNAL_MAP_LEAVE_REQUEST",
		403: "MSG_INTERNAL_MAP_LEAVE_RESPONSE",
		404: "MSG_INTERNAL_MAP_MOVE_REQUEST",
		405: "MSG_INTERNAL_MAP_MOVE_SYNC",
		406: "MSG_INTERNAL_MAP_ATTACK_REQUEST",
		407: "MSG_INTERNAL_COMBAT_ACTION",
		600: "MSG_INTERNAL_CROSS_SERVER_REQUEST",
		601: "MSG_INTERNAL_CROSS_SERVER_RESPONSE",
	}
	InternalMsgId_value = map[string]int32{
		"MSG_INTERNAL_INVALID":               0,
		"MSG_INTERNAL_SERVICE_REGISTER":      100,
		"MSG_INTERNAL_SERVICE_DEREGISTER":    101,
		"MSG_INTERNAL_SERVICE_HEARTBEAT":     102,
		"MSG_INTERNAL_SERVICE_DISCOVER":      103,
		"MSG_INTERNAL_GATEWAY_ROUTE":         200,
		"MSG_INTERNAL_GATEWAY_BROADCAST":     201,
		"MSG_INTERNAL_GATEWAY_KICK":          202,
		"MSG_INTERNAL_PLAYER_ROUTE":          300,
		"MSG_INTERNAL_PLAYER_BIND_SERVER":    301,
		"MSG_INTERNAL_PLAYER_UNBIND_SERVER":  302,
		"MSG_INTERNAL_PLAYER_TRANSFER":       303,
		"MSG_INTERNAL_MAP_ENTER_REQUEST":     400,
		"MSG_INTERNAL_MAP_ENTER_RESPONSE":    401,
		"MSG_INTERNAL_MAP_LEAVE_REQUEST":     402,
		"MSG_INTERNAL_MAP_LEAVE_RESPONSE":    403,
		"MSG_INTERNAL_MAP_MOVE_REQUEST":      404,
		"MSG_INTERNAL_MAP_MOVE_SYNC":         405,
		"MSG_INTERNAL_MAP_ATTACK_REQUEST":    406,
		"MSG_INTERNAL_COMBAT_ACTION":         407,
		"MSG_INTERNAL_CROSS_SERVER_REQUEST":  600,
		"MSG_INTERNAL_CROSS_SERVER_RESPONSE": 601,
	}
)

func (x InternalMsgId) Enum() *InternalMsgId {
	p := new(InternalMsgId)
	*p = x
	return p
}

func (x InternalMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[0].Descriptor()
}

func (InternalMsgId) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[0]
}

func (x InternalMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalMsgId.Descriptor instead.
func (InternalMsgId) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

// 服务类型
type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_INVALID ServiceType = 0
	ServiceType_SERVICE_TYPE_GLOBAL  ServiceType = 1
	ServiceType_SERVICE_TYPE_GATEWAY ServiceType = 2
	ServiceType_SERVICE_TYPE_GAME    ServiceType = 3
	ServiceType_SERVICE_TYPE_MAP     ServiceType = 4
	ServiceType_SERVICE_TYPE_ADMIN   ServiceType = 5
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_INVALID",
		1: "SERVICE_TYPE_GLOBAL",
		2: "SERVICE_TYPE_GATEWAY",
		3: "SERVICE_TYPE_GAME",
		4: "SERVICE_TYPE_MAP",
		5: "SERVICE_TYPE_ADMIN",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_INVALID": 0,
		"SERVICE_TYPE_GLOBAL":  1,
		"SERVICE_TYPE_GATEWAY": 2,
		"SERVICE_TYPE_GAME":    3,
		"SERVICE_TYPE_MAP":     4,
		"SERVICE_TYPE_ADMIN":   5,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

// 服务信息
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=protocol.ServiceType" json:"service_type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	GroupId       int32                  `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,7,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	MaxOnline     int32                  `protobuf:"varint,8,opt,name=max_online,json=maxOnline,proto3" json:"max_online,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	RegisterTime  int64                  `protobuf:"varint,10,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,11,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceInfo) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

func (x *ServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ServiceInfo) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *ServiceInfo) GetMaxOnline() int32 {
	if x != nil {
		return x.MaxOnline
	}
	return 0
}

func (x *ServiceInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServiceInfo) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

func (x *ServiceInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ServiceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 服务注册请求
type ServiceRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegisterRequest) Reset() {
	*x = ServiceRegisterRequest{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegisterRequest) ProtoMessage() {}

func (x *ServiceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegisterRequest.ProtoReflect.Descriptor instead.
func (*ServiceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRegisterRequest) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

// 服务注册响应
type ServiceRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegisterResponse) Reset() {
	*x = ServiceRegisterResponse{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegisterResponse) ProtoMessage() {}

func (x *ServiceRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegisterResponse.ProtoReflect.Descriptor instead.
func (*ServiceRegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceRegisterResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 服务注销请求
type ServiceDeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=protocol.ServiceType" json:"service_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDeregisterRequest) Reset() {
	*x = ServiceDeregisterRequest{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeregisterRequest) ProtoMessage() {}

func (x *ServiceDeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeregisterRequest.ProtoReflect.Descriptor instead.
func (*ServiceDeregisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDeregisterRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceDeregisterRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

// 服务心跳请求
type ServiceHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=protocol.ServiceType" json:"service_type,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,3,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Load          float32                `protobuf:"fixed32,5,opt,name=load,proto3" json:"load,omitempty"`
	ExternalIp    string                 `protobuf:"bytes,6,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	ExternalPort  int32                  `protobuf:"varint,7,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeatRequest) Reset() {
	*x = ServiceHeartbeatRequest{}
	mi := &file_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeatRequest) ProtoMessage() {}

func (x *ServiceHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceHeartbeatRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

func (x *ServiceHeartbeatRequest) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetLoad() float32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *ServiceHeartbeatRequest) GetExternalPort() int32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

func (x *ServiceHeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 服务发现请求
type ServiceDiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceType   ServiceType            `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=protocol.ServiceType" json:"service_type,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoverRequest) Reset() {
	*x = ServiceDiscoverRequest{}
	mi := &file_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoverRequest) ProtoMessage() {}

func (x *ServiceDiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoverRequest.ProtoReflect.Descriptor instead.
func (*ServiceDiscoverRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceDiscoverRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_INVALID
}

func (x *ServiceDiscoverRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 服务发现响应
type ServiceDiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Services      []*ServiceInfo         `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoverResponse) Reset() {
	*x = ServiceDiscoverResponse{}
	mi := &file_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoverResponse) ProtoMessage() {}

func (x *ServiceDiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoverResponse.ProtoReflect.Descriptor instead.
func (*ServiceDiscoverResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceDiscoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceDiscoverResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ServiceDiscoverResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

// 网关路由消息（Gateway转发到GameServer/MapServer）
type GatewayRouteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId         int32                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRouteMessage) Reset() {
	*x = GatewayRouteMessage{}
	mi := &file_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRouteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRouteMessage) ProtoMessage() {}

func (x *GatewayRouteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRouteMessage.ProtoReflect.Descriptor instead.
func (*GatewayRouteMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayRouteMessage) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GatewayRouteMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GatewayRouteMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GatewayRouteMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GatewayRouteMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 网关广播消息
type GatewayBroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []int64                `protobuf:"varint,1,rep,packed,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	MsgId         int32                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayBroadcastMessage) Reset() {
	*x = GatewayBroadcastMessage{}
	mi := &file_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayBroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayBroadcastMessage) ProtoMessage() {}

func (x *GatewayBroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayBroadcastMessage.ProtoReflect.Descriptor instead.
func (*GatewayBroadcastMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{8}
}

func (x *GatewayBroadcastMessage) GetSessionIds() []int64 {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *GatewayBroadcastMessage) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *GatewayBroadcastMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GatewayBroadcastMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 网关踢人请求
type GatewayKickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKickRequest) Reset() {
	*x = GatewayKickRequest{}
	mi := &file_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKickRequest) ProtoMessage() {}

func (x *GatewayKickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKickRequest.ProtoReflect.Descriptor instead.
func (*GatewayKickRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayKickRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GatewayKickRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GatewayKickRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *GatewayKickRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 玩家路由信息
type PlayerRouteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	GameServerId  int32                  `protobuf:"varint,4,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MapServerId   int32                  `protobuf:"varint,5,opt,name=map_server_id,json=mapServerId,proto3" json:"map_server_id,omitempty"`
	CurrentMapId  int64                  `protobuf:"varint,6,opt,name=current_map_id,json=currentMapId,proto3" json:"current_map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRouteInfo) Reset() {
	*x = PlayerRouteInfo{}
	mi := &file_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRouteInfo) ProtoMessage() {}

func (x *PlayerRouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRouteInfo.ProtoReflect.Descriptor instead.
func (*PlayerRouteInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerRouteInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerRouteInfo) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PlayerRouteInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerRouteInfo) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

func (x *PlayerRouteInfo) GetMapServerId() int32 {
	if x != nil {
		return x.MapServerId
	}
	return 0
}

func (x *PlayerRouteInfo) GetCurrentMapId() int64 {
	if x != nil {
		return x.CurrentMapId
	}
	return 0
}

// 玩家绑定服务器请求
type PlayerBindServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameServerId  int32                  `protobuf:"varint,3,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MapServerId   int32                  `protobuf:"varint,4,opt,name=map_server_id,json=mapServerId,proto3" json:"map_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBindServerRequest) Reset() {
	*x = PlayerBindServerRequest{}
	mi := &file_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBindServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBindServerRequest) ProtoMessage() {}

func (x *PlayerBindServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBindServerRequest.ProtoReflect.Descriptor instead.
func (*PlayerBindServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerBindServerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBindServerRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PlayerBindServerRequest) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

func (x *PlayerBindServerRequest) GetMapServerId() int32 {
	if x != nil {
		return x.MapServerId
	}
	return 0
}

// 玩家绑定服务器响应
type PlayerBindServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	RouteInfo     *PlayerRouteInfo       `protobuf:"bytes,3,opt,name=route_info,json=routeInfo,proto3" json:"route_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBindServerResponse) Reset() {
	*x = PlayerBindServerResponse{}
	mi := &file_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBindServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBindServerResponse) ProtoMessage() {}

func (x *PlayerBindServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBindServerResponse.ProtoReflect.Descriptor instead.
func (*PlayerBindServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerBindServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerBindServerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *PlayerBindServerResponse) GetRouteInfo() *PlayerRouteInfo {
	if x != nil {
		return x.RouteInfo
	}
	return nil
}

// 玩家解绑服务器请求
type PlayerUnbindServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameServerId  int32                  `protobuf:"varint,2,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MapServerId   int32                  `protobuf:"varint,3,opt,name=map_server_id,json=mapServerId,proto3" json:"map_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUnbindServerRequest) Reset() {
	*x = PlayerUnbindServerRequest{}
	mi := &file_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUnbindServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUnbindServerRequest) ProtoMessage() {}

func (x *PlayerUnbindServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUnbindServerRequest.ProtoReflect.Descriptor instead.
func (*PlayerUnbindServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerUnbindServerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerUnbindServerRequest) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

func (x *PlayerUnbindServerRequest) GetMapServerId() int32 {
	if x != nil {
		return x.MapServerId
	}
	return 0
}

// 玩家转移请求
type PlayerTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FromServerId  int32                  `protobuf:"varint,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId    int32                  `protobuf:"varint,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	PlayerData    []byte                 `protobuf:"bytes,4,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTransferRequest) Reset() {
	*x = PlayerTransferRequest{}
	mi := &file_internal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTransferRequest) ProtoMessage() {}

func (x *PlayerTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTransferRequest.ProtoReflect.Descriptor instead.
func (*PlayerTransferRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerTransferRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerTransferRequest) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *PlayerTransferRequest) GetToServerId() int32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *PlayerTransferRequest) GetPlayerData() []byte {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

// 玩家转移响应
type PlayerTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTransferResponse) Reset() {
	*x = PlayerTransferResponse{}
	mi := &file_internal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTransferResponse) ProtoMessage() {}

func (x *PlayerTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTransferResponse.ProtoReflect.Descriptor instead.
func (*PlayerTransferResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerTransferResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 跨服请求
type CrossServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromServerId  int32                  `protobuf:"varint,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId    int32                  `protobuf:"varint,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	MsgId         int32                  `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossServerRequest) Reset() {
	*x = CrossServerRequest{}
	mi := &file_internal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossServerRequest) ProtoMessage() {}

func (x *CrossServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossServerRequest.ProtoReflect.Descriptor instead.
func (*CrossServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{16}
}

func (x *CrossServerRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CrossServerRequest) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *CrossServerRequest) GetToServerId() int32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *CrossServerRequest) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *CrossServerRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CrossServerRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 跨服响应
type CrossServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromServerId  int32                  `protobuf:"varint,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId    int32                  `protobuf:"varint,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossServerResponse) Reset() {
	*x = CrossServerResponse{}
	mi := &file_internal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossServerResponse) ProtoMessage() {}

func (x *CrossServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossServerResponse.ProtoReflect.Descriptor instead.
func (*CrossServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{17}
}

func (x *CrossServerResponse) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CrossServerResponse) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *CrossServerResponse) GetToServerId() int32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *CrossServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrossServerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CrossServerResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 跨服消息包装
type CrossServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       uint64                 `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	FromServerId  uint32                 `protobuf:"varint,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId    uint32                 `protobuf:"varint,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	FromService   uint32                 `protobuf:"varint,4,opt,name=from_service,json=fromService,proto3" json:"from_service,omitempty"`
	ToService     uint32                 `protobuf:"varint,5,opt,name=to_service,json=toService,proto3" json:"to_service,omitempty"`
	Message       *BaseMessage           `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossServerMessage) Reset() {
	*x = CrossServerMessage{}
	mi := &file_internal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossServerMessage) ProtoMessage() {}

func (x *CrossServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossServerMessage.ProtoReflect.Descriptor instead.
func (*CrossServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{18}
}

func (x *CrossServerMessage) GetTraceId() uint64 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *CrossServerMessage) GetFromServerId() uint32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *CrossServerMessage) GetToServerId() uint32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *CrossServerMessage) GetFromService() uint32 {
	if x != nil {
		return x.FromService
	}
	return 0
}

func (x *CrossServerMessage) GetToService() uint32 {
	if x != nil {
		return x.ToService
	}
	return 0
}

func (x *CrossServerMessage) GetMessage() *BaseMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// 基础消息结构
type BaseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MsgId         uint32                 `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ServerId      uint32                 `protobuf:"varint,5,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MapId         uint32                 `protobuf:"varint,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	MapServerId   uint32                 `protobuf:"varint,7,opt,name=map_server_id,json=mapServerId,proto3" json:"map_server_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseMessage) Reset() {
	*x = BaseMessage{}
	mi := &file_internal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMessage) ProtoMessage() {}

func (x *BaseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMessage.ProtoReflect.Descriptor instead.
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{19}
}

func (x *BaseMessage) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *BaseMessage) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *BaseMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BaseMessage) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *BaseMessage) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BaseMessage) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *BaseMessage) GetMapServerId() uint32 {
	if x != nil {
		return x.MapServerId
	}
	return 0
}

func (x *BaseMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 内部消息包装
type InternalMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          int32                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceServerId int32                  `protobuf:"varint,4,opt,name=source_server_id,json=sourceServerId,proto3" json:"source_server_id,omitempty"`
	TargetServerId int32                  `protobuf:"varint,5,opt,name=target_server_id,json=targetServerId,proto3" json:"target_server_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InternalMessage) Reset() {
	*x = InternalMessage{}
	mi := &file_internal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalMessage) ProtoMessage() {}

func (x *InternalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalMessage.ProtoReflect.Descriptor instead.
func (*InternalMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{20}
}

func (x *InternalMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *InternalMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InternalMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InternalMessage) GetSourceServerId() int32 {
	if x != nil {
		return x.SourceServerId
	}
	return 0
}

func (x *InternalMessage) GetTargetServerId() int32 {
	if x != nil {
		return x.TargetServerId
	}
	return 0
}

// 地图进入请求
type MapEnterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,5,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEnterRequest) Reset() {
	*x = MapEnterRequest{}
	mi := &file_internal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEnterRequest) ProtoMessage() {}

func (x *MapEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEnterRequest.ProtoReflect.Descriptor instead.
func (*MapEnterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{21}
}

func (x *MapEnterRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapEnterRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapEnterRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapEnterRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapEnterRequest) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 地图进入响应
type MapEnterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	ObjectId      int64                  `protobuf:"varint,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MapId         int64                  `protobuf:"varint,4,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             float32                `protobuf:"fixed32,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,7,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEnterResponse) Reset() {
	*x = MapEnterResponse{}
	mi := &file_internal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEnterResponse) ProtoMessage() {}

func (x *MapEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEnterResponse.ProtoReflect.Descriptor instead.
func (*MapEnterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{22}
}

func (x *MapEnterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MapEnterResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MapEnterResponse) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *MapEnterResponse) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapEnterResponse) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapEnterResponse) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapEnterResponse) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 地图离开请求
type MapLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapLeaveRequest) Reset() {
	*x = MapLeaveRequest{}
	mi := &file_internal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapLeaveRequest) ProtoMessage() {}

func (x *MapLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapLeaveRequest.ProtoReflect.Descriptor instead.
func (*MapLeaveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{23}
}

func (x *MapLeaveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapLeaveRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapLeaveRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// 地图离开响应
type MapLeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapLeaveResponse) Reset() {
	*x = MapLeaveResponse{}
	mi := &file_internal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapLeaveResponse) ProtoMessage() {}

func (x *MapLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapLeaveResponse.ProtoReflect.Descriptor instead.
func (*MapLeaveResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{24}
}

func (x *MapLeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MapLeaveResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MapLeaveResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 地图移动请求
type MapMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ObjectId      int64                  `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MapId         int64                  `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,6,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapMoveRequest) Reset() {
	*x = MapMoveRequest{}
	mi := &file_internal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMoveRequest) ProtoMessage() {}

func (x *MapMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMoveRequest.ProtoReflect.Descriptor instead.
func (*MapMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{25}
}

func (x *MapMoveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapMoveRequest) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *MapMoveRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapMoveRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapMoveRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapMoveRequest) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 地图移动响应
type MapMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,6,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapMoveResponse) Reset() {
	*x = MapMoveResponse{}
	mi := &file_internal_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMoveResponse) ProtoMessage() {}

func (x *MapMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMoveResponse.ProtoReflect.Descriptor instead.
func (*MapMoveResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{26}
}

func (x *MapMoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MapMoveResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MapMoveResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapMoveResponse) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapMoveResponse) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapMoveResponse) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 地图攻击请求
type MapAttackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ObjectId      int64                  `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MapId         int64                  `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapAttackRequest) Reset() {
	*x = MapAttackRequest{}
	mi := &file_internal_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapAttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapAttackRequest) ProtoMessage() {}

func (x *MapAttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapAttackRequest.ProtoReflect.Descriptor instead.
func (*MapAttackRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{27}
}

func (x *MapAttackRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapAttackRequest) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *MapAttackRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapAttackRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 地图攻击响应
type MapAttackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int64                  `protobuf:"varint,5,opt,name=damage,proto3" json:"damage,omitempty"`
	TargetHp      int64                  `protobuf:"varint,6,opt,name=target_hp,json=targetHp,proto3" json:"target_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapAttackResponse) Reset() {
	*x = MapAttackResponse{}
	mi := &file_internal_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapAttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapAttackResponse) ProtoMessage() {}

func (x *MapAttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapAttackResponse.ProtoReflect.Descriptor instead.
func (*MapAttackResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{28}
}

func (x *MapAttackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MapAttackResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MapAttackResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MapAttackResponse) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MapAttackResponse) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *MapAttackResponse) GetTargetHp() int64 {
	if x != nil {
		return x.TargetHp
	}
	return 0
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\bprotocol\"\xf4\x03\n" +
	"\vServiceInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x128\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x15.protocol.ServiceTypeR\vserviceType\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\x05R\agroupId\x12!\n" +
	"\fonline_count\x18\a \x01(\x05R\vonlineCount\x12\x1d\n" +
	"\n" +
	"max_online\x18\b \x01(\x05R\tmaxOnline\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12#\n" +
	"\rregister_time\x18\n" +
	" \x01(\x03R\fregisterTime\x12%\n" +
	"\x0elast_heartbeat\x18\v \x01(\x03R\rlastHeartbeat\x12?\n" +
	"\bmetadata\x18\f \x03(\v2#.protocol.ServiceInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x16ServiceRegisterRequest\x12/\n" +
	"\aservice\x18\x01 \x01(\v2\x15.protocol.ServiceInfoR\aservice\"P\n" +
	"\x17ServiceRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"q\n" +
	"\x18ServiceDeregisterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x128\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x15.protocol.ServiceTypeR\vserviceType\"\x9f\x02\n" +
	"\x17ServiceHeartbeatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x128\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x15.protocol.ServiceTypeR\vserviceType\x12!\n" +
	"\fonline_count\x18\x03 \x01(\x05R\vonlineCount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04load\x18\x05 \x01(\x02R\x04load\x12\x1f\n" +
	"\vexternal_ip\x18\x06 \x01(\tR\n" +
	"externalIp\x12#\n" +
	"\rexternal_port\x18\a \x01(\x05R\fexternalPort\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\"m\n" +
	"\x16ServiceDiscoverRequest\x128\n" +
	"\fservice_type\x18\x01 \x01(\x0e2\x15.protocol.ServiceTypeR\vserviceType\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\"\x83\x01\n" +
	"\x17ServiceDiscoverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x121\n" +
	"\bservices\x18\x03 \x03(\v2\x15.protocol.ServiceInfoR\bservices\"\x9a\x01\n" +
	"\x13GatewayRouteMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x84\x01\n" +
	"\x17GatewayBroadcastMessage\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\x03R\n" +
	"sessionIds\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x03R\tplayerIds\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x82\x01\n" +
	"\x12GatewayKickRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xdc\x01\n" +
	"\x0fPlayerRouteInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12$\n" +
	"\x0egame_server_id\x18\x04 \x01(\x05R\fgameServerId\x12\"\n" +
	"\rmap_server_id\x18\x05 \x01(\x05R\vmapServerId\x12$\n" +
	"\x0ecurrent_map_id\x18\x06 \x01(\x03R\fcurrentMapId\"\x9f\x01\n" +
	"\x17PlayerBindServerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12$\n" +
	"\x0egame_server_id\x18\x03 \x01(\x05R\fgameServerId\x12\"\n" +
	"\rmap_server_id\x18\x04 \x01(\x05R\vmapServerId\"\x8b\x01\n" +
	"\x18PlayerBindServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x128\n" +
	"\n" +
	"route_info\x18\x03 \x01(\v2\x19.protocol.PlayerRouteInfoR\trouteInfo\"\x82\x01\n" +
	"\x19PlayerUnbindServerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12$\n" +
	"\x0egame_server_id\x18\x02 \x01(\x05R\fgameServerId\x12\"\n" +
	"\rmap_server_id\x18\x03 \x01(\x05R\vmapServerId\"\x9d\x01\n" +
	"\x15PlayerTransferRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\x05R\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\x05R\n" +
	"toServerId\x12\x1f\n" +
	"\vplayer_data\x18\x04 \x01(\fR\n" +
	"playerData\"O\n" +
	"\x16PlayerTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\xc4\x01\n" +
	"\x12CrossServerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\x05R\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\x05R\n" +
	"toServerId\x12\x15\n" +
	"\x06msg_id\x18\x04 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xc7\x01\n" +
	"\x13CrossServerResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\x05R\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\x05R\n" +
	"toServerId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\xea\x01\n" +
	"\x12CrossServerMessage\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\x04R\atraceId\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\rR\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\rR\n" +
	"toServerId\x12!\n" +
	"\ffrom_service\x18\x04 \x01(\rR\vfromService\x12\x1d\n" +
	"\n" +
	"to_service\x18\x05 \x01(\rR\ttoService\x12/\n" +
	"\amessage\x18\x06 \x01(\v2\x15.protocol.BaseMessageR\amessage\"\xea\x01\n" +
	"\vBaseMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x15\n" +
	"\x06msg_id\x18\x04 \x01(\rR\x05msgId\x12\x1b\n" +
	"\tserver_id\x18\x05 \x01(\rR\bserverId\x12\x15\n" +
	"\x06map_id\x18\x06 \x01(\rR\x05mapId\x12\"\n" +
	"\rmap_server_id\x18\a \x01(\rR\vmapServerId\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\"\xae\x01\n" +
	"\x0fInternalMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10source_server_id\x18\x04 \x01(\x05R\x0esourceServerId\x12(\n" +
	"\x10target_server_id\x18\x05 \x01(\x05R\x0etargetServerId\"o\n" +
	"\x0fMapEnterRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x05 \x01(\x02R\x01z\"\xa7\x01\n" +
	"\x10MapEnterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\x03R\bobjectId\x12\x15\n" +
	"\x06map_id\x18\x04 \x01(\x03R\x05mapId\x12\f\n" +
	"\x01x\x18\x05 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\a \x01(\x02R\x01z\"]\n" +
	"\x0fMapLeaveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\"f\n" +
	"\x10MapLeaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\"\x8b\x01\n" +
	"\x0eMapMoveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\x03R\bobjectId\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\x03R\x05mapId\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x01(\x02R\x01z\"\x8f\x01\n" +
	"\x0fMapMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x01(\x02R\x01z\"\x80\x01\n" +
	"\x10MapAttackRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\x03R\bobjectId\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\x03R\x05mapId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\"\xb9\x01\n" +
	"\x11MapAttackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06damage\x18\x05 \x01(\x03R\x06damage\x12\x1b\n" +
	"\ttarget_hp\x18\x06 \x01(\x03R\btargetHp*\xa2\x06\n" +
	"\rInternalMsgId\x12\x18\n" +
	"\x14MSG_INTERNAL_INVALID\x10\x00\x12!\n" +
	"\x1dMSG_INTERNAL_SERVICE_REGISTER\x10d\x12#\n" +
	"\x1fMSG_INTERNAL_SERVICE_DEREGISTER\x10e\x12\"\n" +
	"\x1eMSG_INTERNAL_SERVICE_HEARTBEAT\x10f\x12!\n" +
	"\x1dMSG_INTERNAL_SERVICE_DISCOVER\x10g\x12\x1f\n" +
	"\x1aMSG_INTERNAL_GATEWAY_ROUTE\x10\xc8\x01\x12#\n" +
	"\x1eMSG_INTERNAL_GATEWAY_BROADCAST\x10\xc9\x01\x12\x1e\n" +
	"\x19MSG_INTERNAL_GATEWAY_KICK\x10\xca\x01\x12\x1e\n" +
	"\x19MSG_INTERNAL_PLAYER_ROUTE\x10\xac\x02\x12$\n" +
	"\x1fMSG_INTERNAL_PLAYER_BIND_SERVER\x10\xad\x02\x12&\n" +
	"!MSG_INTERNAL_PLAYER_UNBIND_SERVER\x10\xae\x02\x12!\n" +
	"\x1cMSG_INTERNAL_PLAYER_TRANSFER\x10\xaf\x02\x12#\n" +
	"\x1eMSG_INTERNAL_MAP_ENTER_REQUEST\x10\x90\x03\x12$\n" +
	"\x1fMSG_INTERNAL_MAP_ENTER_RESPONSE\x10\x91\x03\x12#\n" +
	"\x1eMSG_INTERNAL_MAP_LEAVE_REQUEST\x10\x92\x03\x12$\n" +
	"\x1fMSG_INTERNAL_MAP_LEAVE_RESPONSE\x10\x93\x03\x12\"\n" +
	"\x1dMSG_INTERNAL_MAP_MOVE_REQUEST\x10\x94\x03\x12\x1f\n" +
	"\x1aMSG_INTERNAL_MAP_MOVE_SYNC\x10\x95\x03\x12$\n" +
	"\x1fMSG_INTERNAL_MAP_ATTACK_REQUEST\x10\x96\x03\x12\x1f\n" +
	"\x1aMSG_INTERNAL_COMBAT_ACTION\x10\x97\x03\x12&\n" +
	"!MSG_INTERNAL_CROSS_SERVER_REQUEST\x10\xd8\x04\x12'\n" +
	"\"MSG_INTERNAL_CROSS_SERVER_RESPONSE\x10\xd9\x04*\x9f\x01\n" +
	"\vServiceType\x12\x18\n" +
	"\x14SERVICE_TYPE_INVALID\x10\x00\x12\x17\n" +
	"\x13SERVICE_TYPE_GLOBAL\x10\x01\x12\x18\n" +
	"\x14SERVICE_TYPE_GATEWAY\x10\x02\x12\x15\n" +
	"\x11SERVICE_TYPE_GAME\x10\x03\x12\x14\n" +
	"\x10SERVICE_TYPE_MAP\x10\x04\x12\x16\n" +
	"\x12SERVICE_TYPE_ADMIN\x10\x05B\rZ\v./;protocolb\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_internal_proto_goTypes = []any{
	(InternalMsgId)(0),                // 0: protocol.InternalMsgId
	(ServiceType)(0),                  // 1: protocol.ServiceType
	(*ServiceInfo)(nil),               // 2: protocol.ServiceInfo
	(*ServiceRegisterRequest)(nil),    // 3: protocol.ServiceRegisterRequest
	(*ServiceRegisterResponse)(nil),   // 4: protocol.ServiceRegisterResponse
	(*ServiceDeregisterRequest)(nil),  // 5: protocol.ServiceDeregisterRequest
	(*ServiceHeartbeatRequest)(nil),   // 6: protocol.ServiceHeartbeatRequest
	(*ServiceDiscoverRequest)(nil),    // 7: protocol.ServiceDiscoverRequest
	(*ServiceDiscoverResponse)(nil),   // 8: protocol.ServiceDiscoverResponse
	(*GatewayRouteMessage)(nil),       // 9: protocol.GatewayRouteMessage
	(*GatewayBroadcastMessage)(nil),   // 10: protocol.GatewayBroadcastMessage
	(*GatewayKickRequest)(nil),        // 11: protocol.GatewayKickRequest
	(*PlayerRouteInfo)(nil),           // 12: protocol.PlayerRouteInfo
	(*PlayerBindServerRequest)(nil),   // 13: protocol.PlayerBindServerRequest
	(*PlayerBindServerResponse)(nil),  // 14: protocol.PlayerBindServerResponse
	(*PlayerUnbindServerRequest)(nil), // 15: protocol.PlayerUnbindServerRequest
	(*PlayerTransferRequest)(nil),     // 16: protocol.PlayerTransferRequest
	(*PlayerTransferResponse)(nil),    // 17: protocol.PlayerTransferResponse
	(*CrossServerRequest)(nil),        // 18: protocol.CrossServerRequest
	(*CrossServerResponse)(nil),       // 19: protocol.CrossServerResponse
	(*CrossServerMessage)(nil),        // 20: protocol.CrossServerMessage
	(*BaseMessage)(nil),               // 21: protocol.BaseMessage
	(*InternalMessage)(nil),           // 22: protocol.InternalMessage
	(*MapEnterRequest)(nil),           // 23: protocol.MapEnterRequest
	(*MapEnterResponse)(nil),          // 24: protocol.MapEnterResponse
	(*MapLeaveRequest)(nil),           // 25: protocol.MapLeaveRequest
	(*MapLeaveResponse)(nil),          // 26: protocol.MapLeaveResponse
	(*MapMoveRequest)(nil),            // 27: protocol.MapMoveRequest
	(*MapMoveResponse)(nil),           // 28: protocol.MapMoveResponse
	(*MapAttackRequest)(nil),          // 29: protocol.MapAttackRequest
	(*MapAttackResponse)(nil),         // 30: protocol.MapAttackResponse
	nil,                               // 31: protocol.ServiceInfo.MetadataEntry
}
var file_internal_proto_depIdxs = []int32{
	1,  // 0: protocol.ServiceInfo.service_type:type_name -> protocol.ServiceType
	31, // 1: protocol.ServiceInfo.metadata:type_name -> protocol.ServiceInfo.MetadataEntry
	2,  // 2: protocol.ServiceRegisterRequest.service:type_name -> protocol.ServiceInfo
	1,  // 3: protocol.ServiceDeregisterRequest.service_type:type_name -> protocol.ServiceType
	1,  // 4: protocol.ServiceHeartbeatRequest.service_type:type_name -> protocol.ServiceType
	1,  // 5: protocol.ServiceDiscoverRequest.service_type:type_name -> protocol.ServiceType
	2,  // 6: protocol.ServiceDiscoverResponse.services:type_name -> protocol.ServiceInfo
	12, // 7: protocol.PlayerBindServerResponse.route_info:type_name -> protocol.PlayerRouteInfo
	21, // 8: protocol.CrossServerMessage.message:type_name -> protocol.BaseMessage
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		EnumInfos:         file_internal_proto_enumTypes,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
