// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: item.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物品/仓库消息
type ItemMsgId int32

const (
	ItemMsgId_MSG_ITEM_INVALID                ItemMsgId = 0
	ItemMsgId_MSG_ITEM_LIST                   ItemMsgId = 1300 // 查询背包
	ItemMsgId_MSG_ITEM_LIST_RESPONSE          ItemMsgId = 1301
	ItemMsgId_MSG_ITEM_USE                    ItemMsgId = 1302 // 使用物品
	ItemMsgId_MSG_ITEM_USE_RESPONSE           ItemMsgId = 1303
	ItemMsgId_MSG_ITEM_MOVE                   ItemMsgId = 1304 // 背包内移动格子
	ItemMsgId_MSG_ITEM_MOVE_RESPONSE          ItemMsgId = 1305
	ItemMsgId_MSG_ITEM_PICKUP                 ItemMsgId = 1306 // 拾取附近掉落物（就近拾取）
	ItemMsgId_MSG_ITEM_PICKUP_NOTIFY          ItemMsgId = 1307 // 拾取结果通知（服务器→客户端）
	ItemMsgId_MSG_WAREHOUSE_LIST              ItemMsgId = 1310 // 查询仓库
	ItemMsgId_MSG_WAREHOUSE_LIST_RESPONSE     ItemMsgId = 1311
	ItemMsgId_MSG_WAREHOUSE_STORE             ItemMsgId = 1312 // 背包 → 仓库
	ItemMsgId_MSG_WAREHOUSE_STORE_RESPONSE    ItemMsgId = 1313
	ItemMsgId_MSG_WAREHOUSE_RETRIEVE          ItemMsgId = 1314 // 仓库 → 背包
	ItemMsgId_MSG_WAREHOUSE_RETRIEVE_RESPONSE ItemMsgId = 1315
)

// Enum value maps for ItemMsgId.
var (
	ItemMsgId_name = map[int32]string{
		0:    "MSG_ITEM_INVALID",
		1300: "MSG_ITEM_LIST",
		1301: "MSG_ITEM_LIST_RESPONSE",
		1302: "MSG_ITEM_USE",
		1303: "MSG_ITEM_USE_RESPONSE",
		1304: "MSG_ITEM_MOVE",
		1305: "MSG_ITEM_MOVE_RESPONSE",
		1306: "MSG_ITEM_PICKUP",
		1307: "MSG_ITEM_PICKUP_NOTIFY",
		1310: "MSG_WAREHOUSE_LIST",
		1311: "MSG_WAREHOUSE_LIST_RESPONSE",
		1312: "MSG_WAREHOUSE_STORE",
		1313: "MSG_WAREHOUSE_STORE_RESPONSE",
		1314: "MSG_WAREHOUSE_RETRIEVE",
		1315: "MSG_WAREHOUSE_RETRIEVE_RESPONSE",
	}
	ItemMsgId_value = map[string]int32{
		"MSG_ITEM_INVALID":                0,
		"MSG_ITEM_LIST":                   1300,
		"MSG_ITEM_LIST_RESPONSE":          1301,
		"MSG_ITEM_USE":                    1302,
		"MSG_ITEM_USE_RESPONSE":           1303,
		"MSG_ITEM_MOVE":                   1304,
		"MSG_ITEM_MOVE_RESPONSE":          1305,
		"MSG_ITEM_PICKUP":                 1306,
		"MSG_ITEM_PICKUP_NOTIFY":          1307,
		"MSG_WAREHOUSE_LIST":              1310,
		"MSG_WAREHOUSE_LIST_RESPONSE":     1311,
		"MSG_WAREHOUSE_STORE":             1312,
		"MSG_WAREHOUSE_STORE_RESPONSE":    1313,
		"MSG_WAREHOUSE_RETRIEVE":          1314,
		"MSG_WAREHOUSE_RETRIEVE_RESPONSE": 1315,
	}
)

func (x ItemMsgId) Enum() *ItemMsgId {
	p := new(ItemMsgId)
	*p = x
	return p
}

func (x ItemMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_item_proto_enumTypes[0].Descriptor()
}

func (ItemMsgId) Type() protoreflect.EnumType {
	return &file_item_proto_enumTypes[0]
}

func (x ItemMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemMsgId.Descriptor instead.
func (ItemMsgId) EnumDescriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

// 一个格子的物品信息（背包/仓库通用）
type ItemSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSlot) Reset() {
	*x = ItemSlot{}
	mi := &file_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSlot) ProtoMessage() {}

func (x *ItemSlot) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSlot.ProtoReflect.Descriptor instead.
func (*ItemSlot) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemSlot) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ItemSlot) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemSlot) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClientItemListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemListRequest) Reset() {
	*x = ClientItemListRequest{}
	mi := &file_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemListRequest) ProtoMessage() {}

func (x *ClientItemListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemListRequest.ProtoReflect.Descriptor instead.
func (*ClientItemListRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{1}
}

func (x *ClientItemListRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ClientItemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 0=成功
	Items         []*ItemSlot            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemListResponse) Reset() {
	*x = ClientItemListResponse{}
	mi := &file_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemListResponse) ProtoMessage() {}

func (x *ClientItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemListResponse.ProtoReflect.Descriptor instead.
func (*ClientItemListResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{2}
}

func (x *ClientItemListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientItemListResponse) GetItems() []*ItemSlot {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClientItemUseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemUseRequest) Reset() {
	*x = ClientItemUseRequest{}
	mi := &file_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemUseRequest) ProtoMessage() {}

func (x *ClientItemUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemUseRequest.ProtoReflect.Descriptor instead.
func (*ClientItemUseRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{3}
}

func (x *ClientItemUseRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientItemUseRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ClientItemUseRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClientItemUseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Remaining     int32                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"` // 使用后该格剩余数量
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemUseResponse) Reset() {
	*x = ClientItemUseResponse{}
	mi := &file_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemUseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemUseResponse) ProtoMessage() {}

func (x *ClientItemUseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemUseResponse.ProtoReflect.Descriptor instead.
func (*ClientItemUseResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{4}
}

func (x *ClientItemUseResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientItemUseResponse) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ClientItemUseResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *ClientItemUseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientItemMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FromSlot      int32                  `protobuf:"varint,2,opt,name=from_slot,json=fromSlot,proto3" json:"from_slot,omitempty"`
	ToSlot        int32                  `protobuf:"varint,3,opt,name=to_slot,json=toSlot,proto3" json:"to_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemMoveRequest) Reset() {
	*x = ClientItemMoveRequest{}
	mi := &file_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemMoveRequest) ProtoMessage() {}

func (x *ClientItemMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemMoveRequest.ProtoReflect.Descriptor instead.
func (*ClientItemMoveRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{5}
}

func (x *ClientItemMoveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientItemMoveRequest) GetFromSlot() int32 {
	if x != nil {
		return x.FromSlot
	}
	return 0
}

func (x *ClientItemMoveRequest) GetToSlot() int32 {
	if x != nil {
		return x.ToSlot
	}
	return 0
}

type ClientItemMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemMoveResponse) Reset() {
	*x = ClientItemMoveResponse{}
	mi := &file_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemMoveResponse) ProtoMessage() {}

func (x *ClientItemMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemMoveResponse.ProtoReflect.Descriptor instead.
func (*ClientItemMoveResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{6}
}

func (x *ClientItemMoveResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientItemMoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 客户端 → GameServer → MapServer：请求拾取玩家附近的掉落物
type ClientItemPickupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemPickupRequest) Reset() {
	*x = ClientItemPickupRequest{}
	mi := &file_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemPickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemPickupRequest) ProtoMessage() {}

func (x *ClientItemPickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemPickupRequest.ProtoReflect.Descriptor instead.
func (*ClientItemPickupRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{7}
}

func (x *ClientItemPickupRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientItemPickupRequest) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

// GameServer → 客户端：拾取结果
type ClientItemPickupNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 0=拾到；非0=无可拾取/失败
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientItemPickupNotify) Reset() {
	*x = ClientItemPickupNotify{}
	mi := &file_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientItemPickupNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientItemPickupNotify) ProtoMessage() {}

func (x *ClientItemPickupNotify) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientItemPickupNotify.ProtoReflect.Descriptor instead.
func (*ClientItemPickupNotify) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{8}
}

func (x *ClientItemPickupNotify) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientItemPickupNotify) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ClientItemPickupNotify) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ClientItemPickupNotify) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// MapServer → GameServer（跨服 push，crossserver 506）：授权把物品发给玩家背包
type ItemGrantNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemGrantNotify) Reset() {
	*x = ItemGrantNotify{}
	mi := &file_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemGrantNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemGrantNotify) ProtoMessage() {}

func (x *ItemGrantNotify) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemGrantNotify.ProtoReflect.Descriptor instead.
func (*ItemGrantNotify) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{9}
}

func (x *ItemGrantNotify) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ItemGrantNotify) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemGrantNotify) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClientWarehouseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientWarehouseListRequest) Reset() {
	*x = ClientWarehouseListRequest{}
	mi := &file_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientWarehouseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWarehouseListRequest) ProtoMessage() {}

func (x *ClientWarehouseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWarehouseListRequest.ProtoReflect.Descriptor instead.
func (*ClientWarehouseListRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{10}
}

func (x *ClientWarehouseListRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ClientWarehouseListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Items         []*ItemSlot            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientWarehouseListResponse) Reset() {
	*x = ClientWarehouseListResponse{}
	mi := &file_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientWarehouseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWarehouseListResponse) ProtoMessage() {}

func (x *ClientWarehouseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWarehouseListResponse.ProtoReflect.Descriptor instead.
func (*ClientWarehouseListResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{11}
}

func (x *ClientWarehouseListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientWarehouseListResponse) GetItems() []*ItemSlot {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClientWarehouseStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	BagSlot       int32                  `protobuf:"varint,2,opt,name=bag_slot,json=bagSlot,proto3" json:"bag_slot,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientWarehouseStoreRequest) Reset() {
	*x = ClientWarehouseStoreRequest{}
	mi := &file_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientWarehouseStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWarehouseStoreRequest) ProtoMessage() {}

func (x *ClientWarehouseStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWarehouseStoreRequest.ProtoReflect.Descriptor instead.
func (*ClientWarehouseStoreRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{12}
}

func (x *ClientWarehouseStoreRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientWarehouseStoreRequest) GetBagSlot() int32 {
	if x != nil {
		return x.BagSlot
	}
	return 0
}

func (x *ClientWarehouseStoreRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClientWarehouseStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	WarehouseSlot int32                  `protobuf:"varint,2,opt,name=warehouse_slot,json=warehouseSlot,proto3" json:"warehouse_slot,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientWarehouseStoreResponse) Reset() {
	*x = ClientWarehouseStoreResponse{}
	mi := &file_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientWarehouseStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWarehouseStoreResponse) ProtoMessage() {}

func (x *ClientWarehouseStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWarehouseStoreResponse.ProtoReflect.Descriptor instead.
func (*ClientWarehouseStoreResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{13}
}

func (x *ClientWarehouseStoreResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientWarehouseStoreResponse) GetWarehouseSlot() int32 {
	if x != nil {
		return x.WarehouseSlot
	}
	return 0
}

func (x *ClientWarehouseStoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientWarehouseRetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	WarehouseSlot int32                  `protobuf:"varint,2,opt,name=warehouse_slot,json=warehouseSlot,proto3" json:"warehouse_slot,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientWarehouseRetrieveRequest) Reset() {
	*x = ClientWarehouseRetrieveRequest{}
	mi := &file_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientWarehouseRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWarehouseRetrieveRequest) ProtoMessage() {}

func (x *ClientWarehouseRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWarehouseRetrieveRequest.ProtoReflect.Descriptor instead.
func (*ClientWarehouseRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{14}
}

func (x *ClientWarehouseRetrieveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientWarehouseRetrieveRequest) GetWarehouseSlot() int32 {
	if x != nil {
		return x.WarehouseSlot
	}
	return 0
}

func (x *ClientWarehouseRetrieveRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClientWarehouseRetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	BagSlot       int32                  `protobuf:"varint,2,opt,name=bag_slot,json=bagSlot,proto3" json:"bag_slot,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientWarehouseRetrieveResponse) Reset() {
	*x = ClientWarehouseRetrieveResponse{}
	mi := &file_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientWarehouseRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWarehouseRetrieveResponse) ProtoMessage() {}

func (x *ClientWarehouseRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWarehouseRetrieveResponse.ProtoReflect.Descriptor instead.
func (*ClientWarehouseRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{15}
}

func (x *ClientWarehouseRetrieveResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientWarehouseRetrieveResponse) GetBagSlot() int32 {
	if x != nil {
		return x.BagSlot
	}
	return 0
}

func (x *ClientWarehouseRetrieveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_item_proto protoreflect.FileDescriptor

const file_item_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"item.proto\x12\bprotocol\"M\n" +
	"\bItemSlot\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"4\n" +
	"\x15ClientItemListRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"Z\n" +
	"\x16ClientItemListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.protocol.ItemSlotR\x05items\"]\n" +
	"\x14ClientItemUseRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"w\n" +
	"\x15ClientItemUseResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"j\n" +
	"\x15ClientItemMoveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\tfrom_slot\x18\x02 \x01(\x05R\bfromSlot\x12\x17\n" +
	"\ato_slot\x18\x03 \x01(\x05R\x06toSlot\"F\n" +
	"\x16ClientItemMoveResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x17ClientItemPickupRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\"u\n" +
	"\x16ClientItemPickupNotify\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"]\n" +
	"\x0fItemGrantNotify\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"9\n" +
	"\x1aClientWarehouseListRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"_\n" +
	"\x1bClientWarehouseListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.protocol.ItemSlotR\x05items\"k\n" +
	"\x1bClientWarehouseStoreRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bbag_slot\x18\x02 \x01(\x05R\abagSlot\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"s\n" +
	"\x1cClientWarehouseStoreResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12%\n" +
	"\x0ewarehouse_slot\x18\x02 \x01(\x05R\rwarehouseSlot\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"z\n" +
	"\x1eClientWarehouseRetrieveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12%\n" +
	"\x0ewarehouse_slot\x18\x02 \x01(\x05R\rwarehouseSlot\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"j\n" +
	"\x1fClientWarehouseRetrieveResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x19\n" +
	"\bbag_slot\x18\x02 \x01(\x05R\abagSlot\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\xa0\x03\n" +
	"\tItemMsgId\x12\x14\n" +
	"\x10MSG_ITEM_INVALID\x10\x00\x12\x12\n" +
	"\rMSG_ITEM_LIST\x10\x94\n" +
	"\x12\x1b\n" +
	"\x16MSG_ITEM_LIST_RESPONSE\x10\x95\n" +
	"\x12\x11\n" +
	"\fMSG_ITEM_USE\x10\x96\n" +
	"\x12\x1a\n" +
	"\x15MSG_ITEM_USE_RESPONSE\x10\x97\n" +
	"\x12\x12\n" +
	"\rMSG_ITEM_MOVE\x10\x98\n" +
	"\x12\x1b\n" +
	"\x16MSG_ITEM_MOVE_RESPONSE\x10\x99\n" +
	"\x12\x14\n" +
	"\x0fMSG_ITEM_PICKUP\x10\x9a\n" +
	"\x12\x1b\n" +
	"\x16MSG_ITEM_PICKUP_NOTIFY\x10\x9b\n" +
	"\x12\x17\n" +
	"\x12MSG_WAREHOUSE_LIST\x10\x9e\n" +
	"\x12 \n" +
	"\x1bMSG_WAREHOUSE_LIST_RESPONSE\x10\x9f\n" +
	"\x12\x18\n" +
	"\x13MSG_WAREHOUSE_STORE\x10\xa0\n" +
	"\x12!\n" +
	"\x1cMSG_WAREHOUSE_STORE_RESPONSE\x10\xa1\n" +
	"\x12\x1b\n" +
	"\x16MSG_WAREHOUSE_RETRIEVE\x10\xa2\n" +
	"\x12$\n" +
	"\x1fMSG_WAREHOUSE_RETRIEVE_RESPONSE\x10\xa3\n" +
	"B\rZ\v./;protocolb\x06proto3"

var (
	file_item_proto_rawDescOnce sync.Once
	file_item_proto_rawDescData []byte
)

func file_item_proto_rawDescGZIP() []byte {
	file_item_proto_rawDescOnce.Do(func() {
		file_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)))
	})
	return file_item_proto_rawDescData
}

var file_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_item_proto_goTypes = []any{
	(ItemMsgId)(0),                          // 0: protocol.ItemMsgId
	(*ItemSlot)(nil),                        // 1: protocol.ItemSlot
	(*ClientItemListRequest)(nil),           // 2: protocol.ClientItemListRequest
	(*ClientItemListResponse)(nil),          // 3: protocol.ClientItemListResponse
	(*ClientItemUseRequest)(nil),            // 4: protocol.ClientItemUseRequest
	(*ClientItemUseResponse)(nil),           // 5: protocol.ClientItemUseResponse
	(*ClientItemMoveRequest)(nil),           // 6: protocol.ClientItemMoveRequest
	(*ClientItemMoveResponse)(nil),          // 7: protocol.ClientItemMoveResponse
	(*ClientItemPickupRequest)(nil),         // 8: protocol.ClientItemPickupRequest
	(*ClientItemPickupNotify)(nil),          // 9: protocol.ClientItemPickupNotify
	(*ItemGrantNotify)(nil),                 // 10: protocol.ItemGrantNotify
	(*ClientWarehouseListRequest)(nil),      // 11: protocol.ClientWarehouseListRequest
	(*ClientWarehouseListResponse)(nil),     // 12: protocol.ClientWarehouseListResponse
	(*ClientWarehouseStoreRequest)(nil),     // 13: protocol.ClientWarehouseStoreRequest
	(*ClientWarehouseStoreResponse)(nil),    // 14: protocol.ClientWarehouseStoreResponse
	(*ClientWarehouseRetrieveRequest)(nil),  // 15: protocol.ClientWarehouseRetrieveRequest
	(*ClientWarehouseRetrieveResponse)(nil), // 16: protocol.ClientWarehouseRetrieveResponse
}
var file_item_proto_depIdxs = []int32{
	1, // 0: protocol.ClientItemListResponse.items:type_name -> protocol.ItemSlot
	1, // 1: protocol.ClientWarehouseListResponse.items:type_name -> protocol.ItemSlot
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_item_proto_init() }
func file_item_proto_init() {
	if File_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_proto_goTypes,
		DependencyIndexes: file_item_proto_depIdxs,
		EnumInfos:         file_item_proto_enumTypes,
		MessageInfos:      file_item_proto_msgTypes,
	}.Build()
	File_item_proto = out.File
	file_item_proto_goTypes = nil
	file_item_proto_depIdxs = nil
}
