// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: mail.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailMsgId int32

const (
	MailMsgId_MSG_MAIL_INVALID        MailMsgId = 0
	MailMsgId_MSG_MAIL_SEND           MailMsgId = 1800 // 发送邮件（可发给离线玩家）
	MailMsgId_MSG_MAIL_LIST           MailMsgId = 1802 // 拉取本人邮件
	MailMsgId_MSG_MAIL_LIST_RESPONSE  MailMsgId = 1803
	MailMsgId_MSG_MAIL_CLAIM          MailMsgId = 1804 // 领取邮件附件
	MailMsgId_MSG_MAIL_CLAIM_RESPONSE MailMsgId = 1805
)

// Enum value maps for MailMsgId.
var (
	MailMsgId_name = map[int32]string{
		0:    "MSG_MAIL_INVALID",
		1800: "MSG_MAIL_SEND",
		1802: "MSG_MAIL_LIST",
		1803: "MSG_MAIL_LIST_RESPONSE",
		1804: "MSG_MAIL_CLAIM",
		1805: "MSG_MAIL_CLAIM_RESPONSE",
	}
	MailMsgId_value = map[string]int32{
		"MSG_MAIL_INVALID":        0,
		"MSG_MAIL_SEND":           1800,
		"MSG_MAIL_LIST":           1802,
		"MSG_MAIL_LIST_RESPONSE":  1803,
		"MSG_MAIL_CLAIM":          1804,
		"MSG_MAIL_CLAIM_RESPONSE": 1805,
	}
)

func (x MailMsgId) Enum() *MailMsgId {
	p := new(MailMsgId)
	*p = x
	return p
}

func (x MailMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[0].Descriptor()
}

func (MailMsgId) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[0]
}

func (x MailMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailMsgId.Descriptor instead.
func (MailMsgId) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

type MailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Gold          int64                  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"` // 金币附件
	IsClaimed     bool                   `protobuf:"varint,6,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailInfo) Reset() {
	*x = MailInfo{}
	mi := &file_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailInfo) ProtoMessage() {}

func (x *MailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailInfo.ProtoReflect.Descriptor instead.
func (*MailInfo) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailInfo) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *MailInfo) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MailInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MailInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MailInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *MailInfo) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

type ClientMailSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPlayerId  int64                  `protobuf:"varint,1,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	ToPlayerId    int64                  `protobuf:"varint,2,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Gold          int64                  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMailSendRequest) Reset() {
	*x = ClientMailSendRequest{}
	mi := &file_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMailSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMailSendRequest) ProtoMessage() {}

func (x *ClientMailSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMailSendRequest.ProtoReflect.Descriptor instead.
func (*ClientMailSendRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMailSendRequest) GetFromPlayerId() int64 {
	if x != nil {
		return x.FromPlayerId
	}
	return 0
}

func (x *ClientMailSendRequest) GetToPlayerId() int64 {
	if x != nil {
		return x.ToPlayerId
	}
	return 0
}

func (x *ClientMailSendRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ClientMailSendRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ClientMailSendRequest) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type ClientMailListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMailListRequest) Reset() {
	*x = ClientMailListRequest{}
	mi := &file_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMailListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMailListRequest) ProtoMessage() {}

func (x *ClientMailListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMailListRequest.ProtoReflect.Descriptor instead.
func (*ClientMailListRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMailListRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ClientMailListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Mails         []*MailInfo            `protobuf:"bytes,2,rep,name=mails,proto3" json:"mails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMailListResponse) Reset() {
	*x = ClientMailListResponse{}
	mi := &file_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMailListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMailListResponse) ProtoMessage() {}

func (x *ClientMailListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMailListResponse.ProtoReflect.Descriptor instead.
func (*ClientMailListResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

func (x *ClientMailListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientMailListResponse) GetMails() []*MailInfo {
	if x != nil {
		return x.Mails
	}
	return nil
}

type ClientMailClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MailId        int64                  `protobuf:"varint,2,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMailClaimRequest) Reset() {
	*x = ClientMailClaimRequest{}
	mi := &file_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMailClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMailClaimRequest) ProtoMessage() {}

func (x *ClientMailClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMailClaimRequest.ProtoReflect.Descriptor instead.
func (*ClientMailClaimRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMailClaimRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientMailClaimRequest) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type ClientMailClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 0=成功
	MailId        int64                  `protobuf:"varint,2,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	Gold          int64                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"` // 到账金币
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMailClaimResponse) Reset() {
	*x = ClientMailClaimResponse{}
	mi := &file_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMailClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMailClaimResponse) ProtoMessage() {}

func (x *ClientMailClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMailClaimResponse.ProtoReflect.Descriptor instead.
func (*ClientMailClaimResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{5}
}

func (x *ClientMailClaimResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientMailClaimResponse) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *ClientMailClaimResponse) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *ClientMailClaimResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mail_proto protoreflect.FileDescriptor

const file_mail_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mail.proto\x12\bprotocol\"\x9e\x01\n" +
	"\bMailInfo\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x03R\x04gold\x12\x1d\n" +
	"\n" +
	"is_claimed\x18\x06 \x01(\bR\tisClaimed\"\xa3\x01\n" +
	"\x15ClientMailSendRequest\x12$\n" +
	"\x0efrom_player_id\x18\x01 \x01(\x03R\ffromPlayerId\x12 \n" +
	"\fto_player_id\x18\x02 \x01(\x03R\n" +
	"toPlayerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x03R\x04gold\"4\n" +
	"\x15ClientMailListRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"Z\n" +
	"\x16ClientMailListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12(\n" +
	"\x05mails\x18\x02 \x03(\v2\x12.protocol.MailInfoR\x05mails\"N\n" +
	"\x16ClientMailClaimRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x17\n" +
	"\amail_id\x18\x02 \x01(\x03R\x06mailId\"t\n" +
	"\x17ClientMailClaimResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x17\n" +
	"\amail_id\x18\x02 \x01(\x03R\x06mailId\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x03R\x04gold\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\x99\x01\n" +
	"\tMailMsgId\x12\x14\n" +
	"\x10MSG_MAIL_INVALID\x10\x00\x12\x12\n" +
	"\rMSG_MAIL_SEND\x10\x88\x0e\x12\x12\n" +
	"\rMSG_MAIL_LIST\x10\x8a\x0e\x12\x1b\n" +
	"\x16MSG_MAIL_LIST_RESPONSE\x10\x8b\x0e\x12\x13\n" +
	"\x0eMSG_MAIL_CLAIM\x10\x8c\x0e\x12\x1c\n" +
	"\x17MSG_MAIL_CLAIM_RESPONSE\x10\x8d\x0eB\rZ\v./;protocolb\x06proto3"

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData []byte
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)))
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mail_proto_goTypes = []any{
	(MailMsgId)(0),                  // 0: protocol.MailMsgId
	(*MailInfo)(nil),                // 1: protocol.MailInfo
	(*ClientMailSendRequest)(nil),   // 2: protocol.ClientMailSendRequest
	(*ClientMailListRequest)(nil),   // 3: protocol.ClientMailListRequest
	(*ClientMailListResponse)(nil),  // 4: protocol.ClientMailListResponse
	(*ClientMailClaimRequest)(nil),  // 5: protocol.ClientMailClaimRequest
	(*ClientMailClaimResponse)(nil), // 6: protocol.ClientMailClaimResponse
}
var file_mail_proto_depIdxs = []int32{
	1, // 0: protocol.ClientMailListResponse.mails:type_name -> protocol.MailInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		EnumInfos:         file_mail_proto_enumTypes,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
