// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: mmo_auth.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 账号创建
type AccountCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCreateRequest) Reset() {
	*x = AccountCreateRequest{}
	mi := &file_mmo_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreateRequest) ProtoMessage() {}

func (x *AccountCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreateRequest.ProtoReflect.Descriptor instead.
func (*AccountCreateRequest) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AccountCreateRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AccountCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCreateResponse) Reset() {
	*x = AccountCreateResponse{}
	mi := &file_mmo_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreateResponse) ProtoMessage() {}

func (x *AccountCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreateResponse.ProtoReflect.Descriptor instead.
func (*AccountCreateResponse) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCreateResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *AccountCreateResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *AccountCreateResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 账号登录
type AccountLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLoginRequest) Reset() {
	*x = AccountLoginRequest{}
	mi := &file_mmo_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginRequest) ProtoMessage() {}

func (x *AccountLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginRequest.ProtoReflect.Descriptor instead.
func (*AccountLoginRequest) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AccountLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccountLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	AccountId     int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Servers       []*ServerInfo          `protobuf:"bytes,5,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLoginResponse) Reset() {
	*x = AccountLoginResponse{}
	mi := &file_mmo_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginResponse) ProtoMessage() {}

func (x *AccountLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginResponse.ProtoReflect.Descriptor instead.
func (*AccountLoginResponse) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AccountLoginResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *AccountLoginResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *AccountLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccountLoginResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountLoginResponse) GetServers() []*ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

// 服务器信息
type ServerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName     string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerType     string                 `protobuf:"bytes,3,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	GroupId        int32                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Address        string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Port           int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Status         int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	OnlineCount    int32                  `protobuf:"varint,8,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	MaxOnlineCount int32                  `protobuf:"varint,9,opt,name=max_online_count,json=maxOnlineCount,proto3" json:"max_online_count,omitempty"`
	Region         string                 `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Version        string                 `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_mmo_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ServerInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfo) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *ServerInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ServerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServerInfo) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *ServerInfo) GetMaxOnlineCount() int32 {
	if x != nil {
		return x.MaxOnlineCount
	}
	return 0
}

func (x *ServerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 服务器列表
type ServerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerListRequest) Reset() {
	*x = ServerListRequest{}
	mi := &file_mmo_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListRequest) ProtoMessage() {}

func (x *ServerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListRequest.ProtoReflect.Descriptor instead.
func (*ServerListRequest) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ServerListRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ServerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Servers       []*ServerInfo          `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerListResponse) Reset() {
	*x = ServerListResponse{}
	mi := &file_mmo_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListResponse) ProtoMessage() {}

func (x *ServerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListResponse.ProtoReflect.Descriptor instead.
func (*ServerListResponse) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ServerListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ServerListResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ServerListResponse) GetServers() []*ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

// 服务器注册 (内部服务使用)
type ServerRegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName     string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerType     string                 `protobuf:"bytes,3,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	GroupId        int32                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Address        string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Port           int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	MaxOnlineCount int32                  `protobuf:"varint,7,opt,name=max_online_count,json=maxOnlineCount,proto3" json:"max_online_count,omitempty"`
	Region         string                 `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	Version        string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerRegisterRequest) Reset() {
	*x = ServerRegisterRequest{}
	mi := &file_mmo_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegisterRequest) ProtoMessage() {}

func (x *ServerRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegisterRequest.ProtoReflect.Descriptor instead.
func (*ServerRegisterRequest) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ServerRegisterRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerRegisterRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerRegisterRequest) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *ServerRegisterRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ServerRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerRegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerRegisterRequest) GetMaxOnlineCount() int32 {
	if x != nil {
		return x.MaxOnlineCount
	}
	return 0
}

func (x *ServerRegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ServerRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ServerRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRegisterResponse) Reset() {
	*x = ServerRegisterResponse{}
	mi := &file_mmo_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegisterResponse) ProtoMessage() {}

func (x *ServerRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegisterResponse.ProtoReflect.Descriptor instead.
func (*ServerRegisterResponse) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ServerRegisterResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ServerRegisterResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 服务器心跳 (内部服务使用)
type ServerHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,2,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Load          float32                `protobuf:"fixed32,5,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHeartbeatRequest) Reset() {
	*x = ServerHeartbeatRequest{}
	mi := &file_mmo_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeatRequest) ProtoMessage() {}

func (x *ServerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ServerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ServerHeartbeatRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerHeartbeatRequest) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *ServerHeartbeatRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServerHeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerHeartbeatRequest) GetLoad() float32 {
	if x != nil {
		return x.Load
	}
	return 0
}

type ServerHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHeartbeatResponse) Reset() {
	*x = ServerHeartbeatResponse{}
	mi := &file_mmo_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeatResponse) ProtoMessage() {}

func (x *ServerHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*ServerHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_mmo_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ServerHeartbeatResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ServerHeartbeatResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_mmo_auth_proto protoreflect.FileDescriptor

const file_mmo_auth_proto_rawDesc = "" +
	"\n" +
	"\x0emmo_auth.proto\x12\bprotocol\"b\n" +
	"\x14AccountCreateRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"k\n" +
	"\x15AccountCreateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\"K\n" +
	"\x13AccountLoginRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb0\x01\n" +
	"\x14AccountLoginResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x03R\taccountId\x12.\n" +
	"\aservers\x18\x05 \x03(\v2\x14.protocol.ServerInfoR\aservers\"\xcb\x02\n" +
	"\n" +
	"ServerInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x1f\n" +
	"\vserver_type\x18\x03 \x01(\tR\n" +
	"serverType\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x05R\agroupId\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12!\n" +
	"\fonline_count\x18\b \x01(\x05R\vonlineCount\x12(\n" +
	"\x10max_online_count\x18\t \x01(\x05R\x0emaxOnlineCount\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12\x18\n" +
	"\aversion\x18\v \x01(\tR\aversion\".\n" +
	"\x11ServerListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"y\n" +
	"\x12ServerListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12.\n" +
	"\aservers\x18\x03 \x03(\v2\x14.protocol.ServerInfoR\aservers\"\x9b\x02\n" +
	"\x15ServerRegisterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x1f\n" +
	"\vserver_type\x18\x03 \x01(\tR\n" +
	"serverType\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x05R\agroupId\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12(\n" +
	"\x10max_online_count\x18\a \x01(\x05R\x0emaxOnlineCount\x12\x16\n" +
	"\x06region\x18\b \x01(\tR\x06region\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\"M\n" +
	"\x16ServerRegisterResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\x9e\x01\n" +
	"\x16ServerHeartbeatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12!\n" +
	"\fonline_count\x18\x02 \x01(\x05R\vonlineCount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04load\x18\x05 \x01(\x02R\x04load\"N\n" +
	"\x17ServerHeartbeatResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsgB\rZ\v./;protocolb\x06proto3"

var (
	file_mmo_auth_proto_rawDescOnce sync.Once
	file_mmo_auth_proto_rawDescData []byte
)

func file_mmo_auth_proto_rawDescGZIP() []byte {
	file_mmo_auth_proto_rawDescOnce.Do(func() {
		file_mmo_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mmo_auth_proto_rawDesc), len(file_mmo_auth_proto_rawDesc)))
	})
	return file_mmo_auth_proto_rawDescData
}

var file_mmo_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mmo_auth_proto_goTypes = []any{
	(*AccountCreateRequest)(nil),    // 0: protocol.AccountCreateRequest
	(*AccountCreateResponse)(nil),   // 1: protocol.AccountCreateResponse
	(*AccountLoginRequest)(nil),     // 2: protocol.AccountLoginRequest
	(*AccountLoginResponse)(nil),    // 3: protocol.AccountLoginResponse
	(*ServerInfo)(nil),              // 4: protocol.ServerInfo
	(*ServerListRequest)(nil),       // 5: protocol.ServerListRequest
	(*ServerListResponse)(nil),      // 6: protocol.ServerListResponse
	(*ServerRegisterRequest)(nil),   // 7: protocol.ServerRegisterRequest
	(*ServerRegisterResponse)(nil),  // 8: protocol.ServerRegisterResponse
	(*ServerHeartbeatRequest)(nil),  // 9: protocol.ServerHeartbeatRequest
	(*ServerHeartbeatResponse)(nil), // 10: protocol.ServerHeartbeatResponse
}
var file_mmo_auth_proto_depIdxs = []int32{
	4, // 0: protocol.AccountLoginResponse.servers:type_name -> protocol.ServerInfo
	4, // 1: protocol.ServerListResponse.servers:type_name -> protocol.ServerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mmo_auth_proto_init() }
func file_mmo_auth_proto_init() {
	if File_mmo_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mmo_auth_proto_rawDesc), len(file_mmo_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mmo_auth_proto_goTypes,
		DependencyIndexes: file_mmo_auth_proto_depIdxs,
		MessageInfos:      file_mmo_auth_proto_msgTypes,
	}.Build()
	File_mmo_auth_proto = out.File
	file_mmo_auth_proto_goTypes = nil
	file_mmo_auth_proto_depIdxs = nil
}
