// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: player.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家基础信息
type PlayerBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold          int64                  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	VipLevel      int32                  `protobuf:"varint,6,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`
	ServerId      int32                  `protobuf:"varint,7,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastLoginTime int64                  `protobuf:"varint,9,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBasicInfo) Reset() {
	*x = PlayerBasicInfo{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBasicInfo) ProtoMessage() {}

func (x *PlayerBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBasicInfo.ProtoReflect.Descriptor instead.
func (*PlayerBasicInfo) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerBasicInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerBasicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerBasicInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerBasicInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerBasicInfo) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *PlayerBasicInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *PlayerBasicInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PlayerBasicInfo) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

// 玩家创建
type PlayerCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex           int32                  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Profession    int32                  `protobuf:"varint,4,opt,name=profession,proto3" json:"profession,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCreateRequest) Reset() {
	*x = PlayerCreateRequest{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCreateRequest) ProtoMessage() {}

func (x *PlayerCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCreateRequest.ProtoReflect.Descriptor instead.
func (*PlayerCreateRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerCreateRequest) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *PlayerCreateRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PlayerCreateRequest) GetProfession() int32 {
	if x != nil {
		return x.Profession
	}
	return 0
}

type PlayerCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerInfo    *PlayerBasicInfo       `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCreateResponse) Reset() {
	*x = PlayerCreateResponse{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCreateResponse) ProtoMessage() {}

func (x *PlayerCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCreateResponse.ProtoReflect.Descriptor instead.
func (*PlayerCreateResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerCreateResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerCreateResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *PlayerCreateResponse) GetPlayerInfo() *PlayerBasicInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 玩家登录
type PlayerLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginRequest) Reset() {
	*x = PlayerLoginRequest{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginRequest) ProtoMessage() {}

func (x *PlayerLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginRequest.ProtoReflect.Descriptor instead.
func (*PlayerLoginRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLoginRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerLoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PlayerLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerInfo    *PlayerBasicInfo       `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginResponse) Reset() {
	*x = PlayerLoginResponse{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginResponse) ProtoMessage() {}

func (x *PlayerLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginResponse.ProtoReflect.Descriptor instead.
func (*PlayerLoginResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerLoginResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerLoginResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *PlayerLoginResponse) GetPlayerInfo() *PlayerBasicInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 玩家登出
type PlayerLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLogoutRequest) Reset() {
	*x = PlayerLogoutRequest{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogoutRequest) ProtoMessage() {}

func (x *PlayerLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogoutRequest.ProtoReflect.Descriptor instead.
func (*PlayerLogoutRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerLogoutRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerLogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLogoutResponse) Reset() {
	*x = PlayerLogoutResponse{}
	mi := &file_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogoutResponse) ProtoMessage() {}

func (x *PlayerLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogoutResponse.ProtoReflect.Descriptor instead.
func (*PlayerLogoutResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerLogoutResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerLogoutResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 获取玩家信息
type PlayerGetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGetInfoRequest) Reset() {
	*x = PlayerGetInfoRequest{}
	mi := &file_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGetInfoRequest) ProtoMessage() {}

func (x *PlayerGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGetInfoRequest.ProtoReflect.Descriptor instead.
func (*PlayerGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerGetInfoRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerGetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerInfo    *PlayerBasicInfo       `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGetInfoResponse) Reset() {
	*x = PlayerGetInfoResponse{}
	mi := &file_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGetInfoResponse) ProtoMessage() {}

func (x *PlayerGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGetInfoResponse.ProtoReflect.Descriptor instead.
func (*PlayerGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerGetInfoResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerGetInfoResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *PlayerGetInfoResponse) GetPlayerInfo() *PlayerBasicInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 更新玩家信息
type PlayerUpdateInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HeadIcon      int32                  `protobuf:"varint,3,opt,name=head_icon,json=headIcon,proto3" json:"head_icon,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUpdateInfoRequest) Reset() {
	*x = PlayerUpdateInfoRequest{}
	mi := &file_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUpdateInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUpdateInfoRequest) ProtoMessage() {}

func (x *PlayerUpdateInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUpdateInfoRequest.ProtoReflect.Descriptor instead.
func (*PlayerUpdateInfoRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerUpdateInfoRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerUpdateInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerUpdateInfoRequest) GetHeadIcon() int32 {
	if x != nil {
		return x.HeadIcon
	}
	return 0
}

func (x *PlayerUpdateInfoRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type PlayerUpdateInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	PlayerInfo    *PlayerBasicInfo       `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUpdateInfoResponse) Reset() {
	*x = PlayerUpdateInfoResponse{}
	mi := &file_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUpdateInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUpdateInfoResponse) ProtoMessage() {}

func (x *PlayerUpdateInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUpdateInfoResponse.ProtoReflect.Descriptor instead.
func (*PlayerUpdateInfoResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerUpdateInfoResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerUpdateInfoResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *PlayerUpdateInfoResponse) GetPlayerInfo() *PlayerBasicInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\bprotocol\"\x81\x02\n" +
	"\x0fPlayerBasicInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x03R\x04gold\x12\x1b\n" +
	"\tvip_level\x18\x06 \x01(\x05R\bvipLevel\x12\x1b\n" +
	"\tserver_id\x18\a \x01(\x05R\bserverId\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12&\n" +
	"\x0flast_login_time\x18\t \x01(\x03R\rlastLoginTime\"m\n" +
	"\x13PlayerCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x02 \x01(\x05R\x03sex\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1e\n" +
	"\n" +
	"profession\x18\x04 \x01(\x05R\n" +
	"profession\"\x87\x01\n" +
	"\x14PlayerCreateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12:\n" +
	"\vplayer_info\x18\x03 \x01(\v2\x19.protocol.PlayerBasicInfoR\n" +
	"playerInfo\"G\n" +
	"\x12PlayerLoginRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x86\x01\n" +
	"\x13PlayerLoginResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12:\n" +
	"\vplayer_info\x18\x03 \x01(\v2\x19.protocol.PlayerBasicInfoR\n" +
	"playerInfo\"2\n" +
	"\x13PlayerLogoutRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"K\n" +
	"\x14PlayerLogoutResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"3\n" +
	"\x14PlayerGetInfoRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x88\x01\n" +
	"\x15PlayerGetInfoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12:\n" +
	"\vplayer_info\x18\x03 \x01(\v2\x19.protocol.PlayerBasicInfoR\n" +
	"playerInfo\"\x85\x01\n" +
	"\x17PlayerUpdateInfoRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\thead_icon\x18\x03 \x01(\x05R\bheadIcon\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\x8b\x01\n" +
	"\x18PlayerUpdateInfoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12:\n" +
	"\vplayer_info\x18\x03 \x01(\v2\x19.protocol.PlayerBasicInfoR\n" +
	"playerInfoB\rZ\v./;protocolb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_player_proto_goTypes = []any{
	(*PlayerBasicInfo)(nil),          // 0: protocol.PlayerBasicInfo
	(*PlayerCreateRequest)(nil),      // 1: protocol.PlayerCreateRequest
	(*PlayerCreateResponse)(nil),     // 2: protocol.PlayerCreateResponse
	(*PlayerLoginRequest)(nil),       // 3: protocol.PlayerLoginRequest
	(*PlayerLoginResponse)(nil),      // 4: protocol.PlayerLoginResponse
	(*PlayerLogoutRequest)(nil),      // 5: protocol.PlayerLogoutRequest
	(*PlayerLogoutResponse)(nil),     // 6: protocol.PlayerLogoutResponse
	(*PlayerGetInfoRequest)(nil),     // 7: protocol.PlayerGetInfoRequest
	(*PlayerGetInfoResponse)(nil),    // 8: protocol.PlayerGetInfoResponse
	(*PlayerUpdateInfoRequest)(nil),  // 9: protocol.PlayerUpdateInfoRequest
	(*PlayerUpdateInfoResponse)(nil), // 10: protocol.PlayerUpdateInfoResponse
}
var file_player_proto_depIdxs = []int32{
	0, // 0: protocol.PlayerCreateResponse.player_info:type_name -> protocol.PlayerBasicInfo
	0, // 1: protocol.PlayerLoginResponse.player_info:type_name -> protocol.PlayerBasicInfo
	0, // 2: protocol.PlayerGetInfoResponse.player_info:type_name -> protocol.PlayerBasicInfo
	0, // 3: protocol.PlayerUpdateInfoResponse.player_info:type_name -> protocol.PlayerBasicInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
