// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: skill.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillMsgId int32

const (
	SkillMsgId_MSG_SKILL_INVALID          SkillMsgId = 0
	SkillMsgId_MSG_SKILL_LIST             SkillMsgId = 1400 // 查询已学技能
	SkillMsgId_MSG_SKILL_LIST_RESPONSE    SkillMsgId = 1401
	SkillMsgId_MSG_SKILL_LEARN            SkillMsgId = 1402 // 学习技能
	SkillMsgId_MSG_SKILL_LEARN_RESPONSE   SkillMsgId = 1403
	SkillMsgId_MSG_SKILL_UPGRADE          SkillMsgId = 1404 // 升级技能
	SkillMsgId_MSG_SKILL_UPGRADE_RESPONSE SkillMsgId = 1405
	SkillMsgId_MSG_SKILL_CAST             SkillMsgId = 1406 // 释放技能
	SkillMsgId_MSG_SKILL_CAST_RESPONSE    SkillMsgId = 1407
)

// Enum value maps for SkillMsgId.
var (
	SkillMsgId_name = map[int32]string{
		0:    "MSG_SKILL_INVALID",
		1400: "MSG_SKILL_LIST",
		1401: "MSG_SKILL_LIST_RESPONSE",
		1402: "MSG_SKILL_LEARN",
		1403: "MSG_SKILL_LEARN_RESPONSE",
		1404: "MSG_SKILL_UPGRADE",
		1405: "MSG_SKILL_UPGRADE_RESPONSE",
		1406: "MSG_SKILL_CAST",
		1407: "MSG_SKILL_CAST_RESPONSE",
	}
	SkillMsgId_value = map[string]int32{
		"MSG_SKILL_INVALID":          0,
		"MSG_SKILL_LIST":             1400,
		"MSG_SKILL_LIST_RESPONSE":    1401,
		"MSG_SKILL_LEARN":            1402,
		"MSG_SKILL_LEARN_RESPONSE":   1403,
		"MSG_SKILL_UPGRADE":          1404,
		"MSG_SKILL_UPGRADE_RESPONSE": 1405,
		"MSG_SKILL_CAST":             1406,
		"MSG_SKILL_CAST_RESPONSE":    1407,
	}
)

func (x SkillMsgId) Enum() *SkillMsgId {
	p := new(SkillMsgId)
	*p = x
	return p
}

func (x SkillMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkillMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_skill_proto_enumTypes[0].Descriptor()
}

func (SkillMsgId) Type() protoreflect.EnumType {
	return &file_skill_proto_enumTypes[0]
}

func (x SkillMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkillMsgId.Descriptor instead.
func (SkillMsgId) EnumDescriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

type SkillInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	MaxLevel      int32                  `protobuf:"varint,3,opt,name=max_level,json=maxLevel,proto3" json:"max_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillInfo) Reset() {
	*x = SkillInfo{}
	mi := &file_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInfo) ProtoMessage() {}

func (x *SkillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInfo.ProtoReflect.Descriptor instead.
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

func (x *SkillInfo) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SkillInfo) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

type ClientSkillListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillListRequest) Reset() {
	*x = ClientSkillListRequest{}
	mi := &file_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillListRequest) ProtoMessage() {}

func (x *ClientSkillListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillListRequest.ProtoReflect.Descriptor instead.
func (*ClientSkillListRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{1}
}

func (x *ClientSkillListRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ClientSkillListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Skills        []*SkillInfo           `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillListResponse) Reset() {
	*x = ClientSkillListResponse{}
	mi := &file_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillListResponse) ProtoMessage() {}

func (x *ClientSkillListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillListResponse.ProtoReflect.Descriptor instead.
func (*ClientSkillListResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{2}
}

func (x *ClientSkillListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientSkillListResponse) GetSkills() []*SkillInfo {
	if x != nil {
		return x.Skills
	}
	return nil
}

type ClientSkillLearnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillLearnRequest) Reset() {
	*x = ClientSkillLearnRequest{}
	mi := &file_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillLearnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillLearnRequest) ProtoMessage() {}

func (x *ClientSkillLearnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillLearnRequest.ProtoReflect.Descriptor instead.
func (*ClientSkillLearnRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSkillLearnRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientSkillLearnRequest) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

type ClientSkillLearnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillLearnResponse) Reset() {
	*x = ClientSkillLearnResponse{}
	mi := &file_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillLearnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillLearnResponse) ProtoMessage() {}

func (x *ClientSkillLearnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillLearnResponse.ProtoReflect.Descriptor instead.
func (*ClientSkillLearnResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{4}
}

func (x *ClientSkillLearnResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientSkillLearnResponse) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *ClientSkillLearnResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientSkillUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillUpgradeRequest) Reset() {
	*x = ClientSkillUpgradeRequest{}
	mi := &file_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillUpgradeRequest) ProtoMessage() {}

func (x *ClientSkillUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillUpgradeRequest.ProtoReflect.Descriptor instead.
func (*ClientSkillUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{5}
}

func (x *ClientSkillUpgradeRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientSkillUpgradeRequest) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

type ClientSkillUpgradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillUpgradeResponse) Reset() {
	*x = ClientSkillUpgradeResponse{}
	mi := &file_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillUpgradeResponse) ProtoMessage() {}

func (x *ClientSkillUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillUpgradeResponse.ProtoReflect.Descriptor instead.
func (*ClientSkillUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{6}
}

func (x *ClientSkillUpgradeResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientSkillUpgradeResponse) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *ClientSkillUpgradeResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ClientSkillUpgradeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientSkillCastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillCastRequest) Reset() {
	*x = ClientSkillCastRequest{}
	mi := &file_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillCastRequest) ProtoMessage() {}

func (x *ClientSkillCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillCastRequest.ProtoReflect.Descriptor instead.
func (*ClientSkillCastRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{7}
}

func (x *ClientSkillCastRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientSkillCastRequest) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *ClientSkillCastRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type ClientSkillCastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSkillCastResponse) Reset() {
	*x = ClientSkillCastResponse{}
	mi := &file_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSkillCastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSkillCastResponse) ProtoMessage() {}

func (x *ClientSkillCastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSkillCastResponse.ProtoReflect.Descriptor instead.
func (*ClientSkillCastResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{8}
}

func (x *ClientSkillCastResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ClientSkillCastResponse) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *ClientSkillCastResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_skill_proto protoreflect.FileDescriptor

const file_skill_proto_rawDesc = "" +
	"\n" +
	"\vskill.proto\x12\bprotocol\"Y\n" +
	"\tSkillInfo\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x1b\n" +
	"\tmax_level\x18\x03 \x01(\x05R\bmaxLevel\"5\n" +
	"\x16ClientSkillListRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"^\n" +
	"\x17ClientSkillListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12+\n" +
	"\x06skills\x18\x02 \x03(\v2\x13.protocol.SkillInfoR\x06skills\"Q\n" +
	"\x17ClientSkillLearnRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\"c\n" +
	"\x18ClientSkillLearnResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"S\n" +
	"\x19ClientSkillUpgradeRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\"{\n" +
	"\x1aClientSkillUpgradeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"m\n" +
	"\x16ClientSkillCastRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"b\n" +
	"\x17ClientSkillCastResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\xf7\x01\n" +
	"\n" +
	"SkillMsgId\x12\x15\n" +
	"\x11MSG_SKILL_INVALID\x10\x00\x12\x13\n" +
	"\x0eMSG_SKILL_LIST\x10\xf8\n" +
	"\x12\x1c\n" +
	"\x17MSG_SKILL_LIST_RESPONSE\x10\xf9\n" +
	"\x12\x14\n" +
	"\x0fMSG_SKILL_LEARN\x10\xfa\n" +
	"\x12\x1d\n" +
	"\x18MSG_SKILL_LEARN_RESPONSE\x10\xfb\n" +
	"\x12\x16\n" +
	"\x11MSG_SKILL_UPGRADE\x10\xfc\n" +
	"\x12\x1f\n" +
	"\x1aMSG_SKILL_UPGRADE_RESPONSE\x10\xfd\n" +
	"\x12\x13\n" +
	"\x0eMSG_SKILL_CAST\x10\xfe\n" +
	"\x12\x1c\n" +
	"\x17MSG_SKILL_CAST_RESPONSE\x10\xff\n" +
	"B\rZ\v./;protocolb\x06proto3"

var (
	file_skill_proto_rawDescOnce sync.Once
	file_skill_proto_rawDescData []byte
)

func file_skill_proto_rawDescGZIP() []byte {
	file_skill_proto_rawDescOnce.Do(func() {
		file_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)))
	})
	return file_skill_proto_rawDescData
}

var file_skill_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_skill_proto_goTypes = []any{
	(SkillMsgId)(0),                    // 0: protocol.SkillMsgId
	(*SkillInfo)(nil),                  // 1: protocol.SkillInfo
	(*ClientSkillListRequest)(nil),     // 2: protocol.ClientSkillListRequest
	(*ClientSkillListResponse)(nil),    // 3: protocol.ClientSkillListResponse
	(*ClientSkillLearnRequest)(nil),    // 4: protocol.ClientSkillLearnRequest
	(*ClientSkillLearnResponse)(nil),   // 5: protocol.ClientSkillLearnResponse
	(*ClientSkillUpgradeRequest)(nil),  // 6: protocol.ClientSkillUpgradeRequest
	(*ClientSkillUpgradeResponse)(nil), // 7: protocol.ClientSkillUpgradeResponse
	(*ClientSkillCastRequest)(nil),     // 8: protocol.ClientSkillCastRequest
	(*ClientSkillCastResponse)(nil),    // 9: protocol.ClientSkillCastResponse
}
var file_skill_proto_depIdxs = []int32{
	1, // 0: protocol.ClientSkillListResponse.skills:type_name -> protocol.SkillInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_skill_proto_init() }
func file_skill_proto_init() {
	if File_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skill_proto_goTypes,
		DependencyIndexes: file_skill_proto_depIdxs,
		EnumInfos:         file_skill_proto_enumTypes,
		MessageInfos:      file_skill_proto_msgTypes,
	}.Build()
	File_skill_proto = out.File
	file_skill_proto_goTypes = nil
	file_skill_proto_depIdxs = nil
}
