// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: team.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamMsgId int32

const (
	TeamMsgId_MSG_TEAM_INVALID       TeamMsgId = 0
	TeamMsgId_MSG_TEAM_CREATE        TeamMsgId = 1600 // 创建队伍
	TeamMsgId_MSG_TEAM_JOIN          TeamMsgId = 1602 // 加入队伍
	TeamMsgId_MSG_TEAM_LEAVE         TeamMsgId = 1604 // 离开队伍
	TeamMsgId_MSG_TEAM_UPDATE_NOTIFY TeamMsgId = 1606 // 队伍花名册变更（推送给全体成员）
)

// Enum value maps for TeamMsgId.
var (
	TeamMsgId_name = map[int32]string{
		0:    "MSG_TEAM_INVALID",
		1600: "MSG_TEAM_CREATE",
		1602: "MSG_TEAM_JOIN",
		1604: "MSG_TEAM_LEAVE",
		1606: "MSG_TEAM_UPDATE_NOTIFY",
	}
	TeamMsgId_value = map[string]int32{
		"MSG_TEAM_INVALID":       0,
		"MSG_TEAM_CREATE":        1600,
		"MSG_TEAM_JOIN":          1602,
		"MSG_TEAM_LEAVE":         1604,
		"MSG_TEAM_UPDATE_NOTIFY": 1606,
	}
)

func (x TeamMsgId) Enum() *TeamMsgId {
	p := new(TeamMsgId)
	*p = x
	return p
}

func (x TeamMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_team_proto_enumTypes[0].Descriptor()
}

func (TeamMsgId) Type() protoreflect.EnumType {
	return &file_team_proto_enumTypes[0]
}

func (x TeamMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamMsgId.Descriptor instead.
func (TeamMsgId) EnumDescriptor() ([]byte, []int) {
	return file_team_proto_rawDescGZIP(), []int{0}
}

// 队伍成员
type TeamMemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMemberInfo) Reset() {
	*x = TeamMemberInfo{}
	mi := &file_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMemberInfo) ProtoMessage() {}

func (x *TeamMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMemberInfo.ProtoReflect.Descriptor instead.
func (*TeamMemberInfo) Descriptor() ([]byte, []int) {
	return file_team_proto_rawDescGZIP(), []int{0}
}

func (x *TeamMemberInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *TeamMemberInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamMemberInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

// 客户端 → 服务器（均为 fire；结果/花名册经 UPDATE_NOTIFY 回推）
type ClientTeamCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTeamCreateRequest) Reset() {
	*x = ClientTeamCreateRequest{}
	mi := &file_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTeamCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTeamCreateRequest) ProtoMessage() {}

func (x *ClientTeamCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTeamCreateRequest.ProtoReflect.Descriptor instead.
func (*ClientTeamCreateRequest) Descriptor() ([]byte, []int) {
	return file_team_proto_rawDescGZIP(), []int{1}
}

func (x *ClientTeamCreateRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ClientTeamJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TeamId        int32                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTeamJoinRequest) Reset() {
	*x = ClientTeamJoinRequest{}
	mi := &file_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTeamJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTeamJoinRequest) ProtoMessage() {}

func (x *ClientTeamJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTeamJoinRequest.ProtoReflect.Descriptor instead.
func (*ClientTeamJoinRequest) Descriptor() ([]byte, []int) {
	return file_team_proto_rawDescGZIP(), []int{2}
}

func (x *ClientTeamJoinRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientTeamJoinRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type ClientTeamLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTeamLeaveRequest) Reset() {
	*x = ClientTeamLeaveRequest{}
	mi := &file_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTeamLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTeamLeaveRequest) ProtoMessage() {}

func (x *ClientTeamLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTeamLeaveRequest.ProtoReflect.Descriptor instead.
func (*ClientTeamLeaveRequest) Descriptor() ([]byte, []int) {
	return file_team_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTeamLeaveRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 服务器 → 客户端：队伍花名册（成员增减/建队/离队都推一遍最新全量花名册）
type ClientTeamUpdateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int32                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Members       []*TeamMemberInfo      `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Disbanded     bool                   `protobuf:"varint,3,opt,name=disbanded,proto3" json:"disbanded,omitempty"` // 队伍已解散（最后一人离开）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTeamUpdateNotify) Reset() {
	*x = ClientTeamUpdateNotify{}
	mi := &file_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTeamUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTeamUpdateNotify) ProtoMessage() {}

func (x *ClientTeamUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTeamUpdateNotify.ProtoReflect.Descriptor instead.
func (*ClientTeamUpdateNotify) Descriptor() ([]byte, []int) {
	return file_team_proto_rawDescGZIP(), []int{4}
}

func (x *ClientTeamUpdateNotify) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ClientTeamUpdateNotify) GetMembers() []*TeamMemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ClientTeamUpdateNotify) GetDisbanded() bool {
	if x != nil {
		return x.Disbanded
	}
	return false
}

var File_team_proto protoreflect.FileDescriptor

const file_team_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"team.proto\x12\bprotocol\"^\n" +
	"\x0eTeamMemberInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\"6\n" +
	"\x17ClientTeamCreateRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"M\n" +
	"\x15ClientTeamJoinRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x05R\x06teamId\"5\n" +
	"\x16ClientTeamLeaveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x83\x01\n" +
	"\x16ClientTeamUpdateNotify\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x05R\x06teamId\x122\n" +
	"\amembers\x18\x02 \x03(\v2\x18.protocol.TeamMemberInfoR\amembers\x12\x1c\n" +
	"\tdisbanded\x18\x03 \x01(\bR\tdisbanded*}\n" +
	"\tTeamMsgId\x12\x14\n" +
	"\x10MSG_TEAM_INVALID\x10\x00\x12\x14\n" +
	"\x0fMSG_TEAM_CREATE\x10\xc0\f\x12\x12\n" +
	"\rMSG_TEAM_JOIN\x10\xc2\f\x12\x13\n" +
	"\x0eMSG_TEAM_LEAVE\x10\xc4\f\x12\x1b\n" +
	"\x16MSG_TEAM_UPDATE_NOTIFY\x10\xc6\fB\rZ\v./;protocolb\x06proto3"

var (
	file_team_proto_rawDescOnce sync.Once
	file_team_proto_rawDescData []byte
)

func file_team_proto_rawDescGZIP() []byte {
	file_team_proto_rawDescOnce.Do(func() {
		file_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_proto_rawDesc), len(file_team_proto_rawDesc)))
	})
	return file_team_proto_rawDescData
}

var file_team_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_team_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_team_proto_goTypes = []any{
	(TeamMsgId)(0),                  // 0: protocol.TeamMsgId
	(*TeamMemberInfo)(nil),          // 1: protocol.TeamMemberInfo
	(*ClientTeamCreateRequest)(nil), // 2: protocol.ClientTeamCreateRequest
	(*ClientTeamJoinRequest)(nil),   // 3: protocol.ClientTeamJoinRequest
	(*ClientTeamLeaveRequest)(nil),  // 4: protocol.ClientTeamLeaveRequest
	(*ClientTeamUpdateNotify)(nil),  // 5: protocol.ClientTeamUpdateNotify
}
var file_team_proto_depIdxs = []int32{
	1, // 0: protocol.ClientTeamUpdateNotify.members:type_name -> protocol.TeamMemberInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_team_proto_init() }
func file_team_proto_init() {
	if File_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_proto_rawDesc), len(file_team_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_team_proto_goTypes,
		DependencyIndexes: file_team_proto_depIdxs,
		EnumInfos:         file_team_proto_enumTypes,
		MessageInfos:      file_team_proto_msgTypes,
	}.Build()
	File_team_proto = out.File
	file_team_proto_goTypes = nil
	file_team_proto_depIdxs = nil
}
