// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: trade.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeMsgId int32

const (
	TradeMsgId_MSG_TRADE_INVALID       TradeMsgId = 0
	TradeMsgId_MSG_TRADE_START         TradeMsgId = 1700 // 发起与目标玩家的交易
	TradeMsgId_MSG_TRADE_SET_GOLD      TradeMsgId = 1702 // 设置本方报价金币
	TradeMsgId_MSG_TRADE_CONFIRM       TradeMsgId = 1704 // 确认（双方确认→原子交换）
	TradeMsgId_MSG_TRADE_CANCEL        TradeMsgId = 1706 // 取消交易
	TradeMsgId_MSG_TRADE_UPDATE_NOTIFY TradeMsgId = 1708 // 交易状态变更（推送给双方）
)

// Enum value maps for TradeMsgId.
var (
	TradeMsgId_name = map[int32]string{
		0:    "MSG_TRADE_INVALID",
		1700: "MSG_TRADE_START",
		1702: "MSG_TRADE_SET_GOLD",
		1704: "MSG_TRADE_CONFIRM",
		1706: "MSG_TRADE_CANCEL",
		1708: "MSG_TRADE_UPDATE_NOTIFY",
	}
	TradeMsgId_value = map[string]int32{
		"MSG_TRADE_INVALID":       0,
		"MSG_TRADE_START":         1700,
		"MSG_TRADE_SET_GOLD":      1702,
		"MSG_TRADE_CONFIRM":       1704,
		"MSG_TRADE_CANCEL":        1706,
		"MSG_TRADE_UPDATE_NOTIFY": 1708,
	}
)

func (x TradeMsgId) Enum() *TradeMsgId {
	p := new(TradeMsgId)
	*p = x
	return p
}

func (x TradeMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_trade_proto_enumTypes[0].Descriptor()
}

func (TradeMsgId) Type() protoreflect.EnumType {
	return &file_trade_proto_enumTypes[0]
}

func (x TradeMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeMsgId.Descriptor instead.
func (TradeMsgId) EnumDescriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

// 交易状态
type TradeState int32

const (
	TradeState_TRADE_OPEN      TradeState = 0 // 进行中
	TradeState_TRADE_DONE      TradeState = 1 // 成交（金币已原子交换）
	TradeState_TRADE_CANCELLED TradeState = 2 // 取消/失败
)

// Enum value maps for TradeState.
var (
	TradeState_name = map[int32]string{
		0: "TRADE_OPEN",
		1: "TRADE_DONE",
		2: "TRADE_CANCELLED",
	}
	TradeState_value = map[string]int32{
		"TRADE_OPEN":      0,
		"TRADE_DONE":      1,
		"TRADE_CANCELLED": 2,
	}
)

func (x TradeState) Enum() *TradeState {
	p := new(TradeState)
	*p = x
	return p
}

func (x TradeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeState) Descriptor() protoreflect.EnumDescriptor {
	return file_trade_proto_enumTypes[1].Descriptor()
}

func (TradeState) Type() protoreflect.EnumType {
	return &file_trade_proto_enumTypes[1]
}

func (x TradeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeState.Descriptor instead.
func (TradeState) EnumDescriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{1}
}

type ClientTradeStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTradeStartRequest) Reset() {
	*x = ClientTradeStartRequest{}
	mi := &file_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTradeStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTradeStartRequest) ProtoMessage() {}

func (x *ClientTradeStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTradeStartRequest.ProtoReflect.Descriptor instead.
func (*ClientTradeStartRequest) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

func (x *ClientTradeStartRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientTradeStartRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type ClientTradeSetGoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Gold          int64                  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTradeSetGoldRequest) Reset() {
	*x = ClientTradeSetGoldRequest{}
	mi := &file_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTradeSetGoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTradeSetGoldRequest) ProtoMessage() {}

func (x *ClientTradeSetGoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTradeSetGoldRequest.ProtoReflect.Descriptor instead.
func (*ClientTradeSetGoldRequest) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{1}
}

func (x *ClientTradeSetGoldRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientTradeSetGoldRequest) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type ClientTradeConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTradeConfirmRequest) Reset() {
	*x = ClientTradeConfirmRequest{}
	mi := &file_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTradeConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTradeConfirmRequest) ProtoMessage() {}

func (x *ClientTradeConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTradeConfirmRequest.ProtoReflect.Descriptor instead.
func (*ClientTradeConfirmRequest) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{2}
}

func (x *ClientTradeConfirmRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ClientTradeCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTradeCancelRequest) Reset() {
	*x = ClientTradeCancelRequest{}
	mi := &file_trade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTradeCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTradeCancelRequest) ProtoMessage() {}

func (x *ClientTradeCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTradeCancelRequest.ProtoReflect.Descriptor instead.
func (*ClientTradeCancelRequest) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTradeCancelRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 交易状态通知：对称，双方收到同一份（含两侧报价/确认）
type ClientTradeUpdateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         int32                  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"` // TradeState
	APlayerId     int64                  `protobuf:"varint,2,opt,name=a_player_id,json=aPlayerId,proto3" json:"a_player_id,omitempty"`
	AGold         int64                  `protobuf:"varint,3,opt,name=a_gold,json=aGold,proto3" json:"a_gold,omitempty"`
	AConfirmed    bool                   `protobuf:"varint,4,opt,name=a_confirmed,json=aConfirmed,proto3" json:"a_confirmed,omitempty"`
	BPlayerId     int64                  `protobuf:"varint,5,opt,name=b_player_id,json=bPlayerId,proto3" json:"b_player_id,omitempty"`
	BGold         int64                  `protobuf:"varint,6,opt,name=b_gold,json=bGold,proto3" json:"b_gold,omitempty"`
	BConfirmed    bool                   `protobuf:"varint,7,opt,name=b_confirmed,json=bConfirmed,proto3" json:"b_confirmed,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"` // 失败/取消原因等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTradeUpdateNotify) Reset() {
	*x = ClientTradeUpdateNotify{}
	mi := &file_trade_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTradeUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTradeUpdateNotify) ProtoMessage() {}

func (x *ClientTradeUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTradeUpdateNotify.ProtoReflect.Descriptor instead.
func (*ClientTradeUpdateNotify) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{4}
}

func (x *ClientTradeUpdateNotify) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ClientTradeUpdateNotify) GetAPlayerId() int64 {
	if x != nil {
		return x.APlayerId
	}
	return 0
}

func (x *ClientTradeUpdateNotify) GetAGold() int64 {
	if x != nil {
		return x.AGold
	}
	return 0
}

func (x *ClientTradeUpdateNotify) GetAConfirmed() bool {
	if x != nil {
		return x.AConfirmed
	}
	return false
}

func (x *ClientTradeUpdateNotify) GetBPlayerId() int64 {
	if x != nil {
		return x.BPlayerId
	}
	return 0
}

func (x *ClientTradeUpdateNotify) GetBGold() int64 {
	if x != nil {
		return x.BGold
	}
	return 0
}

func (x *ClientTradeUpdateNotify) GetBConfirmed() bool {
	if x != nil {
		return x.BConfirmed
	}
	return false
}

func (x *ClientTradeUpdateNotify) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_trade_proto protoreflect.FileDescriptor

const file_trade_proto_rawDesc = "" +
	"\n" +
	"\vtrade.proto\x12\bprotocol\"S\n" +
	"\x17ClientTradeStartRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\"L\n" +
	"\x19ClientTradeSetGoldRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04gold\x18\x02 \x01(\x03R\x04gold\"8\n" +
	"\x19ClientTradeConfirmRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"7\n" +
	"\x18ClientTradeCancelRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\xf9\x01\n" +
	"\x17ClientTradeUpdateNotify\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\x12\x1e\n" +
	"\va_player_id\x18\x02 \x01(\x03R\taPlayerId\x12\x15\n" +
	"\x06a_gold\x18\x03 \x01(\x03R\x05aGold\x12\x1f\n" +
	"\va_confirmed\x18\x04 \x01(\bR\n" +
	"aConfirmed\x12\x1e\n" +
	"\vb_player_id\x18\x05 \x01(\x03R\tbPlayerId\x12\x15\n" +
	"\x06b_gold\x18\x06 \x01(\x03R\x05bGold\x12\x1f\n" +
	"\vb_confirmed\x18\a \x01(\bR\n" +
	"bConfirmed\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage*\x9f\x01\n" +
	"\n" +
	"TradeMsgId\x12\x15\n" +
	"\x11MSG_TRADE_INVALID\x10\x00\x12\x14\n" +
	"\x0fMSG_TRADE_START\x10\xa4\r\x12\x17\n" +
	"\x12MSG_TRADE_SET_GOLD\x10\xa6\r\x12\x16\n" +
	"\x11MSG_TRADE_CONFIRM\x10\xa8\r\x12\x15\n" +
	"\x10MSG_TRADE_CANCEL\x10\xaa\r\x12\x1c\n" +
	"\x17MSG_TRADE_UPDATE_NOTIFY\x10\xac\r*A\n" +
	"\n" +
	"TradeState\x12\x0e\n" +
	"\n" +
	"TRADE_OPEN\x10\x00\x12\x0e\n" +
	"\n" +
	"TRADE_DONE\x10\x01\x12\x13\n" +
	"\x0fTRADE_CANCELLED\x10\x02B\rZ\v./;protocolb\x06proto3"

var (
	file_trade_proto_rawDescOnce sync.Once
	file_trade_proto_rawDescData []byte
)

func file_trade_proto_rawDescGZIP() []byte {
	file_trade_proto_rawDescOnce.Do(func() {
		file_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)))
	})
	return file_trade_proto_rawDescData
}

var file_trade_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_trade_proto_goTypes = []any{
	(TradeMsgId)(0),                   // 0: protocol.TradeMsgId
	(TradeState)(0),                   // 1: protocol.TradeState
	(*ClientTradeStartRequest)(nil),   // 2: protocol.ClientTradeStartRequest
	(*ClientTradeSetGoldRequest)(nil), // 3: protocol.ClientTradeSetGoldRequest
	(*ClientTradeConfirmRequest)(nil), // 4: protocol.ClientTradeConfirmRequest
	(*ClientTradeCancelRequest)(nil),  // 5: protocol.ClientTradeCancelRequest
	(*ClientTradeUpdateNotify)(nil),   // 6: protocol.ClientTradeUpdateNotify
}
var file_trade_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trade_proto_init() }
func file_trade_proto_init() {
	if File_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_proto_goTypes,
		DependencyIndexes: file_trade_proto_depIdxs,
		EnumInfos:         file_trade_proto_enumTypes,
		MessageInfos:      file_trade_proto_msgTypes,
	}.Build()
	File_trade_proto = out.File
	file_trade_proto_goTypes = nil
	file_trade_proto_depIdxs = nil
}
