// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码定义
type ErrorCode int32

const (
	ErrorCode_ERR_SUCCESS           ErrorCode = 0
	ErrorCode_ERR_UNKNOWN           ErrorCode = 1
	ErrorCode_ERR_INVALID_PARAM     ErrorCode = 2
	ErrorCode_ERR_NOT_FOUND         ErrorCode = 3
	ErrorCode_ERR_ALREADY_EXISTS    ErrorCode = 4
	ErrorCode_ERR_PERMISSION_DENIED ErrorCode = 5
	ErrorCode_ERR_SERVER_BUSY       ErrorCode = 6
	ErrorCode_ERR_TIMEOUT           ErrorCode = 7
	ErrorCode_ERR_NOT_IMPLEMENTED   ErrorCode = 8
	// 账号相关错误 100-199
	ErrorCode_ERR_ACCOUNT_NOT_FOUND      ErrorCode = 100
	ErrorCode_ERR_ACCOUNT_ALREADY_EXISTS ErrorCode = 101
	ErrorCode_ERR_ACCOUNT_PASSWORD_WRONG ErrorCode = 102
	ErrorCode_ERR_ACCOUNT_BANNED         ErrorCode = 103
	ErrorCode_ERR_ACCOUNT_TOKEN_INVALID  ErrorCode = 104
	ErrorCode_ERR_ACCOUNT_TOKEN_EXPIRED  ErrorCode = 105
	// 玩家相关错误 200-299
	ErrorCode_ERR_PLAYER_NOT_FOUND   ErrorCode = 200
	ErrorCode_ERR_PLAYER_NAME_EXISTS ErrorCode = 201
	ErrorCode_ERR_PLAYER_LEVEL_LIMIT ErrorCode = 202
	ErrorCode_ERR_PLAYER_OFFLINE     ErrorCode = 203
	// 背包相关错误 300-399
	ErrorCode_ERR_BAG_FULL              ErrorCode = 300
	ErrorCode_ERR_ITEM_NOT_FOUND        ErrorCode = 301
	ErrorCode_ERR_ITEM_COUNT_NOT_ENOUGH ErrorCode = 302
	ErrorCode_ERR_ITEM_CANNOT_USE       ErrorCode = 303
	// 金币相关错误 400-499
	ErrorCode_ERR_GOLD_NOT_ENOUGH    ErrorCode = 400
	ErrorCode_ERR_DIAMOND_NOT_ENOUGH ErrorCode = 401
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERR_SUCCESS",
		1:   "ERR_UNKNOWN",
		2:   "ERR_INVALID_PARAM",
		3:   "ERR_NOT_FOUND",
		4:   "ERR_ALREADY_EXISTS",
		5:   "ERR_PERMISSION_DENIED",
		6:   "ERR_SERVER_BUSY",
		7:   "ERR_TIMEOUT",
		8:   "ERR_NOT_IMPLEMENTED",
		100: "ERR_ACCOUNT_NOT_FOUND",
		101: "ERR_ACCOUNT_ALREADY_EXISTS",
		102: "ERR_ACCOUNT_PASSWORD_WRONG",
		103: "ERR_ACCOUNT_BANNED",
		104: "ERR_ACCOUNT_TOKEN_INVALID",
		105: "ERR_ACCOUNT_TOKEN_EXPIRED",
		200: "ERR_PLAYER_NOT_FOUND",
		201: "ERR_PLAYER_NAME_EXISTS",
		202: "ERR_PLAYER_LEVEL_LIMIT",
		203: "ERR_PLAYER_OFFLINE",
		300: "ERR_BAG_FULL",
		301: "ERR_ITEM_NOT_FOUND",
		302: "ERR_ITEM_COUNT_NOT_ENOUGH",
		303: "ERR_ITEM_CANNOT_USE",
		400: "ERR_GOLD_NOT_ENOUGH",
		401: "ERR_DIAMOND_NOT_ENOUGH",
	}
	ErrorCode_value = map[string]int32{
		"ERR_SUCCESS":                0,
		"ERR_UNKNOWN":                1,
		"ERR_INVALID_PARAM":          2,
		"ERR_NOT_FOUND":              3,
		"ERR_ALREADY_EXISTS":         4,
		"ERR_PERMISSION_DENIED":      5,
		"ERR_SERVER_BUSY":            6,
		"ERR_TIMEOUT":                7,
		"ERR_NOT_IMPLEMENTED":        8,
		"ERR_ACCOUNT_NOT_FOUND":      100,
		"ERR_ACCOUNT_ALREADY_EXISTS": 101,
		"ERR_ACCOUNT_PASSWORD_WRONG": 102,
		"ERR_ACCOUNT_BANNED":         103,
		"ERR_ACCOUNT_TOKEN_INVALID":  104,
		"ERR_ACCOUNT_TOKEN_EXPIRED":  105,
		"ERR_PLAYER_NOT_FOUND":       200,
		"ERR_PLAYER_NAME_EXISTS":     201,
		"ERR_PLAYER_LEVEL_LIMIT":     202,
		"ERR_PLAYER_OFFLINE":         203,
		"ERR_BAG_FULL":               300,
		"ERR_ITEM_NOT_FOUND":         301,
		"ERR_ITEM_COUNT_NOT_ENOUGH":  302,
		"ERR_ITEM_CANNOT_USE":        303,
		"ERR_GOLD_NOT_ENOUGH":        400,
		"ERR_DIAMOND_NOT_ENOUGH":     401,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 通用响应结构
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // ErrorCode
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CommonResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 分页请求
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 分页响应
type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// 时间范围
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeRange) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 坐标信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Orientation   float32                `protobuf:"fixed32,4,opt,name=orientation,proto3" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Position) GetOrientation() float32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

// Buff详细信息
type BuffDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuffId        int32                  `protobuf:"varint,1,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"`
	BuffName      string                 `protobuf:"bytes,2,opt,name=buff_name,json=buffName,proto3" json:"buff_name,omitempty"`
	BuffDesc      string                 `protobuf:"bytes,3,opt,name=buff_desc,json=buffDesc,proto3" json:"buff_desc,omitempty"`
	BuffType      int32                  `protobuf:"varint,4,opt,name=buff_type,json=buffType,proto3" json:"buff_type,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	RemainingTime int32                  `protobuf:"varint,6,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
	Stacks        int32                  `protobuf:"varint,7,opt,name=stacks,proto3" json:"stacks,omitempty"`
	IsBeneficial  bool                   `protobuf:"varint,8,opt,name=is_beneficial,json=isBeneficial,proto3" json:"is_beneficial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffDetail) Reset() {
	*x = BuffDetail{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffDetail) ProtoMessage() {}

func (x *BuffDetail) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffDetail.ProtoReflect.Descriptor instead.
func (*BuffDetail) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *BuffDetail) GetBuffId() int32 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *BuffDetail) GetBuffName() string {
	if x != nil {
		return x.BuffName
	}
	return ""
}

func (x *BuffDetail) GetBuffDesc() string {
	if x != nil {
		return x.BuffDesc
	}
	return ""
}

func (x *BuffDetail) GetBuffType() int32 {
	if x != nil {
		return x.BuffType
	}
	return 0
}

func (x *BuffDetail) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BuffDetail) GetRemainingTime() int32 {
	if x != nil {
		return x.RemainingTime
	}
	return 0
}

func (x *BuffDetail) GetStacks() int32 {
	if x != nil {
		return x.Stacks
	}
	return 0
}

func (x *BuffDetail) GetIsBeneficial() bool {
	if x != nil {
		return x.IsBeneficial
	}
	return false
}

// 活动详细信息
type ActivityDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityName  string                 `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	ActivityDesc  string                 `protobuf:"bytes,3,opt,name=activity_desc,json=activityDesc,proto3" json:"activity_desc,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Config        map[string]string      `protobuf:"bytes,7,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityDetail) Reset() {
	*x = ActivityDetail{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDetail) ProtoMessage() {}

func (x *ActivityDetail) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDetail.ProtoReflect.Descriptor instead.
func (*ActivityDetail) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *ActivityDetail) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityDetail) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *ActivityDetail) GetActivityDesc() string {
	if x != nil {
		return x.ActivityDesc
	}
	return ""
}

func (x *ActivityDetail) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ActivityDetail) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ActivityDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityDetail) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// Buff列表响应
type BuffListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Buffs         []*BuffDetail          `protobuf:"bytes,3,rep,name=buffs,proto3" json:"buffs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffListResponse) Reset() {
	*x = BuffListResponse{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffListResponse) ProtoMessage() {}

func (x *BuffListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffListResponse.ProtoReflect.Descriptor instead.
func (*BuffListResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *BuffListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *BuffListResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *BuffListResponse) GetBuffs() []*BuffDetail {
	if x != nil {
		return x.Buffs
	}
	return nil
}

// 活动列表响应
type ActivityListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Activities    []*ActivityDetail      `protobuf:"bytes,3,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityListResponse) Reset() {
	*x = ActivityListResponse{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityListResponse) ProtoMessage() {}

func (x *ActivityListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityListResponse.ProtoReflect.Descriptor instead.
func (*ActivityListResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *ActivityListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ActivityListResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ActivityListResponse) GetActivities() []*ActivityDetail {
	if x != nil {
		return x.Activities
	}
	return nil
}

// 掉落物品信息
type DropItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	IsRare        bool                   `protobuf:"varint,3,opt,name=is_rare,json=isRare,proto3" json:"is_rare,omitempty"`
	BindType      int32                  `protobuf:"varint,4,opt,name=bind_type,json=bindType,proto3" json:"bind_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropItemInfo) Reset() {
	*x = DropItemInfo{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropItemInfo) ProtoMessage() {}

func (x *DropItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropItemInfo.ProtoReflect.Descriptor instead.
func (*DropItemInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *DropItemInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *DropItemInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DropItemInfo) GetIsRare() bool {
	if x != nil {
		return x.IsRare
	}
	return false
}

func (x *DropItemInfo) GetBindType() int32 {
	if x != nil {
		return x.BindType
	}
	return 0
}

// 掉落实体信息
type DropEntityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Items         []*DropItemInfo        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Gold          int64                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	OwnerId       int64                  `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IsProtected   bool                   `protobuf:"varint,6,opt,name=is_protected,json=isProtected,proto3" json:"is_protected,omitempty"`
	ProtectTime   int32                  `protobuf:"varint,7,opt,name=protect_time,json=protectTime,proto3" json:"protect_time,omitempty"`
	PositionX     float32                `protobuf:"fixed32,8,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY     float32                `protobuf:"fixed32,9,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	PositionZ     float32                `protobuf:"fixed32,10,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropEntityInfo) Reset() {
	*x = DropEntityInfo{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropEntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropEntityInfo) ProtoMessage() {}

func (x *DropEntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropEntityInfo.ProtoReflect.Descriptor instead.
func (*DropEntityInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *DropEntityInfo) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *DropEntityInfo) GetItems() []*DropItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DropEntityInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *DropEntityInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *DropEntityInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *DropEntityInfo) GetIsProtected() bool {
	if x != nil {
		return x.IsProtected
	}
	return false
}

func (x *DropEntityInfo) GetProtectTime() int32 {
	if x != nil {
		return x.ProtectTime
	}
	return 0
}

func (x *DropEntityInfo) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *DropEntityInfo) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *DropEntityInfo) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

// 掉落拾取响应
type DropPickupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Items         []*DropItemInfo        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Gold          int64                  `protobuf:"varint,4,opt,name=gold,proto3" json:"gold,omitempty"`
	Exp           int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropPickupResponse) Reset() {
	*x = DropPickupResponse{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropPickupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropPickupResponse) ProtoMessage() {}

func (x *DropPickupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropPickupResponse.ProtoReflect.Descriptor instead.
func (*DropPickupResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *DropPickupResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *DropPickupResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *DropPickupResponse) GetItems() []*DropItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DropPickupResponse) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *DropPickupResponse) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// 掉落列表响应
type DropListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Drops         []*DropEntityInfo      `protobuf:"bytes,3,rep,name=drops,proto3" json:"drops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropListResponse) Reset() {
	*x = DropListResponse{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropListResponse) ProtoMessage() {}

func (x *DropListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropListResponse.ProtoReflect.Descriptor instead.
func (*DropListResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *DropListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *DropListResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *DropListResponse) GetDrops() []*DropEntityInfo {
	if x != nil {
		return x.Drops
	}
	return nil
}

// 副本信息
type DungeonInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DungeonId        int32                  `protobuf:"varint,1,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`
	DungeonName      string                 `protobuf:"bytes,2,opt,name=dungeon_name,json=dungeonName,proto3" json:"dungeon_name,omitempty"`
	DungeonDesc      string                 `protobuf:"bytes,3,opt,name=dungeon_desc,json=dungeonDesc,proto3" json:"dungeon_desc,omitempty"`
	LevelRequirement int32                  `protobuf:"varint,4,opt,name=level_requirement,json=levelRequirement,proto3" json:"level_requirement,omitempty"`
	RecommendedLevel int32                  `protobuf:"varint,5,opt,name=recommended_level,json=recommendedLevel,proto3" json:"recommended_level,omitempty"`
	MaxPlayers       int32                  `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Difficulty       int32                  `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	EntryCost        int64                  `protobuf:"varint,8,opt,name=entry_cost,json=entryCost,proto3" json:"entry_cost,omitempty"`
	GoldReward       int64                  `protobuf:"varint,9,opt,name=gold_reward,json=goldReward,proto3" json:"gold_reward,omitempty"`
	ExpReward        int64                  `protobuf:"varint,10,opt,name=exp_reward,json=expReward,proto3" json:"exp_reward,omitempty"`
	CooldownHours    int32                  `protobuf:"varint,11,opt,name=cooldown_hours,json=cooldownHours,proto3" json:"cooldown_hours,omitempty"`
	IsUnlocked       bool                   `protobuf:"varint,12,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DungeonInfo) Reset() {
	*x = DungeonInfo{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonInfo) ProtoMessage() {}

func (x *DungeonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonInfo.ProtoReflect.Descriptor instead.
func (*DungeonInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *DungeonInfo) GetDungeonId() int32 {
	if x != nil {
		return x.DungeonId
	}
	return 0
}

func (x *DungeonInfo) GetDungeonName() string {
	if x != nil {
		return x.DungeonName
	}
	return ""
}

func (x *DungeonInfo) GetDungeonDesc() string {
	if x != nil {
		return x.DungeonDesc
	}
	return ""
}

func (x *DungeonInfo) GetLevelRequirement() int32 {
	if x != nil {
		return x.LevelRequirement
	}
	return 0
}

func (x *DungeonInfo) GetRecommendedLevel() int32 {
	if x != nil {
		return x.RecommendedLevel
	}
	return 0
}

func (x *DungeonInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *DungeonInfo) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *DungeonInfo) GetEntryCost() int64 {
	if x != nil {
		return x.EntryCost
	}
	return 0
}

func (x *DungeonInfo) GetGoldReward() int64 {
	if x != nil {
		return x.GoldReward
	}
	return 0
}

func (x *DungeonInfo) GetExpReward() int64 {
	if x != nil {
		return x.ExpReward
	}
	return 0
}

func (x *DungeonInfo) GetCooldownHours() int32 {
	if x != nil {
		return x.CooldownHours
	}
	return 0
}

func (x *DungeonInfo) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

// 副本列表响应
type DungeonListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Dungeons      []*DungeonInfo         `protobuf:"bytes,3,rep,name=dungeons,proto3" json:"dungeons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonListResponse) Reset() {
	*x = DungeonListResponse{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonListResponse) ProtoMessage() {}

func (x *DungeonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonListResponse.ProtoReflect.Descriptor instead.
func (*DungeonListResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *DungeonListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *DungeonListResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *DungeonListResponse) GetDungeons() []*DungeonInfo {
	if x != nil {
		return x.Dungeons
	}
	return nil
}

// 商店物品信息
type ShopItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ShopId        int32                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,4,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDesc      string                 `protobuf:"bytes,5,opt,name=item_desc,json=itemDesc,proto3" json:"item_desc,omitempty"`
	Price         int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CurrencyType  int32                  `protobuf:"varint,7,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"` // 1=金币, 2=钻石, 3=积分
	Stock         int32                  `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxStock      int32                  `protobuf:"varint,9,opt,name=max_stock,json=maxStock,proto3" json:"max_stock,omitempty"`
	IsLimited     bool                   `protobuf:"varint,10,opt,name=is_limited,json=isLimited,proto3" json:"is_limited,omitempty"`
	RefreshTime   int64                  `protobuf:"varint,11,opt,name=refresh_time,json=refreshTime,proto3" json:"refresh_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItemInfo) Reset() {
	*x = ShopItemInfo{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItemInfo) ProtoMessage() {}

func (x *ShopItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItemInfo.ProtoReflect.Descriptor instead.
func (*ShopItemInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *ShopItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ShopItemInfo) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopItemInfo) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ShopItemInfo) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ShopItemInfo) GetItemDesc() string {
	if x != nil {
		return x.ItemDesc
	}
	return ""
}

func (x *ShopItemInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShopItemInfo) GetCurrencyType() int32 {
	if x != nil {
		return x.CurrencyType
	}
	return 0
}

func (x *ShopItemInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ShopItemInfo) GetMaxStock() int32 {
	if x != nil {
		return x.MaxStock
	}
	return 0
}

func (x *ShopItemInfo) GetIsLimited() bool {
	if x != nil {
		return x.IsLimited
	}
	return false
}

func (x *ShopItemInfo) GetRefreshTime() int64 {
	if x != nil {
		return x.RefreshTime
	}
	return 0
}

// 商店分类信息
type ShopCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ShopId        int32                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryDesc  string                 `protobuf:"bytes,4,opt,name=category_desc,json=categoryDesc,proto3" json:"category_desc,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCategoryInfo) Reset() {
	*x = ShopCategoryInfo{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCategoryInfo) ProtoMessage() {}

func (x *ShopCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCategoryInfo.ProtoReflect.Descriptor instead.
func (*ShopCategoryInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *ShopCategoryInfo) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ShopCategoryInfo) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopCategoryInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ShopCategoryInfo) GetCategoryDesc() string {
	if x != nil {
		return x.CategoryDesc
	}
	return ""
}

func (x *ShopCategoryInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// 商店物品列表响应
type ShopItemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Items         []*ShopItemInfo        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItemListResponse) Reset() {
	*x = ShopItemListResponse{}
	mi := &file_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItemListResponse) ProtoMessage() {}

func (x *ShopItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItemListResponse.ProtoReflect.Descriptor instead.
func (*ShopItemListResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *ShopItemListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ShopItemListResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ShopItemListResponse) GetItems() []*ShopItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// 商店分类列表响应
type ShopCategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Categories    []*ShopCategoryInfo    `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCategoryListResponse) Reset() {
	*x = ShopCategoryListResponse{}
	mi := &file_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCategoryListResponse) ProtoMessage() {}

func (x *ShopCategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCategoryListResponse.ProtoReflect.Descriptor instead.
func (*ShopCategoryListResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18}
}

func (x *ShopCategoryListResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ShopCategoryListResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ShopCategoryListResponse) GetCategories() []*ShopCategoryInfo {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bprotocol\"E\n" +
	"\x0eCommonResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\">\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"v\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"E\n" +
	"\tTimeRange\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"V\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12 \n" +
	"\vorientation\x18\x04 \x01(\x02R\vorientation\"\xfc\x01\n" +
	"\n" +
	"BuffDetail\x12\x17\n" +
	"\abuff_id\x18\x01 \x01(\x05R\x06buffId\x12\x1b\n" +
	"\tbuff_name\x18\x02 \x01(\tR\bbuffName\x12\x1b\n" +
	"\tbuff_desc\x18\x03 \x01(\tR\bbuffDesc\x12\x1b\n" +
	"\tbuff_type\x18\x04 \x01(\x05R\bbuffType\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12%\n" +
	"\x0eremaining_time\x18\x06 \x01(\x05R\rremainingTime\x12\x16\n" +
	"\x06stacks\x18\a \x01(\x05R\x06stacks\x12#\n" +
	"\ris_beneficial\x18\b \x01(\bR\fisBeneficial\"\xc6\x02\n" +
	"\x0eActivityDetail\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x12#\n" +
	"\ractivity_desc\x18\x03 \x01(\tR\factivityDesc\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12<\n" +
	"\x06config\x18\a \x03(\v2$.protocol.ActivityDetail.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x10BuffListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12*\n" +
	"\x05buffs\x18\x03 \x03(\v2\x14.protocol.BuffDetailR\x05buffs\"\x85\x01\n" +
	"\x14ActivityListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x128\n" +
	"\n" +
	"activities\x18\x03 \x03(\v2\x18.protocol.ActivityDetailR\n" +
	"activities\"s\n" +
	"\fDropItemInfo\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x17\n" +
	"\ais_rare\x18\x03 \x01(\bR\x06isRare\x12\x1b\n" +
	"\tbind_type\x18\x04 \x01(\x05R\bbindType\"\xbf\x02\n" +
	"\x0eDropEntityInfo\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x03R\bentityId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.protocol.DropItemInfoR\x05items\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x03R\x04gold\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\x03R\aownerId\x12!\n" +
	"\fis_protected\x18\x06 \x01(\bR\visProtected\x12!\n" +
	"\fprotect_time\x18\a \x01(\x05R\vprotectTime\x12\x1d\n" +
	"\n" +
	"position_x\x18\b \x01(\x02R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\t \x01(\x02R\tpositionY\x12\x1d\n" +
	"\n" +
	"position_z\x18\n" +
	" \x01(\x02R\tpositionZ\"\x9d\x01\n" +
	"\x12DropPickupResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12,\n" +
	"\x05items\x18\x03 \x03(\v2\x16.protocol.DropItemInfoR\x05items\x12\x12\n" +
	"\x04gold\x18\x04 \x01(\x03R\x04gold\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\"w\n" +
	"\x10DropListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12.\n" +
	"\x05drops\x18\x03 \x03(\v2\x18.protocol.DropEntityInfoR\x05drops\"\xb4\x03\n" +
	"\vDungeonInfo\x12\x1d\n" +
	"\n" +
	"dungeon_id\x18\x01 \x01(\x05R\tdungeonId\x12!\n" +
	"\fdungeon_name\x18\x02 \x01(\tR\vdungeonName\x12!\n" +
	"\fdungeon_desc\x18\x03 \x01(\tR\vdungeonDesc\x12+\n" +
	"\x11level_requirement\x18\x04 \x01(\x05R\x10levelRequirement\x12+\n" +
	"\x11recommended_level\x18\x05 \x01(\x05R\x10recommendedLevel\x12\x1f\n" +
	"\vmax_players\x18\x06 \x01(\x05R\n" +
	"maxPlayers\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\x05R\n" +
	"difficulty\x12\x1d\n" +
	"\n" +
	"entry_cost\x18\b \x01(\x03R\tentryCost\x12\x1f\n" +
	"\vgold_reward\x18\t \x01(\x03R\n" +
	"goldReward\x12\x1d\n" +
	"\n" +
	"exp_reward\x18\n" +
	" \x01(\x03R\texpReward\x12%\n" +
	"\x0ecooldown_hours\x18\v \x01(\x05R\rcooldownHours\x12\x1f\n" +
	"\vis_unlocked\x18\f \x01(\bR\n" +
	"isUnlocked\"}\n" +
	"\x13DungeonListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x121\n" +
	"\bdungeons\x18\x03 \x03(\v2\x15.protocol.DungeonInfoR\bdungeons\"\xcb\x02\n" +
	"\fShopItemInfo\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x05R\x06shopId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12\x1b\n" +
	"\titem_name\x18\x04 \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_desc\x18\x05 \x01(\tR\bitemDesc\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12#\n" +
	"\rcurrency_type\x18\a \x01(\x05R\fcurrencyType\x12\x14\n" +
	"\x05stock\x18\b \x01(\x05R\x05stock\x12\x1b\n" +
	"\tmax_stock\x18\t \x01(\x05R\bmaxStock\x12\x1d\n" +
	"\n" +
	"is_limited\x18\n" +
	" \x01(\bR\tisLimited\x12!\n" +
	"\frefresh_time\x18\v \x01(\x03R\vrefreshTime\"\xb5\x01\n" +
	"\x10ShopCategoryInfo\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x05R\x06shopId\x12#\n" +
	"\rcategory_name\x18\x03 \x01(\tR\fcategoryName\x12#\n" +
	"\rcategory_desc\x18\x04 \x01(\tR\fcategoryDesc\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"y\n" +
	"\x14ShopItemListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12,\n" +
	"\x05items\x18\x03 \x03(\v2\x16.protocol.ShopItemInfoR\x05items\"\x8b\x01\n" +
	"\x18ShopCategoryListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12:\n" +
	"\n" +
	"categories\x18\x03 \x03(\v2\x1a.protocol.ShopCategoryInfoR\n" +
	"categories*\x85\x05\n" +
	"\tErrorCode\x12\x0f\n" +
	"\vERR_SUCCESS\x10\x00\x12\x0f\n" +
	"\vERR_UNKNOWN\x10\x01\x12\x15\n" +
	"\x11ERR_INVALID_PARAM\x10\x02\x12\x11\n" +
	"\rERR_NOT_FOUND\x10\x03\x12\x16\n" +
	"\x12ERR_ALREADY_EXISTS\x10\x04\x12\x19\n" +
	"\x15ERR_PERMISSION_DENIED\x10\x05\x12\x13\n" +
	"\x0fERR_SERVER_BUSY\x10\x06\x12\x0f\n" +
	"\vERR_TIMEOUT\x10\a\x12\x17\n" +
	"\x13ERR_NOT_IMPLEMENTED\x10\b\x12\x19\n" +
	"\x15ERR_ACCOUNT_NOT_FOUND\x10d\x12\x1e\n" +
	"\x1aERR_ACCOUNT_ALREADY_EXISTS\x10e\x12\x1e\n" +
	"\x1aERR_ACCOUNT_PASSWORD_WRONG\x10f\x12\x16\n" +
	"\x12ERR_ACCOUNT_BANNED\x10g\x12\x1d\n" +
	"\x19ERR_ACCOUNT_TOKEN_INVALID\x10h\x12\x1d\n" +
	"\x19ERR_ACCOUNT_TOKEN_EXPIRED\x10i\x12\x19\n" +
	"\x14ERR_PLAYER_NOT_FOUND\x10\xc8\x01\x12\x1b\n" +
	"\x16ERR_PLAYER_NAME_EXISTS\x10\xc9\x01\x12\x1b\n" +
	"\x16ERR_PLAYER_LEVEL_LIMIT\x10\xca\x01\x12\x17\n" +
	"\x12ERR_PLAYER_OFFLINE\x10\xcb\x01\x12\x11\n" +
	"\fERR_BAG_FULL\x10\xac\x02\x12\x17\n" +
	"\x12ERR_ITEM_NOT_FOUND\x10\xad\x02\x12\x1e\n" +
	"\x19ERR_ITEM_COUNT_NOT_ENOUGH\x10\xae\x02\x12\x18\n" +
	"\x13ERR_ITEM_CANNOT_USE\x10\xaf\x02\x12\x18\n" +
	"\x13ERR_GOLD_NOT_ENOUGH\x10\x90\x03\x12\x1b\n" +
	"\x16ERR_DIAMOND_NOT_ENOUGH\x10\x91\x03B\rZ\v./;protocolb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_common_proto_goTypes = []any{
	(ErrorCode)(0),                   // 0: protocol.ErrorCode
	(*CommonResponse)(nil),           // 1: protocol.CommonResponse
	(*PageRequest)(nil),              // 2: protocol.PageRequest
	(*PageResponse)(nil),             // 3: protocol.PageResponse
	(*TimeRange)(nil),                // 4: protocol.TimeRange
	(*Position)(nil),                 // 5: protocol.Position
	(*BuffDetail)(nil),               // 6: protocol.BuffDetail
	(*ActivityDetail)(nil),           // 7: protocol.ActivityDetail
	(*BuffListResponse)(nil),         // 8: protocol.BuffListResponse
	(*ActivityListResponse)(nil),     // 9: protocol.ActivityListResponse
	(*DropItemInfo)(nil),             // 10: protocol.DropItemInfo
	(*DropEntityInfo)(nil),           // 11: protocol.DropEntityInfo
	(*DropPickupResponse)(nil),       // 12: protocol.DropPickupResponse
	(*DropListResponse)(nil),         // 13: protocol.DropListResponse
	(*DungeonInfo)(nil),              // 14: protocol.DungeonInfo
	(*DungeonListResponse)(nil),      // 15: protocol.DungeonListResponse
	(*ShopItemInfo)(nil),             // 16: protocol.ShopItemInfo
	(*ShopCategoryInfo)(nil),         // 17: protocol.ShopCategoryInfo
	(*ShopItemListResponse)(nil),     // 18: protocol.ShopItemListResponse
	(*ShopCategoryListResponse)(nil), // 19: protocol.ShopCategoryListResponse
	nil,                              // 20: protocol.ActivityDetail.ConfigEntry
}
var file_common_proto_depIdxs = []int32{
	20, // 0: protocol.ActivityDetail.config:type_name -> protocol.ActivityDetail.ConfigEntry
	6,  // 1: protocol.BuffListResponse.buffs:type_name -> protocol.BuffDetail
	7,  // 2: protocol.ActivityListResponse.activities:type_name -> protocol.ActivityDetail
	10, // 3: protocol.DropEntityInfo.items:type_name -> protocol.DropItemInfo
	10, // 4: protocol.DropPickupResponse.items:type_name -> protocol.DropItemInfo
	11, // 5: protocol.DropListResponse.drops:type_name -> protocol.DropEntityInfo
	14, // 6: protocol.DungeonListResponse.dungeons:type_name -> protocol.DungeonInfo
	16, // 7: protocol.ShopItemListResponse.items:type_name -> protocol.ShopItemInfo
	17, // 8: protocol.ShopCategoryListResponse.categories:type_name -> protocol.ShopCategoryInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
